/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.gt.dao.nhapcanh.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the CrewList service. Represents a row in the &quot;crew_list&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link vn.gt.dao.nhapcanh.model.impl.CrewListModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link vn.gt.dao.nhapcanh.model.impl.CrewListImpl}.
 * </p>
 *
 * @author win_64
 * @see CrewList
 * @see vn.gt.dao.nhapcanh.model.impl.CrewListImpl
 * @see vn.gt.dao.nhapcanh.model.impl.CrewListModelImpl
 * @generated
 */
public interface CrewListModel extends BaseModel<CrewList> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a crew list model instance should use the {@link CrewList} interface instead.
	 */

	/**
	 * Returns the primary key of this crew list.
	 *
	 * @return the primary key of this crew list
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this crew list.
	 *
	 * @param primaryKey the primary key of this crew list
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this crew list.
	 *
	 * @return the ID of this crew list
	 */
	public long getId();

	/**
	 * Sets the ID of this crew list.
	 *
	 * @param id the ID of this crew list
	 */
	public void setId(long id);

	/**
	 * Returns the crew code of this crew list.
	 *
	 * @return the crew code of this crew list
	 */
	@AutoEscape
	public String getCrewCode();

	/**
	 * Sets the crew code of this crew list.
	 *
	 * @param crewCode the crew code of this crew list
	 */
	public void setCrewCode(String crewCode);

	/**
	 * Returns the document no of this crew list.
	 *
	 * @return the document no of this crew list
	 */
	@AutoEscape
	public String getDocumentNo();

	/**
	 * Sets the document no of this crew list.
	 *
	 * @param documentNo the document no of this crew list
	 */
	public void setDocumentNo(String documentNo);

	/**
	 * Returns the state code of this crew list.
	 *
	 * @return the state code of this crew list
	 */
	@AutoEscape
	public String getStateCode();

	/**
	 * Sets the state code of this crew list.
	 *
	 * @param stateCode the state code of this crew list
	 */
	public void setStateCode(String stateCode);

	/**
	 * Returns the birth day of this crew list.
	 *
	 * @return the birth day of this crew list
	 */
	public Date getBirthDay();

	/**
	 * Sets the birth day of this crew list.
	 *
	 * @param birthDay the birth day of this crew list
	 */
	public void setBirthDay(Date birthDay);

	/**
	 * Returns the birth place of this crew list.
	 *
	 * @return the birth place of this crew list
	 */
	@AutoEscape
	public String getBirthPlace();

	/**
	 * Sets the birth place of this crew list.
	 *
	 * @param birthPlace the birth place of this crew list
	 */
	public void setBirthPlace(String birthPlace);

	/**
	 * Returns the family name of this crew list.
	 *
	 * @return the family name of this crew list
	 */
	@AutoEscape
	public String getFamilyName();

	/**
	 * Sets the family name of this crew list.
	 *
	 * @param familyName the family name of this crew list
	 */
	public void setFamilyName(String familyName);

	/**
	 * Returns the full name of this crew list.
	 *
	 * @return the full name of this crew list
	 */
	@AutoEscape
	public String getFullName();

	/**
	 * Sets the full name of this crew list.
	 *
	 * @param fullName the full name of this crew list
	 */
	public void setFullName(String fullName);

	/**
	 * Returns the given name of this crew list.
	 *
	 * @return the given name of this crew list
	 */
	@AutoEscape
	public String getGivenName();

	/**
	 * Sets the given name of this crew list.
	 *
	 * @param givenName the given name of this crew list
	 */
	public void setGivenName(String givenName);

	/**
	 * Returns the passport number of this crew list.
	 *
	 * @return the passport number of this crew list
	 */
	@AutoEscape
	public String getPassportNumber();

	/**
	 * Sets the passport number of this crew list.
	 *
	 * @param passportNumber the passport number of this crew list
	 */
	public void setPassportNumber(String passportNumber);

	/**
	 * Returns the passport type of this crew list.
	 *
	 * @return the passport type of this crew list
	 */
	@AutoEscape
	public String getPassportType();

	/**
	 * Sets the passport type of this crew list.
	 *
	 * @param passportType the passport type of this crew list
	 */
	public void setPassportType(String passportType);

	/**
	 * Returns the rank code of this crew list.
	 *
	 * @return the rank code of this crew list
	 */
	@AutoEscape
	public String getRankCode();

	/**
	 * Sets the rank code of this crew list.
	 *
	 * @param rankCode the rank code of this crew list
	 */
	public void setRankCode(String rankCode);

	/**
	 * Returns the create date of this crew list.
	 *
	 * @return the create date of this crew list
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this crew list.
	 *
	 * @param createDate the create date of this crew list
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modify date of this crew list.
	 *
	 * @return the modify date of this crew list
	 */
	public Date getModifyDate();

	/**
	 * Sets the modify date of this crew list.
	 *
	 * @param modifyDate the modify date of this crew list
	 */
	public void setModifyDate(Date modifyDate);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(CrewList crewList);

	public int hashCode();

	public CacheModel<CrewList> toCacheModel();

	public CrewList toEscapedModel();

	public String toString();

	public String toXmlString();
}