/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.gt.dao.nhapcanh.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the DocumentGeneral service. Represents a row in the &quot;document_general&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link vn.gt.dao.nhapcanh.model.impl.DocumentGeneralModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link vn.gt.dao.nhapcanh.model.impl.DocumentGeneralImpl}.
 * </p>
 *
 * @author win_64
 * @see DocumentGeneral
 * @see vn.gt.dao.nhapcanh.model.impl.DocumentGeneralImpl
 * @see vn.gt.dao.nhapcanh.model.impl.DocumentGeneralModelImpl
 * @generated
 */
public interface DocumentGeneralModel extends BaseModel<DocumentGeneral> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a document general model instance should use the {@link DocumentGeneral} interface instead.
	 */

	/**
	 * Returns the primary key of this document general.
	 *
	 * @return the primary key of this document general
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this document general.
	 *
	 * @param primaryKey the primary key of this document general
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this document general.
	 *
	 * @return the ID of this document general
	 */
	public long getId();

	/**
	 * Sets the ID of this document general.
	 *
	 * @param id the ID of this document general
	 */
	public void setId(long id);

	/**
	 * Returns the document no of this document general.
	 *
	 * @return the document no of this document general
	 */
	@AutoEscape
	public String getDocumentNo();

	/**
	 * Sets the document no of this document general.
	 *
	 * @param documentNo the document no of this document general
	 */
	public void setDocumentNo(String documentNo);

	/**
	 * Returns the document function of this document general.
	 *
	 * @return the document function of this document general
	 */
	@AutoEscape
	public String getDocumentFunction();

	/**
	 * Sets the document function of this document general.
	 *
	 * @param documentFunction the document function of this document general
	 */
	public void setDocumentFunction(String documentFunction);

	/**
	 * Returns the is arrival of this document general.
	 *
	 * @return the is arrival of this document general
	 */
	public int getIsArrival();

	/**
	 * Sets the is arrival of this document general.
	 *
	 * @param isArrival the is arrival of this document general
	 */
	public void setIsArrival(int isArrival);

	/**
	 * Returns the is departure of this document general.
	 *
	 * @return the is departure of this document general
	 */
	public int getIsDeparture();

	/**
	 * Sets the is departure of this document general.
	 *
	 * @param isDeparture the is departure of this document general
	 */
	public void setIsDeparture(int isDeparture);

	/**
	 * Returns the ship code of this document general.
	 *
	 * @return the ship code of this document general
	 */
	@AutoEscape
	public String getShipCode();

	/**
	 * Sets the ship code of this document general.
	 *
	 * @param shipCode the ship code of this document general
	 */
	public void setShipCode(String shipCode);

	/**
	 * Returns the arrival or departure port code of this document general.
	 *
	 * @return the arrival or departure port code of this document general
	 */
	@AutoEscape
	public String getArrivalOrDeparturePortCode();

	/**
	 * Sets the arrival or departure port code of this document general.
	 *
	 * @param arrivalOrDeparturePortCode the arrival or departure port code of this document general
	 */
	public void setArrivalOrDeparturePortCode(String arrivalOrDeparturePortCode);

	/**
	 * Returns the time arrival or departure of this document general.
	 *
	 * @return the time arrival or departure of this document general
	 */
	public Date getTimeArrivalOrDeparture();

	/**
	 * Sets the time arrival or departure of this document general.
	 *
	 * @param timeArrivalOrDeparture the time arrival or departure of this document general
	 */
	public void setTimeArrivalOrDeparture(Date timeArrivalOrDeparture);

	/**
	 * Returns the imo number of this document general.
	 *
	 * @return the imo number of this document general
	 */
	@AutoEscape
	public String getImoNumber();

	/**
	 * Sets the imo number of this document general.
	 *
	 * @param imoNumber the imo number of this document general
	 */
	public void setImoNumber(String imoNumber);

	/**
	 * Returns the call sign of this document general.
	 *
	 * @return the call sign of this document general
	 */
	@AutoEscape
	public String getCallSign();

	/**
	 * Sets the call sign of this document general.
	 *
	 * @param callSign the call sign of this document general
	 */
	public void setCallSign(String callSign);

	/**
	 * Returns the voyage number of this document general.
	 *
	 * @return the voyage number of this document general
	 */
	public int getVoyageNumber();

	/**
	 * Sets the voyage number of this document general.
	 *
	 * @param voyageNumber the voyage number of this document general
	 */
	public void setVoyageNumber(int voyageNumber);

	/**
	 * Returns the ship nation code of this document general.
	 *
	 * @return the ship nation code of this document general
	 */
	@AutoEscape
	public String getShipNationCode();

	/**
	 * Sets the ship nation code of this document general.
	 *
	 * @param shipNationCode the ship nation code of this document general
	 */
	public void setShipNationCode(String shipNationCode);

	/**
	 * Returns the name of master of this document general.
	 *
	 * @return the name of master of this document general
	 */
	@AutoEscape
	public String getNameOfMaster();

	/**
	 * Sets the name of master of this document general.
	 *
	 * @param nameOfMaster the name of master of this document general
	 */
	public void setNameOfMaster(String nameOfMaster);

	/**
	 * Returns the last port of this document general.
	 *
	 * @return the last port of this document general
	 */
	@AutoEscape
	public String getLastPort();

	/**
	 * Sets the last port of this document general.
	 *
	 * @param lastPort the last port of this document general
	 */
	public void setLastPort(String lastPort);

	/**
	 * Returns the contact detail ship agent of this document general.
	 *
	 * @return the contact detail ship agent of this document general
	 */
	@AutoEscape
	public String getContactDetailShipAgent();

	/**
	 * Sets the contact detail ship agent of this document general.
	 *
	 * @param contactDetailShipAgent the contact detail ship agent of this document general
	 */
	public void setContactDetailShipAgent(String contactDetailShipAgent);

	/**
	 * Returns the gross tonnage of this document general.
	 *
	 * @return the gross tonnage of this document general
	 */
	public double getGrossTonnage();

	/**
	 * Sets the gross tonnage of this document general.
	 *
	 * @param grossTonnage the gross tonnage of this document general
	 */
	public void setGrossTonnage(double grossTonnage);

	/**
	 * Returns the net tonnage of this document general.
	 *
	 * @return the net tonnage of this document general
	 */
	public double getNetTonnage();

	/**
	 * Sets the net tonnage of this document general.
	 *
	 * @param netTonnage the net tonnage of this document general
	 */
	public void setNetTonnage(double netTonnage);

	/**
	 * Returns the position ship in port of this document general.
	 *
	 * @return the position ship in port of this document general
	 */
	public int getPositionShipInPort();

	/**
	 * Sets the position ship in port of this document general.
	 *
	 * @param positionShipInPort the position ship in port of this document general
	 */
	public void setPositionShipInPort(int positionShipInPort);

	/**
	 * Returns the brief particulars voyage of this document general.
	 *
	 * @return the brief particulars voyage of this document general
	 */
	@AutoEscape
	public String getBriefParticularsVoyage();

	/**
	 * Sets the brief particulars voyage of this document general.
	 *
	 * @param briefParticularsVoyage the brief particulars voyage of this document general
	 */
	public void setBriefParticularsVoyage(String briefParticularsVoyage);

	/**
	 * Returns the brief description cargo of this document general.
	 *
	 * @return the brief description cargo of this document general
	 */
	@AutoEscape
	public String getBriefDescriptionCargo();

	/**
	 * Sets the brief description cargo of this document general.
	 *
	 * @param briefDescriptionCargo the brief description cargo of this document general
	 */
	public void setBriefDescriptionCargo(String briefDescriptionCargo);

	/**
	 * Returns the crew number of this document general.
	 *
	 * @return the crew number of this document general
	 */
	public int getCrewNumber();

	/**
	 * Sets the crew number of this document general.
	 *
	 * @param crewNumber the crew number of this document general
	 */
	public void setCrewNumber(int crewNumber);

	/**
	 * Returns the passenger number of this document general.
	 *
	 * @return the passenger number of this document general
	 */
	public int getPassengerNumber();

	/**
	 * Sets the passenger number of this document general.
	 *
	 * @param passengerNumber the passenger number of this document general
	 */
	public void setPassengerNumber(int passengerNumber);

	/**
	 * Returns the remarks of this document general.
	 *
	 * @return the remarks of this document general
	 */
	@AutoEscape
	public String getRemarks();

	/**
	 * Sets the remarks of this document general.
	 *
	 * @param remarks the remarks of this document general
	 */
	public void setRemarks(String remarks);

	/**
	 * Returns the cargo declaration of this document general.
	 *
	 * @return the cargo declaration of this document general
	 */
	@AutoEscape
	public String getCargoDeclaration();

	/**
	 * Sets the cargo declaration of this document general.
	 *
	 * @param cargoDeclaration the cargo declaration of this document general
	 */
	public void setCargoDeclaration(String cargoDeclaration);

	/**
	 * Returns the ship stores declaration of this document general.
	 *
	 * @return the ship stores declaration of this document general
	 */
	@AutoEscape
	public String getShipStoresDeclaration();

	/**
	 * Sets the ship stores declaration of this document general.
	 *
	 * @param shipStoresDeclaration the ship stores declaration of this document general
	 */
	public void setShipStoresDeclaration(String shipStoresDeclaration);

	/**
	 * Returns the crew list of this document general.
	 *
	 * @return the crew list of this document general
	 */
	@AutoEscape
	public String getCrewList();

	/**
	 * Sets the crew list of this document general.
	 *
	 * @param crewList the crew list of this document general
	 */
	public void setCrewList(String crewList);

	/**
	 * Returns the passenger list of this document general.
	 *
	 * @return the passenger list of this document general
	 */
	@AutoEscape
	public String getPassengerList();

	/**
	 * Sets the passenger list of this document general.
	 *
	 * @param passengerList the passenger list of this document general
	 */
	public void setPassengerList(String passengerList);

	/**
	 * Returns the ship requirements of this document general.
	 *
	 * @return the ship requirements of this document general
	 */
	@AutoEscape
	public String getShipRequirements();

	/**
	 * Sets the ship requirements of this document general.
	 *
	 * @param shipRequirements the ship requirements of this document general
	 */
	public void setShipRequirements(String shipRequirements);

	/**
	 * Returns the is crew effect declaration of this document general.
	 *
	 * @return the is crew effect declaration of this document general
	 */
	public int getIsCrewEffectDeclaration();

	/**
	 * Sets the is crew effect declaration of this document general.
	 *
	 * @param isCrewEffectDeclaration the is crew effect declaration of this document general
	 */
	public void setIsCrewEffectDeclaration(int isCrewEffectDeclaration);

	/**
	 * Returns the is maritime declaration health of this document general.
	 *
	 * @return the is maritime declaration health of this document general
	 */
	public int getIsMaritimeDeclarationHealth();

	/**
	 * Sets the is maritime declaration health of this document general.
	 *
	 * @param isMaritimeDeclarationHealth the is maritime declaration health of this document general
	 */
	public void setIsMaritimeDeclarationHealth(int isMaritimeDeclarationHealth);

	/**
	 * Returns the create date of this document general.
	 *
	 * @return the create date of this document general
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this document general.
	 *
	 * @param createDate the create date of this document general
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modify date of this document general.
	 *
	 * @return the modify date of this document general
	 */
	public Date getModifyDate();

	/**
	 * Sets the modify date of this document general.
	 *
	 * @param modifyDate the modify date of this document general
	 */
	public void setModifyDate(Date modifyDate);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(DocumentGeneral documentGeneral);

	public int hashCode();

	public CacheModel<DocumentGeneral> toCacheModel();

	public DocumentGeneral toEscapedModel();

	public String toString();

	public String toXmlString();
}