/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.gt.dao.danhmucgt.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import vn.gt.dao.danhmucgt.model.DmGtOrganization;
import vn.gt.dao.danhmucgt.model.DmGtOrganizationModel;
import vn.gt.dao.danhmucgt.model.DmGtOrganizationSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

/**
 * The base model implementation for the DmGtOrganization service. Represents a row in the &quot;DM_GT_ORGANIZATION&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link vn.gt.dao.danhmucgt.model.DmGtOrganizationModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link DmGtOrganizationImpl}.
 * </p>
 *
 * @author win_64
 * @see DmGtOrganizationImpl
 * @see vn.gt.dao.danhmucgt.model.DmGtOrganization
 * @see vn.gt.dao.danhmucgt.model.DmGtOrganizationModel
 * @generated
 */
@JSON(strict = true)
public class DmGtOrganizationModelImpl extends BaseModelImpl<DmGtOrganization>
	implements DmGtOrganizationModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a dm gt organization model instance should use the {@link vn.gt.dao.danhmucgt.model.DmGtOrganization} interface instead.
	 */
	public static final String TABLE_NAME = "DM_GT_ORGANIZATION";
	public static final Object[][] TABLE_COLUMNS = {
			{ "ID", Types.BIGINT },
			{ "OrganizationCode", Types.VARCHAR },
			{ "OrganizationName", Types.VARCHAR },
			{ "OrganizationNameVN", Types.VARCHAR },
			{ "OrganizationOrder", Types.INTEGER },
			{ "IsDelete", Types.INTEGER },
			{ "MarkedAsDelete", Types.INTEGER },
			{ "ModifiedDate", Types.TIMESTAMP },
			{ "RequestedDate", Types.TIMESTAMP },
			{ "SyncVersion", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table DM_GT_ORGANIZATION (ID LONG not null primary key,OrganizationCode VARCHAR(75) null,OrganizationName VARCHAR(75) null,OrganizationNameVN VARCHAR(75) null,OrganizationOrder INTEGER,IsDelete INTEGER,MarkedAsDelete INTEGER,ModifiedDate DATE null,RequestedDate DATE null,SyncVersion VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table DM_GT_ORGANIZATION";
	public static final String ORDER_BY_JPQL = " ORDER BY dmGtOrganization.id ASC";
	public static final String ORDER_BY_SQL = " ORDER BY DM_GT_ORGANIZATION.ID ASC";
	public static final String DATA_SOURCE = "gtDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.vn.gt.dao.danhmucgt.model.DmGtOrganization"),
			false);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.vn.gt.dao.danhmucgt.model.DmGtOrganization"),
			false);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.vn.gt.dao.danhmucgt.model.DmGtOrganization"),
			true);
	public static long ORGANIZATIONCODE_COLUMN_BITMASK = 1L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static DmGtOrganization toModel(DmGtOrganizationSoap soapModel) {
		DmGtOrganization model = new DmGtOrganizationImpl();

		model.setId(soapModel.getId());
		model.setOrganizationCode(soapModel.getOrganizationCode());
		model.setOrganizationName(soapModel.getOrganizationName());
		model.setOrganizationNameVN(soapModel.getOrganizationNameVN());
		model.setOrganizationorder(soapModel.getOrganizationorder());
		model.setIsDelete(soapModel.getIsDelete());
		model.setMarkedAsDelete(soapModel.getMarkedAsDelete());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setRequestedDate(soapModel.getRequestedDate());
		model.setSyncVersion(soapModel.getSyncVersion());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<DmGtOrganization> toModels(
		DmGtOrganizationSoap[] soapModels) {
		List<DmGtOrganization> models = new ArrayList<DmGtOrganization>(soapModels.length);

		for (DmGtOrganizationSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.vn.gt.dao.danhmucgt.model.DmGtOrganization"));

	public DmGtOrganizationModelImpl() {
	}

	public long getPrimaryKey() {
		return _id;
	}

	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	public Serializable getPrimaryKeyObj() {
		return new Long(_id);
	}

	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	public Class<?> getModelClass() {
		return DmGtOrganization.class;
	}

	public String getModelClassName() {
		return DmGtOrganization.class.getName();
	}

	@JSON
	public long getId() {
		return _id;
	}

	public void setId(long id) {
		_columnBitmask = -1L;

		_id = id;
	}

	@JSON
	public String getOrganizationCode() {
		if (_organizationCode == null) {
			return StringPool.BLANK;
		}
		else {
			return _organizationCode;
		}
	}

	public void setOrganizationCode(String organizationCode) {
		_columnBitmask |= ORGANIZATIONCODE_COLUMN_BITMASK;

		if (_originalOrganizationCode == null) {
			_originalOrganizationCode = _organizationCode;
		}

		_organizationCode = organizationCode;
	}

	public String getOriginalOrganizationCode() {
		return GetterUtil.getString(_originalOrganizationCode);
	}

	@JSON
	public String getOrganizationName() {
		if (_organizationName == null) {
			return StringPool.BLANK;
		}
		else {
			return _organizationName;
		}
	}

	public void setOrganizationName(String organizationName) {
		_organizationName = organizationName;
	}

	@JSON
	public String getOrganizationNameVN() {
		if (_organizationNameVN == null) {
			return StringPool.BLANK;
		}
		else {
			return _organizationNameVN;
		}
	}

	public void setOrganizationNameVN(String organizationNameVN) {
		_organizationNameVN = organizationNameVN;
	}

	@JSON
	public int getOrganizationorder() {
		return _organizationorder;
	}

	public void setOrganizationorder(int organizationorder) {
		_organizationorder = organizationorder;
	}

	@JSON
	public int getIsDelete() {
		return _isDelete;
	}

	public void setIsDelete(int isDelete) {
		_isDelete = isDelete;
	}

	@JSON
	public int getMarkedAsDelete() {
		return _markedAsDelete;
	}

	public void setMarkedAsDelete(int markedAsDelete) {
		_markedAsDelete = markedAsDelete;
	}

	@JSON
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {
		_modifiedDate = modifiedDate;
	}

	@JSON
	public Date getRequestedDate() {
		return _requestedDate;
	}

	public void setRequestedDate(Date requestedDate) {
		_requestedDate = requestedDate;
	}

	@JSON
	public String getSyncVersion() {
		if (_syncVersion == null) {
			return StringPool.BLANK;
		}
		else {
			return _syncVersion;
		}
	}

	public void setSyncVersion(String syncVersion) {
		_syncVersion = syncVersion;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public DmGtOrganization toEscapedModel() {
		if (_escapedModelProxy == null) {
			_escapedModelProxy = (DmGtOrganization)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelProxyInterfaces,
					new AutoEscapeBeanHandler(this));
		}

		return _escapedModelProxy;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		if (_expandoBridge == null) {
			_expandoBridge = ExpandoBridgeFactoryUtil.getExpandoBridge(0,
					DmGtOrganization.class.getName(), getPrimaryKey());
		}

		return _expandoBridge;
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		getExpandoBridge().setAttributes(serviceContext);
	}

	@Override
	public Object clone() {
		DmGtOrganizationImpl dmGtOrganizationImpl = new DmGtOrganizationImpl();

		dmGtOrganizationImpl.setId(getId());
		dmGtOrganizationImpl.setOrganizationCode(getOrganizationCode());
		dmGtOrganizationImpl.setOrganizationName(getOrganizationName());
		dmGtOrganizationImpl.setOrganizationNameVN(getOrganizationNameVN());
		dmGtOrganizationImpl.setOrganizationorder(getOrganizationorder());
		dmGtOrganizationImpl.setIsDelete(getIsDelete());
		dmGtOrganizationImpl.setMarkedAsDelete(getMarkedAsDelete());
		dmGtOrganizationImpl.setModifiedDate(getModifiedDate());
		dmGtOrganizationImpl.setRequestedDate(getRequestedDate());
		dmGtOrganizationImpl.setSyncVersion(getSyncVersion());

		dmGtOrganizationImpl.resetOriginalValues();

		return dmGtOrganizationImpl;
	}

	public int compareTo(DmGtOrganization dmGtOrganization) {
		int value = 0;

		if (getId() < dmGtOrganization.getId()) {
			value = -1;
		}
		else if (getId() > dmGtOrganization.getId()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		DmGtOrganization dmGtOrganization = null;

		try {
			dmGtOrganization = (DmGtOrganization)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		long primaryKey = dmGtOrganization.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		DmGtOrganizationModelImpl dmGtOrganizationModelImpl = this;

		dmGtOrganizationModelImpl._originalOrganizationCode = dmGtOrganizationModelImpl._organizationCode;

		dmGtOrganizationModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<DmGtOrganization> toCacheModel() {
		DmGtOrganizationCacheModel dmGtOrganizationCacheModel = new DmGtOrganizationCacheModel();

		dmGtOrganizationCacheModel.id = getId();

		dmGtOrganizationCacheModel.organizationCode = getOrganizationCode();

		String organizationCode = dmGtOrganizationCacheModel.organizationCode;

		if ((organizationCode != null) && (organizationCode.length() == 0)) {
			dmGtOrganizationCacheModel.organizationCode = null;
		}

		dmGtOrganizationCacheModel.organizationName = getOrganizationName();

		String organizationName = dmGtOrganizationCacheModel.organizationName;

		if ((organizationName != null) && (organizationName.length() == 0)) {
			dmGtOrganizationCacheModel.organizationName = null;
		}

		dmGtOrganizationCacheModel.organizationNameVN = getOrganizationNameVN();

		String organizationNameVN = dmGtOrganizationCacheModel.organizationNameVN;

		if ((organizationNameVN != null) && (organizationNameVN.length() == 0)) {
			dmGtOrganizationCacheModel.organizationNameVN = null;
		}

		dmGtOrganizationCacheModel.organizationorder = getOrganizationorder();

		dmGtOrganizationCacheModel.isDelete = getIsDelete();

		dmGtOrganizationCacheModel.markedAsDelete = getMarkedAsDelete();

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			dmGtOrganizationCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			dmGtOrganizationCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		Date requestedDate = getRequestedDate();

		if (requestedDate != null) {
			dmGtOrganizationCacheModel.requestedDate = requestedDate.getTime();
		}
		else {
			dmGtOrganizationCacheModel.requestedDate = Long.MIN_VALUE;
		}

		dmGtOrganizationCacheModel.syncVersion = getSyncVersion();

		String syncVersion = dmGtOrganizationCacheModel.syncVersion;

		if ((syncVersion != null) && (syncVersion.length() == 0)) {
			dmGtOrganizationCacheModel.syncVersion = null;
		}

		return dmGtOrganizationCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(21);

		sb.append("{id=");
		sb.append(getId());
		sb.append(", organizationCode=");
		sb.append(getOrganizationCode());
		sb.append(", organizationName=");
		sb.append(getOrganizationName());
		sb.append(", organizationNameVN=");
		sb.append(getOrganizationNameVN());
		sb.append(", organizationorder=");
		sb.append(getOrganizationorder());
		sb.append(", isDelete=");
		sb.append(getIsDelete());
		sb.append(", markedAsDelete=");
		sb.append(getMarkedAsDelete());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", requestedDate=");
		sb.append(getRequestedDate());
		sb.append(", syncVersion=");
		sb.append(getSyncVersion());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(34);

		sb.append("<model><model-name>");
		sb.append("vn.gt.dao.danhmucgt.model.DmGtOrganization");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>id</column-name><column-value><![CDATA[");
		sb.append(getId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>organizationCode</column-name><column-value><![CDATA[");
		sb.append(getOrganizationCode());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>organizationName</column-name><column-value><![CDATA[");
		sb.append(getOrganizationName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>organizationNameVN</column-name><column-value><![CDATA[");
		sb.append(getOrganizationNameVN());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>organizationorder</column-name><column-value><![CDATA[");
		sb.append(getOrganizationorder());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>isDelete</column-name><column-value><![CDATA[");
		sb.append(getIsDelete());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>markedAsDelete</column-name><column-value><![CDATA[");
		sb.append(getMarkedAsDelete());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>requestedDate</column-name><column-value><![CDATA[");
		sb.append(getRequestedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>syncVersion</column-name><column-value><![CDATA[");
		sb.append(getSyncVersion());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = DmGtOrganization.class.getClassLoader();
	private static Class<?>[] _escapedModelProxyInterfaces = new Class[] {
			DmGtOrganization.class
		};
	private long _id;
	private String _organizationCode;
	private String _originalOrganizationCode;
	private String _organizationName;
	private String _organizationNameVN;
	private int _organizationorder;
	private int _isDelete;
	private int _markedAsDelete;
	private Date _modifiedDate;
	private Date _requestedDate;
	private String _syncVersion;
	private transient ExpandoBridge _expandoBridge;
	private long _columnBitmask;
	private DmGtOrganization _escapedModelProxy;
}