/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.gt.dao.noticeandmessage.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the IssueShiftingOrder service. Represents a row in the &quot;ISSUE_SHIFTING_ORDER&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link vn.gt.dao.noticeandmessage.model.impl.IssueShiftingOrderModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link vn.gt.dao.noticeandmessage.model.impl.IssueShiftingOrderImpl}.
 * </p>
 *
 * @author win_64
 * @see IssueShiftingOrder
 * @see vn.gt.dao.noticeandmessage.model.impl.IssueShiftingOrderImpl
 * @see vn.gt.dao.noticeandmessage.model.impl.IssueShiftingOrderModelImpl
 * @generated
 */
public interface IssueShiftingOrderModel extends BaseModel<IssueShiftingOrder> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a issue shifting order model instance should use the {@link IssueShiftingOrder} interface instead.
	 */

	/**
	 * Returns the primary key of this issue shifting order.
	 *
	 * @return the primary key of this issue shifting order
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this issue shifting order.
	 *
	 * @param primaryKey the primary key of this issue shifting order
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this issue shifting order.
	 *
	 * @return the ID of this issue shifting order
	 */
	public long getId();

	/**
	 * Sets the ID of this issue shifting order.
	 *
	 * @param id the ID of this issue shifting order
	 */
	public void setId(long id);

	/**
	 * Returns the request code of this issue shifting order.
	 *
	 * @return the request code of this issue shifting order
	 */
	@AutoEscape
	public String getRequestCode();

	/**
	 * Sets the request code of this issue shifting order.
	 *
	 * @param requestCode the request code of this issue shifting order
	 */
	public void setRequestCode(String requestCode);

	/**
	 * Returns the number shifting order of this issue shifting order.
	 *
	 * @return the number shifting order of this issue shifting order
	 */
	@AutoEscape
	public String getNumberShiftingOrder();

	/**
	 * Sets the number shifting order of this issue shifting order.
	 *
	 * @param numberShiftingOrder the number shifting order of this issue shifting order
	 */
	public void setNumberShiftingOrder(String numberShiftingOrder);

	/**
	 * Returns the document name of this issue shifting order.
	 *
	 * @return the document name of this issue shifting order
	 */
	public long getDocumentName();

	/**
	 * Sets the document name of this issue shifting order.
	 *
	 * @param documentName the document name of this issue shifting order
	 */
	public void setDocumentName(long documentName);

	/**
	 * Returns the document year of this issue shifting order.
	 *
	 * @return the document year of this issue shifting order
	 */
	public int getDocumentYear();

	/**
	 * Sets the document year of this issue shifting order.
	 *
	 * @param documentYear the document year of this issue shifting order
	 */
	public void setDocumentYear(int documentYear);

	/**
	 * Returns the portof authority of this issue shifting order.
	 *
	 * @return the portof authority of this issue shifting order
	 */
	@AutoEscape
	public String getPortofAuthority();

	/**
	 * Sets the portof authority of this issue shifting order.
	 *
	 * @param portofAuthority the portof authority of this issue shifting order
	 */
	public void setPortofAuthority(String portofAuthority);

	/**
	 * Returns the name of ship of this issue shifting order.
	 *
	 * @return the name of ship of this issue shifting order
	 */
	@AutoEscape
	public String getNameOfShip();

	/**
	 * Sets the name of ship of this issue shifting order.
	 *
	 * @param nameOfShip the name of ship of this issue shifting order
	 */
	public void setNameOfShip(String nameOfShip);

	/**
	 * Returns the flag state of ship of this issue shifting order.
	 *
	 * @return the flag state of ship of this issue shifting order
	 */
	@AutoEscape
	public String getFlagStateOfShip();

	/**
	 * Sets the flag state of ship of this issue shifting order.
	 *
	 * @param flagStateOfShip the flag state of ship of this issue shifting order
	 */
	public void setFlagStateOfShip(String flagStateOfShip);

	/**
	 * Returns the anchoring port code of this issue shifting order.
	 *
	 * @return the anchoring port code of this issue shifting order
	 */
	@AutoEscape
	public String getAnchoringPortCode();

	/**
	 * Sets the anchoring port code of this issue shifting order.
	 *
	 * @param anchoringPortCode the anchoring port code of this issue shifting order
	 */
	public void setAnchoringPortCode(String anchoringPortCode);

	/**
	 * Returns the anchoring port wharf code of this issue shifting order.
	 *
	 * @return the anchoring port wharf code of this issue shifting order
	 */
	@AutoEscape
	public String getAnchoringPortWharfCode();

	/**
	 * Sets the anchoring port wharf code of this issue shifting order.
	 *
	 * @param anchoringPortWharfCode the anchoring port wharf code of this issue shifting order
	 */
	public void setAnchoringPortWharfCode(String anchoringPortWharfCode);

	/**
	 * Returns the port harbour code of this issue shifting order.
	 *
	 * @return the port harbour code of this issue shifting order
	 */
	@AutoEscape
	public String getPortHarbourCode();

	/**
	 * Sets the port harbour code of this issue shifting order.
	 *
	 * @param portHarbourCode the port harbour code of this issue shifting order
	 */
	public void setPortHarbourCode(String portHarbourCode);

	/**
	 * Returns the shifting port wharf code of this issue shifting order.
	 *
	 * @return the shifting port wharf code of this issue shifting order
	 */
	@AutoEscape
	public String getShiftingPortWharfCode();

	/**
	 * Sets the shifting port wharf code of this issue shifting order.
	 *
	 * @param shiftingPortWharfCode the shifting port wharf code of this issue shifting order
	 */
	public void setShiftingPortWharfCode(String shiftingPortWharfCode);

	/**
	 * Returns the shifting date of this issue shifting order.
	 *
	 * @return the shifting date of this issue shifting order
	 */
	public Date getShiftingDate();

	/**
	 * Sets the shifting date of this issue shifting order.
	 *
	 * @param shiftingDate the shifting date of this issue shifting order
	 */
	public void setShiftingDate(Date shiftingDate);

	/**
	 * Returns the reason to shift of this issue shifting order.
	 *
	 * @return the reason to shift of this issue shifting order
	 */
	@AutoEscape
	public String getReasonToShift();

	/**
	 * Sets the reason to shift of this issue shifting order.
	 *
	 * @param reasonToShift the reason to shift of this issue shifting order
	 */
	public void setReasonToShift(String reasonToShift);

	/**
	 * Returns the issue date of this issue shifting order.
	 *
	 * @return the issue date of this issue shifting order
	 */
	public Date getIssueDate();

	/**
	 * Sets the issue date of this issue shifting order.
	 *
	 * @param issueDate the issue date of this issue shifting order
	 */
	public void setIssueDate(Date issueDate);

	/**
	 * Returns the director of maritime of this issue shifting order.
	 *
	 * @return the director of maritime of this issue shifting order
	 */
	@AutoEscape
	public String getDirectorOfMaritime();

	/**
	 * Sets the director of maritime of this issue shifting order.
	 *
	 * @param directorOfMaritime the director of maritime of this issue shifting order
	 */
	public void setDirectorOfMaritime(String directorOfMaritime);

	/**
	 * Returns the certificate no of this issue shifting order.
	 *
	 * @return the certificate no of this issue shifting order
	 */
	@AutoEscape
	public String getCertificateNo();

	/**
	 * Sets the certificate no of this issue shifting order.
	 *
	 * @param certificateNo the certificate no of this issue shifting order
	 */
	public void setCertificateNo(String certificateNo);

	/**
	 * Returns the request state of this issue shifting order.
	 *
	 * @return the request state of this issue shifting order
	 */
	public int getRequestState();

	/**
	 * Sets the request state of this issue shifting order.
	 *
	 * @param requestState the request state of this issue shifting order
	 */
	public void setRequestState(int requestState);

	/**
	 * Returns the version no of this issue shifting order.
	 *
	 * @return the version no of this issue shifting order
	 */
	@AutoEscape
	public String getVersionNo();

	/**
	 * Sets the version no of this issue shifting order.
	 *
	 * @param versionNo the version no of this issue shifting order
	 */
	public void setVersionNo(String versionNo);

	/**
	 * Returns the is approval of this issue shifting order.
	 *
	 * @return the is approval of this issue shifting order
	 */
	public int getIsApproval();

	/**
	 * Sets the is approval of this issue shifting order.
	 *
	 * @param isApproval the is approval of this issue shifting order
	 */
	public void setIsApproval(int isApproval);

	/**
	 * Returns the approval date of this issue shifting order.
	 *
	 * @return the approval date of this issue shifting order
	 */
	public Date getApprovalDate();

	/**
	 * Sets the approval date of this issue shifting order.
	 *
	 * @param approvalDate the approval date of this issue shifting order
	 */
	public void setApprovalDate(Date approvalDate);

	/**
	 * Returns the approval name of this issue shifting order.
	 *
	 * @return the approval name of this issue shifting order
	 */
	@AutoEscape
	public String getApprovalName();

	/**
	 * Sets the approval name of this issue shifting order.
	 *
	 * @param approvalName the approval name of this issue shifting order
	 */
	public void setApprovalName(String approvalName);

	/**
	 * Returns the remarks of this issue shifting order.
	 *
	 * @return the remarks of this issue shifting order
	 */
	@AutoEscape
	public String getRemarks();

	/**
	 * Sets the remarks of this issue shifting order.
	 *
	 * @param remarks the remarks of this issue shifting order
	 */
	public void setRemarks(String remarks);

	/**
	 * Returns the is cancel of this issue shifting order.
	 *
	 * @return the is cancel of this issue shifting order
	 */
	public int getIsCancel();

	/**
	 * Sets the is cancel of this issue shifting order.
	 *
	 * @param isCancel the is cancel of this issue shifting order
	 */
	public void setIsCancel(int isCancel);

	/**
	 * Returns the cancel date of this issue shifting order.
	 *
	 * @return the cancel date of this issue shifting order
	 */
	public Date getCancelDate();

	/**
	 * Sets the cancel date of this issue shifting order.
	 *
	 * @param cancelDate the cancel date of this issue shifting order
	 */
	public void setCancelDate(Date cancelDate);

	/**
	 * Returns the cancel name of this issue shifting order.
	 *
	 * @return the cancel name of this issue shifting order
	 */
	@AutoEscape
	public String getCancelName();

	/**
	 * Sets the cancel name of this issue shifting order.
	 *
	 * @param cancelName the cancel name of this issue shifting order
	 */
	public void setCancelName(String cancelName);

	/**
	 * Returns the cancel note of this issue shifting order.
	 *
	 * @return the cancel note of this issue shifting order
	 */
	@AutoEscape
	public String getCancelNote();

	/**
	 * Sets the cancel note of this issue shifting order.
	 *
	 * @param cancelNote the cancel note of this issue shifting order
	 */
	public void setCancelNote(String cancelNote);

	/**
	 * Returns the representative of this issue shifting order.
	 *
	 * @return the representative of this issue shifting order
	 */
	@AutoEscape
	public String getRepresentative();

	/**
	 * Sets the representative of this issue shifting order.
	 *
	 * @param representative the representative of this issue shifting order
	 */
	public void setRepresentative(String representative);

	/**
	 * Returns the digital attached file of this issue shifting order.
	 *
	 * @return the digital attached file of this issue shifting order
	 */
	public long getDigitalAttachedFile();

	/**
	 * Sets the digital attached file of this issue shifting order.
	 *
	 * @param digitalAttachedFile the digital attached file of this issue shifting order
	 */
	public void setDigitalAttachedFile(long digitalAttachedFile);

	/**
	 * Returns the sign date of this issue shifting order.
	 *
	 * @return the sign date of this issue shifting order
	 */
	public Date getSignDate();

	/**
	 * Sets the sign date of this issue shifting order.
	 *
	 * @param signDate the sign date of this issue shifting order
	 */
	public void setSignDate(Date signDate);

	/**
	 * Returns the sign name of this issue shifting order.
	 *
	 * @return the sign name of this issue shifting order
	 */
	@AutoEscape
	public String getSignName();

	/**
	 * Sets the sign name of this issue shifting order.
	 *
	 * @param signName the sign name of this issue shifting order
	 */
	public void setSignName(String signName);

	/**
	 * Returns the sign title of this issue shifting order.
	 *
	 * @return the sign title of this issue shifting order
	 */
	@AutoEscape
	public String getSignTitle();

	/**
	 * Sets the sign title of this issue shifting order.
	 *
	 * @param signTitle the sign title of this issue shifting order
	 */
	public void setSignTitle(String signTitle);

	/**
	 * Returns the sign place of this issue shifting order.
	 *
	 * @return the sign place of this issue shifting order
	 */
	@AutoEscape
	public String getSignPlace();

	/**
	 * Sets the sign place of this issue shifting order.
	 *
	 * @param signPlace the sign place of this issue shifting order
	 */
	public void setSignPlace(String signPlace);

	/**
	 * Returns the stamp status of this issue shifting order.
	 *
	 * @return the stamp status of this issue shifting order
	 */
	public int getStampStatus();

	/**
	 * Sets the stamp status of this issue shifting order.
	 *
	 * @param stampStatus the stamp status of this issue shifting order
	 */
	public void setStampStatus(int stampStatus);

	/**
	 * Returns the attached file of this issue shifting order.
	 *
	 * @return the attached file of this issue shifting order
	 */
	public long getAttachedFile();

	/**
	 * Sets the attached file of this issue shifting order.
	 *
	 * @param attachedFile the attached file of this issue shifting order
	 */
	public void setAttachedFile(long attachedFile);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(IssueShiftingOrder issueShiftingOrder);

	public int hashCode();

	public CacheModel<IssueShiftingOrder> toCacheModel();

	public IssueShiftingOrder toEscapedModel();

	public String toString();

	public String toXmlString();
}