/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.gt.dao.noticeandmessage.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Modify service. Represents a row in the &quot;gt_modify&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link vn.gt.dao.noticeandmessage.model.impl.ModifyModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link vn.gt.dao.noticeandmessage.model.impl.ModifyImpl}.
 * </p>
 *
 * @author win_64
 * @see Modify
 * @see vn.gt.dao.noticeandmessage.model.impl.ModifyImpl
 * @see vn.gt.dao.noticeandmessage.model.impl.ModifyModelImpl
 * @generated
 */
public interface ModifyModel extends BaseModel<Modify> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a modify model instance should use the {@link Modify} interface instead.
	 */

	/**
	 * Returns the primary key of this modify.
	 *
	 * @return the primary key of this modify
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this modify.
	 *
	 * @param primaryKey the primary key of this modify
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this modify.
	 *
	 * @return the ID of this modify
	 */
	public long getId();

	/**
	 * Sets the ID of this modify.
	 *
	 * @param id the ID of this modify
	 */
	public void setId(long id);

	/**
	 * Returns the modify code of this modify.
	 *
	 * @return the modify code of this modify
	 */
	@AutoEscape
	public String getModifyCode();

	/**
	 * Sets the modify code of this modify.
	 *
	 * @param modifyCode the modify code of this modify
	 */
	public void setModifyCode(String modifyCode);

	/**
	 * Returns the modify desc of this modify.
	 *
	 * @return the modify desc of this modify
	 */
	@AutoEscape
	public String getModifyDesc();

	/**
	 * Sets the modify desc of this modify.
	 *
	 * @param modifyDesc the modify desc of this modify
	 */
	public void setModifyDesc(String modifyDesc);

	/**
	 * Returns the organization of this modify.
	 *
	 * @return the organization of this modify
	 */
	@AutoEscape
	public String getOrganization();

	/**
	 * Sets the organization of this modify.
	 *
	 * @param organization the organization of this modify
	 */
	public void setOrganization(String organization);

	/**
	 * Returns the division of this modify.
	 *
	 * @return the division of this modify
	 */
	@AutoEscape
	public String getDivision();

	/**
	 * Sets the division of this modify.
	 *
	 * @param division the division of this modify
	 */
	public void setDivision(String division);

	/**
	 * Returns the name of this modify.
	 *
	 * @return the name of this modify
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this modify.
	 *
	 * @param name the name of this modify
	 */
	public void setName(String name);

	/**
	 * Returns the modify date of this modify.
	 *
	 * @return the modify date of this modify
	 */
	public Date getModifyDate();

	/**
	 * Sets the modify date of this modify.
	 *
	 * @param modifyDate the modify date of this modify
	 */
	public void setModifyDate(Date modifyDate);

	/**
	 * Returns the document name of this modify.
	 *
	 * @return the document name of this modify
	 */
	public long getDocumentName();

	/**
	 * Sets the document name of this modify.
	 *
	 * @param documentName the document name of this modify
	 */
	public void setDocumentName(long documentName);

	/**
	 * Returns the document year of this modify.
	 *
	 * @return the document year of this modify
	 */
	public long getDocumentYear();

	/**
	 * Sets the document year of this modify.
	 *
	 * @param documentYear the document year of this modify
	 */
	public void setDocumentYear(long documentYear);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(Modify modify);

	public int hashCode();

	public CacheModel<Modify> toCacheModel();

	public Modify toEscapedModel();

	public String toString();

	public String toXmlString();
}