/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.gt.dao.noticeandmessage.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the TempDangerousGoodsItems service. Represents a row in the &quot;TEMP_DANGEROUS_GOODS_ITEMS&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link vn.gt.dao.noticeandmessage.model.impl.TempDangerousGoodsItemsModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link vn.gt.dao.noticeandmessage.model.impl.TempDangerousGoodsItemsImpl}.
 * </p>
 *
 * @author win_64
 * @see TempDangerousGoodsItems
 * @see vn.gt.dao.noticeandmessage.model.impl.TempDangerousGoodsItemsImpl
 * @see vn.gt.dao.noticeandmessage.model.impl.TempDangerousGoodsItemsModelImpl
 * @generated
 */
public interface TempDangerousGoodsItemsModel extends BaseModel<TempDangerousGoodsItems> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a temp dangerous goods items model instance should use the {@link TempDangerousGoodsItems} interface instead.
	 */

	/**
	 * Returns the primary key of this temp dangerous goods items.
	 *
	 * @return the primary key of this temp dangerous goods items
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this temp dangerous goods items.
	 *
	 * @param primaryKey the primary key of this temp dangerous goods items
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this temp dangerous goods items.
	 *
	 * @return the ID of this temp dangerous goods items
	 */
	public long getId();

	/**
	 * Sets the ID of this temp dangerous goods items.
	 *
	 * @param id the ID of this temp dangerous goods items
	 */
	public void setId(long id);

	/**
	 * Returns the request code of this temp dangerous goods items.
	 *
	 * @return the request code of this temp dangerous goods items
	 */
	@AutoEscape
	public String getRequestCode();

	/**
	 * Sets the request code of this temp dangerous goods items.
	 *
	 * @param requestCode the request code of this temp dangerous goods items
	 */
	public void setRequestCode(String requestCode);

	/**
	 * Returns the dangerous good item code of this temp dangerous goods items.
	 *
	 * @return the dangerous good item code of this temp dangerous goods items
	 */
	@AutoEscape
	public String getDangerousGoodItemCode();

	/**
	 * Sets the dangerous good item code of this temp dangerous goods items.
	 *
	 * @param dangerousGoodItemCode the dangerous good item code of this temp dangerous goods items
	 */
	public void setDangerousGoodItemCode(String dangerousGoodItemCode);

	/**
	 * Returns the ref number of this temp dangerous goods items.
	 *
	 * @return the ref number of this temp dangerous goods items
	 */
	@AutoEscape
	public String getRefNumber();

	/**
	 * Sets the ref number of this temp dangerous goods items.
	 *
	 * @param refNumber the ref number of this temp dangerous goods items
	 */
	public void setRefNumber(String refNumber);

	/**
	 * Returns the marks container of this temp dangerous goods items.
	 *
	 * @return the marks container of this temp dangerous goods items
	 */
	@AutoEscape
	public String getMarksContainer();

	/**
	 * Sets the marks container of this temp dangerous goods items.
	 *
	 * @param marksContainer the marks container of this temp dangerous goods items
	 */
	public void setMarksContainer(String marksContainer);

	/**
	 * Returns the number container of this temp dangerous goods items.
	 *
	 * @return the number container of this temp dangerous goods items
	 */
	@AutoEscape
	public String getNumberContainer();

	/**
	 * Sets the number container of this temp dangerous goods items.
	 *
	 * @param numberContainer the number container of this temp dangerous goods items
	 */
	public void setNumberContainer(String numberContainer);

	/**
	 * Returns the number of package of this temp dangerous goods items.
	 *
	 * @return the number of package of this temp dangerous goods items
	 */
	@AutoEscape
	public String getNumberOfPackage();

	/**
	 * Sets the number of package of this temp dangerous goods items.
	 *
	 * @param numberOfPackage the number of package of this temp dangerous goods items
	 */
	public void setNumberOfPackage(String numberOfPackage);

	/**
	 * Returns the kind of packages of this temp dangerous goods items.
	 *
	 * @return the kind of packages of this temp dangerous goods items
	 */
	@AutoEscape
	public String getKindOfPackages();

	/**
	 * Sets the kind of packages of this temp dangerous goods items.
	 *
	 * @param kindOfPackages the kind of packages of this temp dangerous goods items
	 */
	public void setKindOfPackages(String kindOfPackages);

	/**
	 * Returns the proper shipping name of this temp dangerous goods items.
	 *
	 * @return the proper shipping name of this temp dangerous goods items
	 */
	@AutoEscape
	public String getProperShippingName();

	/**
	 * Sets the proper shipping name of this temp dangerous goods items.
	 *
	 * @param properShippingName the proper shipping name of this temp dangerous goods items
	 */
	public void setProperShippingName(String properShippingName);

	/**
	 * Returns the good class of this temp dangerous goods items.
	 *
	 * @return the good class of this temp dangerous goods items
	 */
	@AutoEscape
	public String getGoodClass();

	/**
	 * Sets the good class of this temp dangerous goods items.
	 *
	 * @param goodClass the good class of this temp dangerous goods items
	 */
	public void setGoodClass(String goodClass);

	/**
	 * Returns the un number of this temp dangerous goods items.
	 *
	 * @return the un number of this temp dangerous goods items
	 */
	@AutoEscape
	public String getUnNumber();

	/**
	 * Sets the un number of this temp dangerous goods items.
	 *
	 * @param unNumber the un number of this temp dangerous goods items
	 */
	public void setUnNumber(String unNumber);

	/**
	 * Returns the packing group of this temp dangerous goods items.
	 *
	 * @return the packing group of this temp dangerous goods items
	 */
	@AutoEscape
	public String getPackingGroup();

	/**
	 * Sets the packing group of this temp dangerous goods items.
	 *
	 * @param packingGroup the packing group of this temp dangerous goods items
	 */
	public void setPackingGroup(String packingGroup);

	/**
	 * Returns the subsidiary risk of this temp dangerous goods items.
	 *
	 * @return the subsidiary risk of this temp dangerous goods items
	 */
	@AutoEscape
	public String getSubsidiaryRisk();

	/**
	 * Sets the subsidiary risk of this temp dangerous goods items.
	 *
	 * @param subsidiaryRisk the subsidiary risk of this temp dangerous goods items
	 */
	public void setSubsidiaryRisk(String subsidiaryRisk);

	/**
	 * Returns the flash point of this temp dangerous goods items.
	 *
	 * @return the flash point of this temp dangerous goods items
	 */
	@AutoEscape
	public String getFlashPoint();

	/**
	 * Sets the flash point of this temp dangerous goods items.
	 *
	 * @param flashPoint the flash point of this temp dangerous goods items
	 */
	public void setFlashPoint(String flashPoint);

	/**
	 * Returns the marine pollutant of this temp dangerous goods items.
	 *
	 * @return the marine pollutant of this temp dangerous goods items
	 */
	@AutoEscape
	public String getMarinePollutant();

	/**
	 * Sets the marine pollutant of this temp dangerous goods items.
	 *
	 * @param marinePollutant the marine pollutant of this temp dangerous goods items
	 */
	public void setMarinePollutant(String marinePollutant);

	/**
	 * Returns the gross weight of this temp dangerous goods items.
	 *
	 * @return the gross weight of this temp dangerous goods items
	 */
	public long getGrossWeight();

	/**
	 * Sets the gross weight of this temp dangerous goods items.
	 *
	 * @param grossWeight the gross weight of this temp dangerous goods items
	 */
	public void setGrossWeight(long grossWeight);

	/**
	 * Returns the ems of this temp dangerous goods items.
	 *
	 * @return the ems of this temp dangerous goods items
	 */
	@AutoEscape
	public String getEms();

	/**
	 * Sets the ems of this temp dangerous goods items.
	 *
	 * @param ems the ems of this temp dangerous goods items
	 */
	public void setEms(String ems);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(TempDangerousGoodsItems tempDangerousGoodsItems);

	public int hashCode();

	public CacheModel<TempDangerousGoodsItems> toCacheModel();

	public TempDangerousGoodsItems toEscapedModel();

	public String toString();

	public String toXmlString();
}