/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.gt.dao.noticeandmessage.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the TempPassengerDetails service. Represents a row in the &quot;TEMP_PASSENGER_DETAILS&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link vn.gt.dao.noticeandmessage.model.impl.TempPassengerDetailsModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link vn.gt.dao.noticeandmessage.model.impl.TempPassengerDetailsImpl}.
 * </p>
 *
 * @author win_64
 * @see TempPassengerDetails
 * @see vn.gt.dao.noticeandmessage.model.impl.TempPassengerDetailsImpl
 * @see vn.gt.dao.noticeandmessage.model.impl.TempPassengerDetailsModelImpl
 * @generated
 */
public interface TempPassengerDetailsModel extends BaseModel<TempPassengerDetails> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a temp passenger details model instance should use the {@link TempPassengerDetails} interface instead.
	 */

	/**
	 * Returns the primary key of this temp passenger details.
	 *
	 * @return the primary key of this temp passenger details
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this temp passenger details.
	 *
	 * @param primaryKey the primary key of this temp passenger details
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this temp passenger details.
	 *
	 * @return the ID of this temp passenger details
	 */
	public long getId();

	/**
	 * Sets the ID of this temp passenger details.
	 *
	 * @param id the ID of this temp passenger details
	 */
	public void setId(long id);

	/**
	 * Returns the request code of this temp passenger details.
	 *
	 * @return the request code of this temp passenger details
	 */
	@AutoEscape
	public String getRequestCode();

	/**
	 * Sets the request code of this temp passenger details.
	 *
	 * @param requestCode the request code of this temp passenger details
	 */
	public void setRequestCode(String requestCode);

	/**
	 * Returns the passenger code of this temp passenger details.
	 *
	 * @return the passenger code of this temp passenger details
	 */
	@AutoEscape
	public String getPassengerCode();

	/**
	 * Sets the passenger code of this temp passenger details.
	 *
	 * @param passengerCode the passenger code of this temp passenger details
	 */
	public void setPassengerCode(String passengerCode);

	/**
	 * Returns the family name of this temp passenger details.
	 *
	 * @return the family name of this temp passenger details
	 */
	@AutoEscape
	public String getFamilyName();

	/**
	 * Sets the family name of this temp passenger details.
	 *
	 * @param familyName the family name of this temp passenger details
	 */
	public void setFamilyName(String familyName);

	/**
	 * Returns the given name of this temp passenger details.
	 *
	 * @return the given name of this temp passenger details
	 */
	@AutoEscape
	public String getGivenName();

	/**
	 * Sets the given name of this temp passenger details.
	 *
	 * @param givenName the given name of this temp passenger details
	 */
	public void setGivenName(String givenName);

	/**
	 * Returns the nationality of this temp passenger details.
	 *
	 * @return the nationality of this temp passenger details
	 */
	@AutoEscape
	public String getNationality();

	/**
	 * Sets the nationality of this temp passenger details.
	 *
	 * @param nationality the nationality of this temp passenger details
	 */
	public void setNationality(String nationality);

	/**
	 * Returns the birth day of this temp passenger details.
	 *
	 * @return the birth day of this temp passenger details
	 */
	public Date getBirthDay();

	/**
	 * Sets the birth day of this temp passenger details.
	 *
	 * @param birthDay the birth day of this temp passenger details
	 */
	public void setBirthDay(Date birthDay);

	/**
	 * Returns the birth place of this temp passenger details.
	 *
	 * @return the birth place of this temp passenger details
	 */
	@AutoEscape
	public String getBirthPlace();

	/**
	 * Sets the birth place of this temp passenger details.
	 *
	 * @param birthPlace the birth place of this temp passenger details
	 */
	public void setBirthPlace(String birthPlace);

	/**
	 * Returns the type of identity of this temp passenger details.
	 *
	 * @return the type of identity of this temp passenger details
	 */
	@AutoEscape
	public String getTypeOfIdentity();

	/**
	 * Sets the type of identity of this temp passenger details.
	 *
	 * @param typeOfIdentity the type of identity of this temp passenger details
	 */
	public void setTypeOfIdentity(String typeOfIdentity);

	/**
	 * Returns the passport expired date of this temp passenger details.
	 *
	 * @return the passport expired date of this temp passenger details
	 */
	public Date getPassportExpiredDate();

	/**
	 * Sets the passport expired date of this temp passenger details.
	 *
	 * @param passportExpiredDate the passport expired date of this temp passenger details
	 */
	public void setPassportExpiredDate(Date passportExpiredDate);

	/**
	 * Returns the serial number of identity of this temp passenger details.
	 *
	 * @return the serial number of identity of this temp passenger details
	 */
	@AutoEscape
	public String getSerialNumberOfIdentity();

	/**
	 * Sets the serial number of identity of this temp passenger details.
	 *
	 * @param serialNumberOfIdentity the serial number of identity of this temp passenger details
	 */
	public void setSerialNumberOfIdentity(String serialNumberOfIdentity);

	/**
	 * Returns the port of embarkation of this temp passenger details.
	 *
	 * @return the port of embarkation of this temp passenger details
	 */
	@AutoEscape
	public String getPortOfEmbarkation();

	/**
	 * Sets the port of embarkation of this temp passenger details.
	 *
	 * @param portOfEmbarkation the port of embarkation of this temp passenger details
	 */
	public void setPortOfEmbarkation(String portOfEmbarkation);

	/**
	 * Returns the port of disembarkation of this temp passenger details.
	 *
	 * @return the port of disembarkation of this temp passenger details
	 */
	@AutoEscape
	public String getPortOfDisembarkation();

	/**
	 * Sets the port of disembarkation of this temp passenger details.
	 *
	 * @param portOfDisembarkation the port of disembarkation of this temp passenger details
	 */
	public void setPortOfDisembarkation(String portOfDisembarkation);

	/**
	 * Returns the is transit of this temp passenger details.
	 *
	 * @return the is transit of this temp passenger details
	 */
	public int getIsTransit();

	/**
	 * Sets the is transit of this temp passenger details.
	 *
	 * @param isTransit the is transit of this temp passenger details
	 */
	public void setIsTransit(int isTransit);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(TempPassengerDetails tempPassengerDetails);

	public int hashCode();

	public CacheModel<TempPassengerDetails> toCacheModel();

	public TempPassengerDetails toEscapedModel();

	public String toString();

	public String toXmlString();
}