/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.gt.dao.noticeandmessage.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the TempCrewDetails service. Represents a row in the &quot;TEMP_CREW_DETAILS&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link vn.gt.dao.noticeandmessage.model.impl.TempCrewDetailsModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link vn.gt.dao.noticeandmessage.model.impl.TempCrewDetailsImpl}.
 * </p>
 *
 * @author win_64
 * @see TempCrewDetails
 * @see vn.gt.dao.noticeandmessage.model.impl.TempCrewDetailsImpl
 * @see vn.gt.dao.noticeandmessage.model.impl.TempCrewDetailsModelImpl
 * @generated
 */
public interface TempCrewDetailsModel extends BaseModel<TempCrewDetails> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a temp crew details model instance should use the {@link TempCrewDetails} interface instead.
	 */

	/**
	 * Returns the primary key of this temp crew details.
	 *
	 * @return the primary key of this temp crew details
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this temp crew details.
	 *
	 * @param primaryKey the primary key of this temp crew details
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this temp crew details.
	 *
	 * @return the ID of this temp crew details
	 */
	public long getId();

	/**
	 * Sets the ID of this temp crew details.
	 *
	 * @param id the ID of this temp crew details
	 */
	public void setId(long id);

	/**
	 * Returns the request code of this temp crew details.
	 *
	 * @return the request code of this temp crew details
	 */
	@AutoEscape
	public String getRequestCode();

	/**
	 * Sets the request code of this temp crew details.
	 *
	 * @param requestCode the request code of this temp crew details
	 */
	public void setRequestCode(String requestCode);

	/**
	 * Returns the crewcode of this temp crew details.
	 *
	 * @return the crewcode of this temp crew details
	 */
	@AutoEscape
	public String getCrewcode();

	/**
	 * Sets the crewcode of this temp crew details.
	 *
	 * @param crewcode the crewcode of this temp crew details
	 */
	public void setCrewcode(String crewcode);

	/**
	 * Returns the family name of this temp crew details.
	 *
	 * @return the family name of this temp crew details
	 */
	@AutoEscape
	public String getFamilyName();

	/**
	 * Sets the family name of this temp crew details.
	 *
	 * @param familyName the family name of this temp crew details
	 */
	public void setFamilyName(String familyName);

	/**
	 * Returns the given name of this temp crew details.
	 *
	 * @return the given name of this temp crew details
	 */
	@AutoEscape
	public String getGivenName();

	/**
	 * Sets the given name of this temp crew details.
	 *
	 * @param givenName the given name of this temp crew details
	 */
	public void setGivenName(String givenName);

	/**
	 * Returns the rank code of this temp crew details.
	 *
	 * @return the rank code of this temp crew details
	 */
	@AutoEscape
	public String getRankCode();

	/**
	 * Sets the rank code of this temp crew details.
	 *
	 * @param rankCode the rank code of this temp crew details
	 */
	public void setRankCode(String rankCode);

	/**
	 * Returns the nationality of this temp crew details.
	 *
	 * @return the nationality of this temp crew details
	 */
	@AutoEscape
	public String getNationality();

	/**
	 * Sets the nationality of this temp crew details.
	 *
	 * @param nationality the nationality of this temp crew details
	 */
	public void setNationality(String nationality);

	/**
	 * Returns the date of birth of this temp crew details.
	 *
	 * @return the date of birth of this temp crew details
	 */
	public Date getDateOfBirth();

	/**
	 * Sets the date of birth of this temp crew details.
	 *
	 * @param dateOfBirth the date of birth of this temp crew details
	 */
	public void setDateOfBirth(Date dateOfBirth);

	/**
	 * Returns the place of birth of this temp crew details.
	 *
	 * @return the place of birth of this temp crew details
	 */
	@AutoEscape
	public String getPlaceOfBirth();

	/**
	 * Sets the place of birth of this temp crew details.
	 *
	 * @param placeOfBirth the place of birth of this temp crew details
	 */
	public void setPlaceOfBirth(String placeOfBirth);

	/**
	 * Returns the passport number of this temp crew details.
	 *
	 * @return the passport number of this temp crew details
	 */
	@AutoEscape
	public String getPassportNumber();

	/**
	 * Sets the passport number of this temp crew details.
	 *
	 * @param passportNumber the passport number of this temp crew details
	 */
	public void setPassportNumber(String passportNumber);

	/**
	 * Returns the passport type code of this temp crew details.
	 *
	 * @return the passport type code of this temp crew details
	 */
	@AutoEscape
	public String getPassportTypeCode();

	/**
	 * Sets the passport type code of this temp crew details.
	 *
	 * @param passportTypeCode the passport type code of this temp crew details
	 */
	public void setPassportTypeCode(String passportTypeCode);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(TempCrewDetails tempCrewDetails);

	public int hashCode();

	public CacheModel<TempCrewDetails> toCacheModel();

	public TempCrewDetails toEscapedModel();

	public String toString();

	public String toXmlString();
}