/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.gt.dao.noticeandmessage.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the TempDeclarationOfHealth service. Represents a row in the &quot;TEMP_DECLARATION_OF_HEALTH&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link vn.gt.dao.noticeandmessage.model.impl.TempDeclarationOfHealthModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link vn.gt.dao.noticeandmessage.model.impl.TempDeclarationOfHealthImpl}.
 * </p>
 *
 * @author win_64
 * @see TempDeclarationOfHealth
 * @see vn.gt.dao.noticeandmessage.model.impl.TempDeclarationOfHealthImpl
 * @see vn.gt.dao.noticeandmessage.model.impl.TempDeclarationOfHealthModelImpl
 * @generated
 */
public interface TempDeclarationOfHealthModel extends BaseModel<TempDeclarationOfHealth> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a temp declaration of health model instance should use the {@link TempDeclarationOfHealth} interface instead.
	 */

	/**
	 * Returns the primary key of this temp declaration of health.
	 *
	 * @return the primary key of this temp declaration of health
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this temp declaration of health.
	 *
	 * @param primaryKey the primary key of this temp declaration of health
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this temp declaration of health.
	 *
	 * @return the ID of this temp declaration of health
	 */
	public long getId();

	/**
	 * Sets the ID of this temp declaration of health.
	 *
	 * @param id the ID of this temp declaration of health
	 */
	public void setId(long id);

	/**
	 * Returns the request code of this temp declaration of health.
	 *
	 * @return the request code of this temp declaration of health
	 */
	@AutoEscape
	public String getRequestCode();

	/**
	 * Sets the request code of this temp declaration of health.
	 *
	 * @param requestCode the request code of this temp declaration of health
	 */
	public void setRequestCode(String requestCode);

	/**
	 * Returns the request state of this temp declaration of health.
	 *
	 * @return the request state of this temp declaration of health
	 */
	public int getRequestState();

	/**
	 * Sets the request state of this temp declaration of health.
	 *
	 * @param requestState the request state of this temp declaration of health
	 */
	public void setRequestState(int requestState);

	/**
	 * Returns the document name of this temp declaration of health.
	 *
	 * @return the document name of this temp declaration of health
	 */
	public long getDocumentName();

	/**
	 * Sets the document name of this temp declaration of health.
	 *
	 * @param documentName the document name of this temp declaration of health
	 */
	public void setDocumentName(long documentName);

	/**
	 * Returns the document year of this temp declaration of health.
	 *
	 * @return the document year of this temp declaration of health
	 */
	public int getDocumentYear();

	/**
	 * Sets the document year of this temp declaration of health.
	 *
	 * @param documentYear the document year of this temp declaration of health
	 */
	public void setDocumentYear(int documentYear);

	/**
	 * Returns the user created of this temp declaration of health.
	 *
	 * @return the user created of this temp declaration of health
	 */
	@AutoEscape
	public String getUserCreated();

	/**
	 * Sets the user created of this temp declaration of health.
	 *
	 * @param userCreated the user created of this temp declaration of health
	 */
	public void setUserCreated(String userCreated);

	/**
	 * Returns the submitted port code of this temp declaration of health.
	 *
	 * @return the submitted port code of this temp declaration of health
	 */
	@AutoEscape
	public String getSubmittedPortCode();

	/**
	 * Sets the submitted port code of this temp declaration of health.
	 *
	 * @param submittedPortCode the submitted port code of this temp declaration of health
	 */
	public void setSubmittedPortCode(String submittedPortCode);

	/**
	 * Returns the date submitted of this temp declaration of health.
	 *
	 * @return the date submitted of this temp declaration of health
	 */
	public Date getDateSubmitted();

	/**
	 * Sets the date submitted of this temp declaration of health.
	 *
	 * @param dateSubmitted the date submitted of this temp declaration of health
	 */
	public void setDateSubmitted(Date dateSubmitted);

	/**
	 * Returns the name of ship of this temp declaration of health.
	 *
	 * @return the name of ship of this temp declaration of health
	 */
	@AutoEscape
	public String getNameOfShip();

	/**
	 * Sets the name of ship of this temp declaration of health.
	 *
	 * @param nameOfShip the name of ship of this temp declaration of health
	 */
	public void setNameOfShip(String nameOfShip);

	/**
	 * Returns the registration of this temp declaration of health.
	 *
	 * @return the registration of this temp declaration of health
	 */
	@AutoEscape
	public String getRegistration();

	/**
	 * Sets the registration of this temp declaration of health.
	 *
	 * @param registration the registration of this temp declaration of health
	 */
	public void setRegistration(String registration);

	/**
	 * Returns the imo number of this temp declaration of health.
	 *
	 * @return the imo number of this temp declaration of health
	 */
	@AutoEscape
	public String getImoNumber();

	/**
	 * Sets the imo number of this temp declaration of health.
	 *
	 * @param imoNumber the imo number of this temp declaration of health
	 */
	public void setImoNumber(String imoNumber);

	/**
	 * Returns the arriving from of this temp declaration of health.
	 *
	 * @return the arriving from of this temp declaration of health
	 */
	@AutoEscape
	public String getArrivingFrom();

	/**
	 * Sets the arriving from of this temp declaration of health.
	 *
	 * @param arrivingFrom the arriving from of this temp declaration of health
	 */
	public void setArrivingFrom(String arrivingFrom);

	/**
	 * Returns the sailing to of this temp declaration of health.
	 *
	 * @return the sailing to of this temp declaration of health
	 */
	@AutoEscape
	public String getSailingTo();

	/**
	 * Sets the sailing to of this temp declaration of health.
	 *
	 * @param sailingTo the sailing to of this temp declaration of health
	 */
	public void setSailingTo(String sailingTo);

	/**
	 * Returns the nationality of this temp declaration of health.
	 *
	 * @return the nationality of this temp declaration of health
	 */
	@AutoEscape
	public String getNationality();

	/**
	 * Sets the nationality of this temp declaration of health.
	 *
	 * @param nationality the nationality of this temp declaration of health
	 */
	public void setNationality(String nationality);

	/**
	 * Returns the master name of this temp declaration of health.
	 *
	 * @return the master name of this temp declaration of health
	 */
	@AutoEscape
	public String getMasterName();

	/**
	 * Sets the master name of this temp declaration of health.
	 *
	 * @param masterName the master name of this temp declaration of health
	 */
	public void setMasterName(String masterName);

	/**
	 * Returns the gross tonnage of this temp declaration of health.
	 *
	 * @return the gross tonnage of this temp declaration of health
	 */
	public double getGrossTonnage();

	/**
	 * Sets the gross tonnage of this temp declaration of health.
	 *
	 * @param grossTonnage the gross tonnage of this temp declaration of health
	 */
	public void setGrossTonnage(double grossTonnage);

	/**
	 * Returns the gross tonnage unit of this temp declaration of health.
	 *
	 * @return the gross tonnage unit of this temp declaration of health
	 */
	@AutoEscape
	public String getGrossTonnageUnit();

	/**
	 * Sets the gross tonnage unit of this temp declaration of health.
	 *
	 * @param grossTonnageUnit the gross tonnage unit of this temp declaration of health
	 */
	public void setGrossTonnageUnit(String grossTonnageUnit);

	/**
	 * Returns the tonnage of this temp declaration of health.
	 *
	 * @return the tonnage of this temp declaration of health
	 */
	public double getTonnage();

	/**
	 * Sets the tonnage of this temp declaration of health.
	 *
	 * @param tonnage the tonnage of this temp declaration of health
	 */
	public void setTonnage(double tonnage);

	/**
	 * Returns the tonnage unit of this temp declaration of health.
	 *
	 * @return the tonnage unit of this temp declaration of health
	 */
	@AutoEscape
	public String getTonnageUnit();

	/**
	 * Sets the tonnage unit of this temp declaration of health.
	 *
	 * @param tonnageUnit the tonnage unit of this temp declaration of health
	 */
	public void setTonnageUnit(String tonnageUnit);

	/**
	 * Returns the certificatecarried of this temp declaration of health.
	 *
	 * @return the certificatecarried of this temp declaration of health
	 */
	public int getCertificatecarried();

	/**
	 * Sets the certificatecarried of this temp declaration of health.
	 *
	 * @param certificatecarried the certificatecarried of this temp declaration of health
	 */
	public void setCertificatecarried(int certificatecarried);

	/**
	 * Returns the issued at of this temp declaration of health.
	 *
	 * @return the issued at of this temp declaration of health
	 */
	@AutoEscape
	public String getIssuedAt();

	/**
	 * Sets the issued at of this temp declaration of health.
	 *
	 * @param issuedAt the issued at of this temp declaration of health
	 */
	public void setIssuedAt(String issuedAt);

	/**
	 * Returns the issue date of this temp declaration of health.
	 *
	 * @return the issue date of this temp declaration of health
	 */
	public Date getIssueDate();

	/**
	 * Sets the issue date of this temp declaration of health.
	 *
	 * @param issueDate the issue date of this temp declaration of health
	 */
	public void setIssueDate(Date issueDate);

	/**
	 * Returns the re inspectionrequired of this temp declaration of health.
	 *
	 * @return the re inspectionrequired of this temp declaration of health
	 */
	public int getReInspectionrequired();

	/**
	 * Sets the re inspectionrequired of this temp declaration of health.
	 *
	 * @param reInspectionrequired the re inspectionrequired of this temp declaration of health
	 */
	public void setReInspectionrequired(int reInspectionrequired);

	/**
	 * Returns the is ship visited w h o of this temp declaration of health.
	 *
	 * @return the is ship visited w h o of this temp declaration of health
	 */
	public int getIsShipVisitedWHO();

	/**
	 * Sets the is ship visited w h o of this temp declaration of health.
	 *
	 * @param isShipVisitedWHO the is ship visited w h o of this temp declaration of health
	 */
	public void setIsShipVisitedWHO(int isShipVisitedWHO);

	/**
	 * Returns the visited w h o port code of this temp declaration of health.
	 *
	 * @return the visited w h o port code of this temp declaration of health
	 */
	@AutoEscape
	public String getVisitedWHOPortCode();

	/**
	 * Sets the visited w h o port code of this temp declaration of health.
	 *
	 * @param visitedWHOPortCode the visited w h o port code of this temp declaration of health
	 */
	public void setVisitedWHOPortCode(String visitedWHOPortCode);

	/**
	 * Returns the date of visited w h o of this temp declaration of health.
	 *
	 * @return the date of visited w h o of this temp declaration of health
	 */
	public Date getDateOfVisitedWHO();

	/**
	 * Sets the date of visited w h o of this temp declaration of health.
	 *
	 * @param dateOfVisitedWHO the date of visited w h o of this temp declaration of health
	 */
	public void setDateOfVisitedWHO(Date dateOfVisitedWHO);

	/**
	 * Returns the list port name of this temp declaration of health.
	 *
	 * @return the list port name of this temp declaration of health
	 */
	@AutoEscape
	public String getListPortName();

	/**
	 * Sets the list port name of this temp declaration of health.
	 *
	 * @param listPortName the list port name of this temp declaration of health
	 */
	public void setListPortName(String listPortName);

	/**
	 * Returns the doctor name of this temp declaration of health.
	 *
	 * @return the doctor name of this temp declaration of health
	 */
	@AutoEscape
	public String getDoctorName();

	/**
	 * Sets the doctor name of this temp declaration of health.
	 *
	 * @param doctorName the doctor name of this temp declaration of health
	 */
	public void setDoctorName(String doctorName);

	/**
	 * Returns the doctor signdate of this temp declaration of health.
	 *
	 * @return the doctor signdate of this temp declaration of health
	 */
	public Date getDoctorSigndate();

	/**
	 * Sets the doctor signdate of this temp declaration of health.
	 *
	 * @param doctorSigndate the doctor signdate of this temp declaration of health
	 */
	public void setDoctorSigndate(Date doctorSigndate);

	/**
	 * Returns the sign place of this temp declaration of health.
	 *
	 * @return the sign place of this temp declaration of health
	 */
	@AutoEscape
	public String getSignPlace();

	/**
	 * Sets the sign place of this temp declaration of health.
	 *
	 * @param signPlace the sign place of this temp declaration of health
	 */
	public void setSignPlace(String signPlace);

	/**
	 * Returns the sign date of this temp declaration of health.
	 *
	 * @return the sign date of this temp declaration of health
	 */
	public Date getSignDate();

	/**
	 * Sets the sign date of this temp declaration of health.
	 *
	 * @param signDate the sign date of this temp declaration of health
	 */
	public void setSignDate(Date signDate);

	/**
	 * Returns the master signed of this temp declaration of health.
	 *
	 * @return the master signed of this temp declaration of health
	 */
	public int getMasterSigned();

	/**
	 * Sets the master signed of this temp declaration of health.
	 *
	 * @param masterSigned the master signed of this temp declaration of health
	 */
	public void setMasterSigned(int masterSigned);

	/**
	 * Returns the master signed image of this temp declaration of health.
	 *
	 * @return the master signed image of this temp declaration of health
	 */
	public int getMasterSignedImage();

	/**
	 * Sets the master signed image of this temp declaration of health.
	 *
	 * @param masterSignedImage the master signed image of this temp declaration of health
	 */
	public void setMasterSignedImage(int masterSignedImage);

	/**
	 * Returns the attached file of this temp declaration of health.
	 *
	 * @return the attached file of this temp declaration of health
	 */
	public long getAttachedFile();

	/**
	 * Sets the attached file of this temp declaration of health.
	 *
	 * @param attachedFile the attached file of this temp declaration of health
	 */
	public void setAttachedFile(long attachedFile);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(TempDeclarationOfHealth tempDeclarationOfHealth);

	public int hashCode();

	public CacheModel<TempDeclarationOfHealth> toCacheModel();

	public TempDeclarationOfHealth toEscapedModel();

	public String toString();

	public String toXmlString();
}