/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.gt.dao.noticeandmessage.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the TempGoodsItems service. Represents a row in the &quot;TEMP_GOODS_ITEMS&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link vn.gt.dao.noticeandmessage.model.impl.TempGoodsItemsModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link vn.gt.dao.noticeandmessage.model.impl.TempGoodsItemsImpl}.
 * </p>
 *
 * @author win_64
 * @see TempGoodsItems
 * @see vn.gt.dao.noticeandmessage.model.impl.TempGoodsItemsImpl
 * @see vn.gt.dao.noticeandmessage.model.impl.TempGoodsItemsModelImpl
 * @generated
 */
public interface TempGoodsItemsModel extends BaseModel<TempGoodsItems> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a temp goods items model instance should use the {@link TempGoodsItems} interface instead.
	 */

	/**
	 * Returns the primary key of this temp goods items.
	 *
	 * @return the primary key of this temp goods items
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this temp goods items.
	 *
	 * @param primaryKey the primary key of this temp goods items
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this temp goods items.
	 *
	 * @return the ID of this temp goods items
	 */
	public long getId();

	/**
	 * Sets the ID of this temp goods items.
	 *
	 * @param id the ID of this temp goods items
	 */
	public void setId(long id);

	/**
	 * Returns the request code of this temp goods items.
	 *
	 * @return the request code of this temp goods items
	 */
	@AutoEscape
	public String getRequestCode();

	/**
	 * Sets the request code of this temp goods items.
	 *
	 * @param requestCode the request code of this temp goods items
	 */
	public void setRequestCode(String requestCode);

	/**
	 * Returns the bill of lading no of this temp goods items.
	 *
	 * @return the bill of lading no of this temp goods items
	 */
	@AutoEscape
	public String getBillOfLadingNo();

	/**
	 * Sets the bill of lading no of this temp goods items.
	 *
	 * @param billOfLadingNo the bill of lading no of this temp goods items
	 */
	public void setBillOfLadingNo(String billOfLadingNo);

	/**
	 * Returns the good item code of this temp goods items.
	 *
	 * @return the good item code of this temp goods items
	 */
	@AutoEscape
	public String getGoodItemCode();

	/**
	 * Sets the good item code of this temp goods items.
	 *
	 * @param goodItemCode the good item code of this temp goods items
	 */
	public void setGoodItemCode(String goodItemCode);

	/**
	 * Returns the good item description of this temp goods items.
	 *
	 * @return the good item description of this temp goods items
	 */
	@AutoEscape
	public String getGoodItemDescription();

	/**
	 * Sets the good item description of this temp goods items.
	 *
	 * @param goodItemDescription the good item description of this temp goods items
	 */
	public void setGoodItemDescription(String goodItemDescription);

	/**
	 * Returns the number of package of this temp goods items.
	 *
	 * @return the number of package of this temp goods items
	 */
	public long getNumberOfPackage();

	/**
	 * Sets the number of package of this temp goods items.
	 *
	 * @param numberOfPackage the number of package of this temp goods items
	 */
	public void setNumberOfPackage(long numberOfPackage);

	/**
	 * Returns the kind of packages of this temp goods items.
	 *
	 * @return the kind of packages of this temp goods items
	 */
	@AutoEscape
	public String getKindOfPackages();

	/**
	 * Sets the kind of packages of this temp goods items.
	 *
	 * @param kindOfPackages the kind of packages of this temp goods items
	 */
	public void setKindOfPackages(String kindOfPackages);

	/**
	 * Returns the marksand nosof goods of this temp goods items.
	 *
	 * @return the marksand nosof goods of this temp goods items
	 */
	@AutoEscape
	public String getMarksandNosofGoods();

	/**
	 * Sets the marksand nosof goods of this temp goods items.
	 *
	 * @param marksandNosofGoods the marksand nosof goods of this temp goods items
	 */
	public void setMarksandNosofGoods(String marksandNosofGoods);

	/**
	 * Returns the gross weight of this temp goods items.
	 *
	 * @return the gross weight of this temp goods items
	 */
	public double getGrossWeight();

	/**
	 * Sets the gross weight of this temp goods items.
	 *
	 * @param grossWeight the gross weight of this temp goods items
	 */
	public void setGrossWeight(double grossWeight);

	/**
	 * Returns the gross weight unit of this temp goods items.
	 *
	 * @return the gross weight unit of this temp goods items
	 */
	@AutoEscape
	public String getGrossWeightUnit();

	/**
	 * Sets the gross weight unit of this temp goods items.
	 *
	 * @param grossWeightUnit the gross weight unit of this temp goods items
	 */
	public void setGrossWeightUnit(String grossWeightUnit);

	/**
	 * Returns the measurement of this temp goods items.
	 *
	 * @return the measurement of this temp goods items
	 */
	public double getMeasurement();

	/**
	 * Sets the measurement of this temp goods items.
	 *
	 * @param measurement the measurement of this temp goods items
	 */
	public void setMeasurement(double measurement);

	/**
	 * Returns the measurement unit of this temp goods items.
	 *
	 * @return the measurement unit of this temp goods items
	 */
	@AutoEscape
	public String getMeasurementUnit();

	/**
	 * Sets the measurement unit of this temp goods items.
	 *
	 * @param measurementUnit the measurement unit of this temp goods items
	 */
	public void setMeasurementUnit(String measurementUnit);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(TempGoodsItems tempGoodsItems);

	public int hashCode();

	public CacheModel<TempGoodsItems> toCacheModel();

	public TempGoodsItems toEscapedModel();

	public String toString();

	public String toXmlString();
}