/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.gt.dao.noticeandmessage.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the TempCrewEffectsDeclaration service. Represents a row in the &quot;TEMP_CREW_EFFECTS_DECLARATION&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link vn.gt.dao.noticeandmessage.model.impl.TempCrewEffectsDeclarationModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link vn.gt.dao.noticeandmessage.model.impl.TempCrewEffectsDeclarationImpl}.
 * </p>
 *
 * @author win_64
 * @see TempCrewEffectsDeclaration
 * @see vn.gt.dao.noticeandmessage.model.impl.TempCrewEffectsDeclarationImpl
 * @see vn.gt.dao.noticeandmessage.model.impl.TempCrewEffectsDeclarationModelImpl
 * @generated
 */
public interface TempCrewEffectsDeclarationModel extends BaseModel<TempCrewEffectsDeclaration> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a temp crew effects declaration model instance should use the {@link TempCrewEffectsDeclaration} interface instead.
	 */

	/**
	 * Returns the primary key of this temp crew effects declaration.
	 *
	 * @return the primary key of this temp crew effects declaration
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this temp crew effects declaration.
	 *
	 * @param primaryKey the primary key of this temp crew effects declaration
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this temp crew effects declaration.
	 *
	 * @return the ID of this temp crew effects declaration
	 */
	public long getId();

	/**
	 * Sets the ID of this temp crew effects declaration.
	 *
	 * @param id the ID of this temp crew effects declaration
	 */
	public void setId(long id);

	/**
	 * Returns the request code of this temp crew effects declaration.
	 *
	 * @return the request code of this temp crew effects declaration
	 */
	@AutoEscape
	public String getRequestCode();

	/**
	 * Sets the request code of this temp crew effects declaration.
	 *
	 * @param requestCode the request code of this temp crew effects declaration
	 */
	public void setRequestCode(String requestCode);

	/**
	 * Returns the request state of this temp crew effects declaration.
	 *
	 * @return the request state of this temp crew effects declaration
	 */
	public int getRequestState();

	/**
	 * Sets the request state of this temp crew effects declaration.
	 *
	 * @param requestState the request state of this temp crew effects declaration
	 */
	public void setRequestState(int requestState);

	/**
	 * Returns the document name of this temp crew effects declaration.
	 *
	 * @return the document name of this temp crew effects declaration
	 */
	public long getDocumentName();

	/**
	 * Sets the document name of this temp crew effects declaration.
	 *
	 * @param documentName the document name of this temp crew effects declaration
	 */
	public void setDocumentName(long documentName);

	/**
	 * Returns the user created of this temp crew effects declaration.
	 *
	 * @return the user created of this temp crew effects declaration
	 */
	@AutoEscape
	public String getUserCreated();

	/**
	 * Sets the user created of this temp crew effects declaration.
	 *
	 * @param userCreated the user created of this temp crew effects declaration
	 */
	public void setUserCreated(String userCreated);

	/**
	 * Returns the name of ship of this temp crew effects declaration.
	 *
	 * @return the name of ship of this temp crew effects declaration
	 */
	@AutoEscape
	public String getNameOfShip();

	/**
	 * Sets the name of ship of this temp crew effects declaration.
	 *
	 * @param nameOfShip the name of ship of this temp crew effects declaration
	 */
	public void setNameOfShip(String nameOfShip);

	/**
	 * Returns the imo number of this temp crew effects declaration.
	 *
	 * @return the imo number of this temp crew effects declaration
	 */
	@AutoEscape
	public String getImoNumber();

	/**
	 * Sets the imo number of this temp crew effects declaration.
	 *
	 * @param imoNumber the imo number of this temp crew effects declaration
	 */
	public void setImoNumber(String imoNumber);

	/**
	 * Returns the callsign of this temp crew effects declaration.
	 *
	 * @return the callsign of this temp crew effects declaration
	 */
	@AutoEscape
	public String getCallsign();

	/**
	 * Sets the callsign of this temp crew effects declaration.
	 *
	 * @param callsign the callsign of this temp crew effects declaration
	 */
	public void setCallsign(String callsign);

	/**
	 * Returns the voyage number of this temp crew effects declaration.
	 *
	 * @return the voyage number of this temp crew effects declaration
	 */
	@AutoEscape
	public String getVoyageNumber();

	/**
	 * Sets the voyage number of this temp crew effects declaration.
	 *
	 * @param voyageNumber the voyage number of this temp crew effects declaration
	 */
	public void setVoyageNumber(String voyageNumber);

	/**
	 * Returns the flag state of ship of this temp crew effects declaration.
	 *
	 * @return the flag state of ship of this temp crew effects declaration
	 */
	@AutoEscape
	public String getFlagStateOfShip();

	/**
	 * Sets the flag state of ship of this temp crew effects declaration.
	 *
	 * @param flagStateOfShip the flag state of ship of this temp crew effects declaration
	 */
	public void setFlagStateOfShip(String flagStateOfShip);

	/**
	 * Returns the name of master of this temp crew effects declaration.
	 *
	 * @return the name of master of this temp crew effects declaration
	 */
	@AutoEscape
	public String getNameOfMaster();

	/**
	 * Sets the name of master of this temp crew effects declaration.
	 *
	 * @param nameOfMaster the name of master of this temp crew effects declaration
	 */
	public void setNameOfMaster(String nameOfMaster);

	/**
	 * Returns the list crew effects of this temp crew effects declaration.
	 *
	 * @return the list crew effects of this temp crew effects declaration
	 */
	public int getListCrewEffects();

	/**
	 * Sets the list crew effects of this temp crew effects declaration.
	 *
	 * @param listCrewEffects the list crew effects of this temp crew effects declaration
	 */
	public void setListCrewEffects(int listCrewEffects);

	/**
	 * Returns the sign place of this temp crew effects declaration.
	 *
	 * @return the sign place of this temp crew effects declaration
	 */
	@AutoEscape
	public String getSignPlace();

	/**
	 * Sets the sign place of this temp crew effects declaration.
	 *
	 * @param signPlace the sign place of this temp crew effects declaration
	 */
	public void setSignPlace(String signPlace);

	/**
	 * Returns the sign date of this temp crew effects declaration.
	 *
	 * @return the sign date of this temp crew effects declaration
	 */
	public Date getSignDate();

	/**
	 * Sets the sign date of this temp crew effects declaration.
	 *
	 * @param signDate the sign date of this temp crew effects declaration
	 */
	public void setSignDate(Date signDate);

	/**
	 * Returns the master signed of this temp crew effects declaration.
	 *
	 * @return the master signed of this temp crew effects declaration
	 */
	public int getMasterSigned();

	/**
	 * Sets the master signed of this temp crew effects declaration.
	 *
	 * @param masterSigned the master signed of this temp crew effects declaration
	 */
	public void setMasterSigned(int masterSigned);

	/**
	 * Returns the master signed image of this temp crew effects declaration.
	 *
	 * @return the master signed image of this temp crew effects declaration
	 */
	public int getMasterSignedImage();

	/**
	 * Sets the master signed image of this temp crew effects declaration.
	 *
	 * @param masterSignedImage the master signed image of this temp crew effects declaration
	 */
	public void setMasterSignedImage(int masterSignedImage);

	/**
	 * Returns the attached file of this temp crew effects declaration.
	 *
	 * @return the attached file of this temp crew effects declaration
	 */
	public long getAttachedFile();

	/**
	 * Sets the attached file of this temp crew effects declaration.
	 *
	 * @param attachedFile the attached file of this temp crew effects declaration
	 */
	public void setAttachedFile(long attachedFile);

	/**
	 * Returns the document year of this temp crew effects declaration.
	 *
	 * @return the document year of this temp crew effects declaration
	 */
	public int getDocumentYear();

	/**
	 * Sets the document year of this temp crew effects declaration.
	 *
	 * @param documentYear the document year of this temp crew effects declaration
	 */
	public void setDocumentYear(int documentYear);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(TempCrewEffectsDeclaration tempCrewEffectsDeclaration);

	public int hashCode();

	public CacheModel<TempCrewEffectsDeclaration> toCacheModel();

	public TempCrewEffectsDeclaration toEscapedModel();

	public String toString();

	public String toXmlString();
}