/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.gt.dao.noticeandmessage.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the TempShipSecurityMessage service. Represents a row in the &quot;TEMP_SHIP_SECURITY_MESSAGE&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link vn.gt.dao.noticeandmessage.model.impl.TempShipSecurityMessageModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link vn.gt.dao.noticeandmessage.model.impl.TempShipSecurityMessageImpl}.
 * </p>
 *
 * @author win_64
 * @see TempShipSecurityMessage
 * @see vn.gt.dao.noticeandmessage.model.impl.TempShipSecurityMessageImpl
 * @see vn.gt.dao.noticeandmessage.model.impl.TempShipSecurityMessageModelImpl
 * @generated
 */
public interface TempShipSecurityMessageModel extends BaseModel<TempShipSecurityMessage> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a temp ship security message model instance should use the {@link TempShipSecurityMessage} interface instead.
	 */

	/**
	 * Returns the primary key of this temp ship security message.
	 *
	 * @return the primary key of this temp ship security message
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this temp ship security message.
	 *
	 * @param primaryKey the primary key of this temp ship security message
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this temp ship security message.
	 *
	 * @return the ID of this temp ship security message
	 */
	public long getId();

	/**
	 * Sets the ID of this temp ship security message.
	 *
	 * @param id the ID of this temp ship security message
	 */
	public void setId(long id);

	/**
	 * Returns the request code of this temp ship security message.
	 *
	 * @return the request code of this temp ship security message
	 */
	@AutoEscape
	public String getRequestCode();

	/**
	 * Sets the request code of this temp ship security message.
	 *
	 * @param requestCode the request code of this temp ship security message
	 */
	public void setRequestCode(String requestCode);

	/**
	 * Returns the request state of this temp ship security message.
	 *
	 * @return the request state of this temp ship security message
	 */
	public int getRequestState();

	/**
	 * Sets the request state of this temp ship security message.
	 *
	 * @param requestState the request state of this temp ship security message
	 */
	public void setRequestState(int requestState);

	/**
	 * Returns the document year of this temp ship security message.
	 *
	 * @return the document year of this temp ship security message
	 */
	public int getDocumentYear();

	/**
	 * Sets the document year of this temp ship security message.
	 *
	 * @param documentYear the document year of this temp ship security message
	 */
	public void setDocumentYear(int documentYear);

	/**
	 * Returns the ship security code of this temp ship security message.
	 *
	 * @return the ship security code of this temp ship security message
	 */
	@AutoEscape
	public String getShipSecurityCode();

	/**
	 * Sets the ship security code of this temp ship security message.
	 *
	 * @param shipSecurityCode the ship security code of this temp ship security message
	 */
	public void setShipSecurityCode(String shipSecurityCode);

	/**
	 * Returns the document name of this temp ship security message.
	 *
	 * @return the document name of this temp ship security message
	 */
	public long getDocumentName();

	/**
	 * Sets the document name of this temp ship security message.
	 *
	 * @param documentName the document name of this temp ship security message
	 */
	public void setDocumentName(long documentName);

	/**
	 * Returns the user created of this temp ship security message.
	 *
	 * @return the user created of this temp ship security message
	 */
	@AutoEscape
	public String getUserCreated();

	/**
	 * Sets the user created of this temp ship security message.
	 *
	 * @param userCreated the user created of this temp ship security message
	 */
	public void setUserCreated(String userCreated);

	/**
	 * Returns the ship agency code of this temp ship security message.
	 *
	 * @return the ship agency code of this temp ship security message
	 */
	@AutoEscape
	public String getShipAgencyCode();

	/**
	 * Sets the ship agency code of this temp ship security message.
	 *
	 * @param shipAgencyCode the ship agency code of this temp ship security message
	 */
	public void setShipAgencyCode(String shipAgencyCode);

	/**
	 * Returns the name of ship agent of this temp ship security message.
	 *
	 * @return the name of ship agent of this temp ship security message
	 */
	@AutoEscape
	public String getNameOfShipAgent();

	/**
	 * Sets the name of ship agent of this temp ship security message.
	 *
	 * @param nameOfShipAgent the name of ship agent of this temp ship security message
	 */
	public void setNameOfShipAgent(String nameOfShipAgent);

	/**
	 * Returns the ship name of this temp ship security message.
	 *
	 * @return the ship name of this temp ship security message
	 */
	@AutoEscape
	public String getShipName();

	/**
	 * Sets the ship name of this temp ship security message.
	 *
	 * @param shipName the ship name of this temp ship security message
	 */
	public void setShipName(String shipName);

	/**
	 * Returns the ship type code of this temp ship security message.
	 *
	 * @return the ship type code of this temp ship security message
	 */
	@AutoEscape
	public String getShipTypeCode();

	/**
	 * Sets the ship type code of this temp ship security message.
	 *
	 * @param shipTypeCode the ship type code of this temp ship security message
	 */
	public void setShipTypeCode(String shipTypeCode);

	/**
	 * Returns the state code of this temp ship security message.
	 *
	 * @return the state code of this temp ship security message
	 */
	@AutoEscape
	public String getStateCode();

	/**
	 * Sets the state code of this temp ship security message.
	 *
	 * @param stateCode the state code of this temp ship security message
	 */
	public void setStateCode(String stateCode);

	/**
	 * Returns the ship captain of this temp ship security message.
	 *
	 * @return the ship captain of this temp ship security message
	 */
	@AutoEscape
	public String getShipCaptain();

	/**
	 * Sets the ship captain of this temp ship security message.
	 *
	 * @param shipCaptain the ship captain of this temp ship security message
	 */
	public void setShipCaptain(String shipCaptain);

	/**
	 * Returns the imo of this temp ship security message.
	 *
	 * @return the imo of this temp ship security message
	 */
	@AutoEscape
	public String getImo();

	/**
	 * Sets the imo of this temp ship security message.
	 *
	 * @param imo the imo of this temp ship security message
	 */
	public void setImo(String imo);

	/**
	 * Returns the grt of this temp ship security message.
	 *
	 * @return the grt of this temp ship security message
	 */
	public double getGrt();

	/**
	 * Sets the grt of this temp ship security message.
	 *
	 * @param grt the grt of this temp ship security message
	 */
	public void setGrt(double grt);

	/**
	 * Returns the unit g r t of this temp ship security message.
	 *
	 * @return the unit g r t of this temp ship security message
	 */
	@AutoEscape
	public String getUnitGRT();

	/**
	 * Sets the unit g r t of this temp ship security message.
	 *
	 * @param unitGRT the unit g r t of this temp ship security message
	 */
	public void setUnitGRT(String unitGRT);

	/**
	 * Returns the crew number of this temp ship security message.
	 *
	 * @return the crew number of this temp ship security message
	 */
	public long getCrewNumber();

	/**
	 * Sets the crew number of this temp ship security message.
	 *
	 * @param crewNumber the crew number of this temp ship security message
	 */
	public void setCrewNumber(long crewNumber);

	/**
	 * Returns the arrival date of this temp ship security message.
	 *
	 * @return the arrival date of this temp ship security message
	 */
	public Date getArrivalDate();

	/**
	 * Sets the arrival date of this temp ship security message.
	 *
	 * @param arrivalDate the arrival date of this temp ship security message
	 */
	public void setArrivalDate(Date arrivalDate);

	/**
	 * Returns the purpose code of this temp ship security message.
	 *
	 * @return the purpose code of this temp ship security message
	 */
	@AutoEscape
	public String getPurposeCode();

	/**
	 * Sets the purpose code of this temp ship security message.
	 *
	 * @param purposeCode the purpose code of this temp ship security message
	 */
	public void setPurposeCode(String purposeCode);

	/**
	 * Returns the purpose specified of this temp ship security message.
	 *
	 * @return the purpose specified of this temp ship security message
	 */
	@AutoEscape
	public String getPurposeSpecified();

	/**
	 * Sets the purpose specified of this temp ship security message.
	 *
	 * @param purposeSpecified the purpose specified of this temp ship security message
	 */
	public void setPurposeSpecified(String purposeSpecified);

	/**
	 * Returns the port region code of this temp ship security message.
	 *
	 * @return the port region code of this temp ship security message
	 */
	@AutoEscape
	public String getPortRegionCode();

	/**
	 * Sets the port region code of this temp ship security message.
	 *
	 * @param portRegionCode the port region code of this temp ship security message
	 */
	public void setPortRegionCode(String portRegionCode);

	/**
	 * Returns the port wharf code of this temp ship security message.
	 *
	 * @return the port wharf code of this temp ship security message
	 */
	@AutoEscape
	public String getPortWharfCode();

	/**
	 * Sets the port wharf code of this temp ship security message.
	 *
	 * @param portWharfCode the port wharf code of this temp ship security message
	 */
	public void setPortWharfCode(String portWharfCode);

	/**
	 * Returns the ship agency phone of this temp ship security message.
	 *
	 * @return the ship agency phone of this temp ship security message
	 */
	@AutoEscape
	public String getShipAgencyPhone();

	/**
	 * Sets the ship agency phone of this temp ship security message.
	 *
	 * @param shipAgencyPhone the ship agency phone of this temp ship security message
	 */
	public void setShipAgencyPhone(String shipAgencyPhone);

	/**
	 * Returns the ship agency fax of this temp ship security message.
	 *
	 * @return the ship agency fax of this temp ship security message
	 */
	@AutoEscape
	public String getShipAgencyFax();

	/**
	 * Sets the ship agency fax of this temp ship security message.
	 *
	 * @param shipAgencyFax the ship agency fax of this temp ship security message
	 */
	public void setShipAgencyFax(String shipAgencyFax);

	/**
	 * Returns the is international ship security of this temp ship security message.
	 *
	 * @return the is international ship security of this temp ship security message
	 */
	public int getIsInternationalShipSecurity();

	/**
	 * Sets the is international ship security of this temp ship security message.
	 *
	 * @param isInternationalShipSecurity the is international ship security of this temp ship security message
	 */
	public void setIsInternationalShipSecurity(int isInternationalShipSecurity);

	/**
	 * Returns the name of i s s c of this temp ship security message.
	 *
	 * @return the name of i s s c of this temp ship security message
	 */
	@AutoEscape
	public String getNameOfISSC();

	/**
	 * Sets the name of i s s c of this temp ship security message.
	 *
	 * @param nameOfISSC the name of i s s c of this temp ship security message
	 */
	public void setNameOfISSC(String nameOfISSC);

	/**
	 * Returns the date of i s s c of this temp ship security message.
	 *
	 * @return the date of i s s c of this temp ship security message
	 */
	public Date getDateOfISSC();

	/**
	 * Sets the date of i s s c of this temp ship security message.
	 *
	 * @param dateOfISSC the date of i s s c of this temp ship security message
	 */
	public void setDateOfISSC(Date dateOfISSC);

	/**
	 * Returns the date of expiry i s s c of this temp ship security message.
	 *
	 * @return the date of expiry i s s c of this temp ship security message
	 */
	public Date getDateOfExpiryISSC();

	/**
	 * Sets the date of expiry i s s c of this temp ship security message.
	 *
	 * @param dateOfExpiryISSC the date of expiry i s s c of this temp ship security message
	 */
	public void setDateOfExpiryISSC(Date dateOfExpiryISSC);

	/**
	 * Returns the security level code of this temp ship security message.
	 *
	 * @return the security level code of this temp ship security message
	 */
	@AutoEscape
	public String getSecurityLevelCode();

	/**
	 * Sets the security level code of this temp ship security message.
	 *
	 * @param securityLevelCode the security level code of this temp ship security message
	 */
	public void setSecurityLevelCode(String securityLevelCode);

	/**
	 * Returns the security from date of this temp ship security message.
	 *
	 * @return the security from date of this temp ship security message
	 */
	public Date getSecurityFromDate();

	/**
	 * Sets the security from date of this temp ship security message.
	 *
	 * @param securityFromDate the security from date of this temp ship security message
	 */
	public void setSecurityFromDate(Date securityFromDate);

	/**
	 * Returns the is additional security measures of this temp ship security message.
	 *
	 * @return the is additional security measures of this temp ship security message
	 */
	public int getIsAdditionalSecurityMeasures();

	/**
	 * Sets the is additional security measures of this temp ship security message.
	 *
	 * @param isAdditionalSecurityMeasures the is additional security measures of this temp ship security message
	 */
	public void setIsAdditionalSecurityMeasures(
		int isAdditionalSecurityMeasures);

	/**
	 * Returns the additional security detail of this temp ship security message.
	 *
	 * @return the additional security detail of this temp ship security message
	 */
	@AutoEscape
	public String getAdditionalSecurityDetail();

	/**
	 * Sets the additional security detail of this temp ship security message.
	 *
	 * @param additionalSecurityDetail the additional security detail of this temp ship security message
	 */
	public void setAdditionalSecurityDetail(String additionalSecurityDetail);

	/**
	 * Returns the is maintain security of this temp ship security message.
	 *
	 * @return the is maintain security of this temp ship security message
	 */
	public int getIsMaintainSecurity();

	/**
	 * Sets the is maintain security of this temp ship security message.
	 *
	 * @param isMaintainSecurity the is maintain security of this temp ship security message
	 */
	public void setIsMaintainSecurity(int isMaintainSecurity);

	/**
	 * Returns the maintain security detail of this temp ship security message.
	 *
	 * @return the maintain security detail of this temp ship security message
	 */
	@AutoEscape
	public String getMaintainSecurityDetail();

	/**
	 * Sets the maintain security detail of this temp ship security message.
	 *
	 * @param maintainSecurityDetail the maintain security detail of this temp ship security message
	 */
	public void setMaintainSecurityDetail(String maintainSecurityDetail);

	/**
	 * Returns the latitude of this temp ship security message.
	 *
	 * @return the latitude of this temp ship security message
	 */
	@AutoEscape
	public String getLatitude();

	/**
	 * Sets the latitude of this temp ship security message.
	 *
	 * @param latitude the latitude of this temp ship security message
	 */
	public void setLatitude(String latitude);

	/**
	 * Returns the longitude of this temp ship security message.
	 *
	 * @return the longitude of this temp ship security message
	 */
	@AutoEscape
	public String getLongitude();

	/**
	 * Sets the longitude of this temp ship security message.
	 *
	 * @param longitude the longitude of this temp ship security message
	 */
	public void setLongitude(String longitude);

	/**
	 * Returns the has ship security port items of this temp ship security message.
	 *
	 * @return the has ship security port items of this temp ship security message
	 */
	public int getHasShipSecurityPortItems();

	/**
	 * Sets the has ship security port items of this temp ship security message.
	 *
	 * @param hasShipSecurityPortItems the has ship security port items of this temp ship security message
	 */
	public void setHasShipSecurityPortItems(int hasShipSecurityPortItems);

	/**
	 * Returns the sign place of this temp ship security message.
	 *
	 * @return the sign place of this temp ship security message
	 */
	@AutoEscape
	public String getSignPlace();

	/**
	 * Sets the sign place of this temp ship security message.
	 *
	 * @param signPlace the sign place of this temp ship security message
	 */
	public void setSignPlace(String signPlace);

	/**
	 * Returns the sign date of this temp ship security message.
	 *
	 * @return the sign date of this temp ship security message
	 */
	public Date getSignDate();

	/**
	 * Sets the sign date of this temp ship security message.
	 *
	 * @param signDate the sign date of this temp ship security message
	 */
	public void setSignDate(Date signDate);

	/**
	 * Returns the master signed of this temp ship security message.
	 *
	 * @return the master signed of this temp ship security message
	 */
	public int getMasterSigned();

	/**
	 * Sets the master signed of this temp ship security message.
	 *
	 * @param masterSigned the master signed of this temp ship security message
	 */
	public void setMasterSigned(int masterSigned);

	/**
	 * Returns the master signed image of this temp ship security message.
	 *
	 * @return the master signed image of this temp ship security message
	 */
	public int getMasterSignedImage();

	/**
	 * Sets the master signed image of this temp ship security message.
	 *
	 * @param masterSignedImage the master signed image of this temp ship security message
	 */
	public void setMasterSignedImage(int masterSignedImage);

	/**
	 * Returns the call sign of this temp ship security message.
	 *
	 * @return the call sign of this temp ship security message
	 */
	@AutoEscape
	public String getCallSign();

	/**
	 * Sets the call sign of this temp ship security message.
	 *
	 * @param callSign the call sign of this temp ship security message
	 */
	public void setCallSign(String callSign);

	/**
	 * Returns the arrival port code of this temp ship security message.
	 *
	 * @return the arrival port code of this temp ship security message
	 */
	@AutoEscape
	public String getArrivalPortCode();

	/**
	 * Sets the arrival port code of this temp ship security message.
	 *
	 * @param arrivalPortCode the arrival port code of this temp ship security message
	 */
	public void setArrivalPortCode(String arrivalPortCode);

	/**
	 * Returns the port harbour code of this temp ship security message.
	 *
	 * @return the port harbour code of this temp ship security message
	 */
	@AutoEscape
	public String getPortHarbourCode();

	/**
	 * Sets the port harbour code of this temp ship security message.
	 *
	 * @param portHarbourCode the port harbour code of this temp ship security message
	 */
	public void setPortHarbourCode(String portHarbourCode);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(TempShipSecurityMessage tempShipSecurityMessage);

	public int hashCode();

	public CacheModel<TempShipSecurityMessage> toCacheModel();

	public TempShipSecurityMessage toEscapedModel();

	public String toString();

	public String toXmlString();
}