/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.gt.dao.noticeandmessage.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the TempDocument service. Represents a row in the &quot;TEMP_DOCUMENT&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link vn.gt.dao.noticeandmessage.model.impl.TempDocumentModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link vn.gt.dao.noticeandmessage.model.impl.TempDocumentImpl}.
 * </p>
 *
 * @author win_64
 * @see TempDocument
 * @see vn.gt.dao.noticeandmessage.model.impl.TempDocumentImpl
 * @see vn.gt.dao.noticeandmessage.model.impl.TempDocumentModelImpl
 * @generated
 */
public interface TempDocumentModel extends BaseModel<TempDocument> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a temp document model instance should use the {@link TempDocument} interface instead.
	 */

	/**
	 * Returns the primary key of this temp document.
	 *
	 * @return the primary key of this temp document
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this temp document.
	 *
	 * @param primaryKey the primary key of this temp document
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this temp document.
	 *
	 * @return the ID of this temp document
	 */
	public long getId();

	/**
	 * Sets the ID of this temp document.
	 *
	 * @param id the ID of this temp document
	 */
	public void setId(long id);

	/**
	 * Returns the request code of this temp document.
	 *
	 * @return the request code of this temp document
	 */
	@AutoEscape
	public String getRequestCode();

	/**
	 * Sets the request code of this temp document.
	 *
	 * @param requestCode the request code of this temp document
	 */
	public void setRequestCode(String requestCode);

	/**
	 * Returns the request state of this temp document.
	 *
	 * @return the request state of this temp document
	 */
	public int getRequestState();

	/**
	 * Sets the request state of this temp document.
	 *
	 * @param requestState the request state of this temp document
	 */
	public void setRequestState(int requestState);

	/**
	 * Returns the document name of this temp document.
	 *
	 * @return the document name of this temp document
	 */
	public long getDocumentName();

	/**
	 * Sets the document name of this temp document.
	 *
	 * @param documentName the document name of this temp document
	 */
	public void setDocumentName(long documentName);

	/**
	 * Returns the document year of this temp document.
	 *
	 * @return the document year of this temp document
	 */
	public int getDocumentYear();

	/**
	 * Sets the document year of this temp document.
	 *
	 * @param documentYear the document year of this temp document
	 */
	public void setDocumentYear(int documentYear);

	/**
	 * Returns the document type code of this temp document.
	 *
	 * @return the document type code of this temp document
	 */
	@AutoEscape
	public String getDocumentTypeCode();

	/**
	 * Sets the document type code of this temp document.
	 *
	 * @param documentTypeCode the document type code of this temp document
	 */
	public void setDocumentTypeCode(String documentTypeCode);

	/**
	 * Returns the user created of this temp document.
	 *
	 * @return the user created of this temp document
	 */
	@AutoEscape
	public String getUserCreated();

	/**
	 * Sets the user created of this temp document.
	 *
	 * @param userCreated the user created of this temp document
	 */
	public void setUserCreated(String userCreated);

	/**
	 * Returns the ship agency code of this temp document.
	 *
	 * @return the ship agency code of this temp document
	 */
	@AutoEscape
	public String getShipAgencyCode();

	/**
	 * Sets the ship agency code of this temp document.
	 *
	 * @param shipAgencyCode the ship agency code of this temp document
	 */
	public void setShipAgencyCode(String shipAgencyCode);

	/**
	 * Returns the ship name of this temp document.
	 *
	 * @return the ship name of this temp document
	 */
	@AutoEscape
	public String getShipName();

	/**
	 * Sets the ship name of this temp document.
	 *
	 * @param shipName the ship name of this temp document
	 */
	public void setShipName(String shipName);

	/**
	 * Returns the ship type code of this temp document.
	 *
	 * @return the ship type code of this temp document
	 */
	@AutoEscape
	public String getShipTypeCode();

	/**
	 * Sets the ship type code of this temp document.
	 *
	 * @param shipTypeCode the ship type code of this temp document
	 */
	public void setShipTypeCode(String shipTypeCode);

	/**
	 * Returns the state code of this temp document.
	 *
	 * @return the state code of this temp document
	 */
	@AutoEscape
	public String getStateCode();

	/**
	 * Sets the state code of this temp document.
	 *
	 * @param stateCode the state code of this temp document
	 */
	public void setStateCode(String stateCode);

	/**
	 * Returns the ship captain of this temp document.
	 *
	 * @return the ship captain of this temp document
	 */
	@AutoEscape
	public String getShipCaptain();

	/**
	 * Sets the ship captain of this temp document.
	 *
	 * @param shipCaptain the ship captain of this temp document
	 */
	public void setShipCaptain(String shipCaptain);

	/**
	 * Returns the imo of this temp document.
	 *
	 * @return the imo of this temp document
	 */
	@AutoEscape
	public String getImo();

	/**
	 * Sets the imo of this temp document.
	 *
	 * @param imo the imo of this temp document
	 */
	public void setImo(String imo);

	/**
	 * Returns the grt of this temp document.
	 *
	 * @return the grt of this temp document
	 */
	public double getGrt();

	/**
	 * Sets the grt of this temp document.
	 *
	 * @param grt the grt of this temp document
	 */
	public void setGrt(double grt);

	/**
	 * Returns the nt of this temp document.
	 *
	 * @return the nt of this temp document
	 */
	public double getNt();

	/**
	 * Sets the nt of this temp document.
	 *
	 * @param nt the nt of this temp document
	 */
	public void setNt(double nt);

	/**
	 * Returns the dwt of this temp document.
	 *
	 * @return the dwt of this temp document
	 */
	public double getDwt();

	/**
	 * Sets the dwt of this temp document.
	 *
	 * @param dwt the dwt of this temp document
	 */
	public void setDwt(double dwt);

	/**
	 * Returns the unit g r t of this temp document.
	 *
	 * @return the unit g r t of this temp document
	 */
	@AutoEscape
	public String getUnitGRT();

	/**
	 * Sets the unit g r t of this temp document.
	 *
	 * @param unitGRT the unit g r t of this temp document
	 */
	public void setUnitGRT(String unitGRT);

	/**
	 * Returns the unit n t of this temp document.
	 *
	 * @return the unit n t of this temp document
	 */
	@AutoEscape
	public String getUnitNT();

	/**
	 * Sets the unit n t of this temp document.
	 *
	 * @param unitNT the unit n t of this temp document
	 */
	public void setUnitNT(String unitNT);

	/**
	 * Returns the unit d w t of this temp document.
	 *
	 * @return the unit d w t of this temp document
	 */
	@AutoEscape
	public String getUnitDWT();

	/**
	 * Sets the unit d w t of this temp document.
	 *
	 * @param unitDWT the unit d w t of this temp document
	 */
	public void setUnitDWT(String unitDWT);

	/**
	 * Returns the call sign of this temp document.
	 *
	 * @return the call sign of this temp document
	 */
	@AutoEscape
	public String getCallSign();

	/**
	 * Sets the call sign of this temp document.
	 *
	 * @param callSign the call sign of this temp document
	 */
	public void setCallSign(String callSign);

	/**
	 * Returns the pre document name of this temp document.
	 *
	 * @return the pre document name of this temp document
	 */
	@AutoEscape
	public String getPreDocumentName();

	/**
	 * Sets the pre document name of this temp document.
	 *
	 * @param preDocumentName the pre document name of this temp document
	 */
	public void setPreDocumentName(String preDocumentName);

	/**
	 * Returns the created date of this temp document.
	 *
	 * @return the created date of this temp document
	 */
	public Date getCreatedDate();

	/**
	 * Sets the created date of this temp document.
	 *
	 * @param createdDate the created date of this temp document
	 */
	public void setCreatedDate(Date createdDate);

	/**
	 * Returns the last modified date of this temp document.
	 *
	 * @return the last modified date of this temp document
	 */
	public Date getLastModifiedDate();

	/**
	 * Sets the last modified date of this temp document.
	 *
	 * @param lastModifiedDate the last modified date of this temp document
	 */
	public void setLastModifiedDate(Date lastModifiedDate);

	/**
	 * Returns the flow flag of this temp document.
	 *
	 * @return the flow flag of this temp document
	 */
	public int getFlowFlag();

	/**
	 * Sets the flow flag of this temp document.
	 *
	 * @param flowFlag the flow flag of this temp document
	 */
	public void setFlowFlag(int flowFlag);

	/**
	 * Returns the document status code of this temp document.
	 *
	 * @return the document status code of this temp document
	 */
	public int getDocumentStatusCode();

	/**
	 * Sets the document status code of this temp document.
	 *
	 * @param documentStatusCode the document status code of this temp document
	 */
	public void setDocumentStatusCode(int documentStatusCode);

	/**
	 * Returns the location code of this temp document.
	 *
	 * @return the location code of this temp document
	 */
	@AutoEscape
	public String getLocationCode();

	/**
	 * Sets the location code of this temp document.
	 *
	 * @param locationCode the location code of this temp document
	 */
	public void setLocationCode(String locationCode);

	/**
	 * Returns the maritime code of this temp document.
	 *
	 * @return the maritime code of this temp document
	 */
	@AutoEscape
	public String getMaritimeCode();

	/**
	 * Sets the maritime code of this temp document.
	 *
	 * @param maritimeCode the maritime code of this temp document
	 */
	public void setMaritimeCode(String maritimeCode);

	/**
	 * Returns the port region code of this temp document.
	 *
	 * @return the port region code of this temp document
	 */
	@AutoEscape
	public String getPortRegionCode();

	/**
	 * Sets the port region code of this temp document.
	 *
	 * @param portRegionCode the port region code of this temp document
	 */
	public void setPortRegionCode(String portRegionCode);

	/**
	 * Returns the port code of this temp document.
	 *
	 * @return the port code of this temp document
	 */
	@AutoEscape
	public String getPortCode();

	/**
	 * Sets the port code of this temp document.
	 *
	 * @param portCode the port code of this temp document
	 */
	public void setPortCode(String portCode);

	/**
	 * Returns the last port code of this temp document.
	 *
	 * @return the last port code of this temp document
	 */
	@AutoEscape
	public String getLastPortCode();

	/**
	 * Sets the last port code of this temp document.
	 *
	 * @param lastPortCode the last port code of this temp document
	 */
	public void setLastPortCode(String lastPortCode);

	/**
	 * Returns the ship position of this temp document.
	 *
	 * @return the ship position of this temp document
	 */
	public int getShipPosition();

	/**
	 * Sets the ship position of this temp document.
	 *
	 * @param shipPosition the ship position of this temp document
	 */
	public void setShipPosition(int shipPosition);

	/**
	 * Returns the ship owner code of this temp document.
	 *
	 * @return the ship owner code of this temp document
	 */
	@AutoEscape
	public String getShipOwnerCode();

	/**
	 * Sets the ship owner code of this temp document.
	 *
	 * @param shipOwnerCode the ship owner code of this temp document
	 */
	public void setShipOwnerCode(String shipOwnerCode);

	/**
	 * Returns the arrival ship agency of this temp document.
	 *
	 * @return the arrival ship agency of this temp document
	 */
	@AutoEscape
	public String getArrivalShipAgency();

	/**
	 * Sets the arrival ship agency of this temp document.
	 *
	 * @param arrivalShipAgency the arrival ship agency of this temp document
	 */
	public void setArrivalShipAgency(String arrivalShipAgency);

	/**
	 * Returns the departure ship agency of this temp document.
	 *
	 * @return the departure ship agency of this temp document
	 */
	@AutoEscape
	public String getDepartureShipAgency();

	/**
	 * Sets the departure ship agency of this temp document.
	 *
	 * @param departureShipAgency the departure ship agency of this temp document
	 */
	public void setDepartureShipAgency(String departureShipAgency);

	/**
	 * Returns the ship date from of this temp document.
	 *
	 * @return the ship date from of this temp document
	 */
	public Date getShipDateFrom();

	/**
	 * Sets the ship date from of this temp document.
	 *
	 * @param shipDateFrom the ship date from of this temp document
	 */
	public void setShipDateFrom(Date shipDateFrom);

	/**
	 * Returns the ship date to of this temp document.
	 *
	 * @return the ship date to of this temp document
	 */
	public Date getShipDateTo();

	/**
	 * Sets the ship date to of this temp document.
	 *
	 * @param shipDateTo the ship date to of this temp document
	 */
	public void setShipDateTo(Date shipDateTo);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(TempDocument tempDocument);

	public int hashCode();

	public CacheModel<TempDocument> toCacheModel();

	public TempDocument toEscapedModel();

	public String toString();

	public String toXmlString();
}