/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.gt.dao.noticeandmessage.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the TempPassengerList service. Represents a row in the &quot;TEMP_PASSENGER_LIST&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link vn.gt.dao.noticeandmessage.model.impl.TempPassengerListModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link vn.gt.dao.noticeandmessage.model.impl.TempPassengerListImpl}.
 * </p>
 *
 * @author win_64
 * @see TempPassengerList
 * @see vn.gt.dao.noticeandmessage.model.impl.TempPassengerListImpl
 * @see vn.gt.dao.noticeandmessage.model.impl.TempPassengerListModelImpl
 * @generated
 */
public interface TempPassengerListModel extends BaseModel<TempPassengerList> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a temp passenger list model instance should use the {@link TempPassengerList} interface instead.
	 */

	/**
	 * Returns the primary key of this temp passenger list.
	 *
	 * @return the primary key of this temp passenger list
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this temp passenger list.
	 *
	 * @param primaryKey the primary key of this temp passenger list
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this temp passenger list.
	 *
	 * @return the ID of this temp passenger list
	 */
	public long getId();

	/**
	 * Sets the ID of this temp passenger list.
	 *
	 * @param id the ID of this temp passenger list
	 */
	public void setId(long id);

	/**
	 * Returns the request code of this temp passenger list.
	 *
	 * @return the request code of this temp passenger list
	 */
	@AutoEscape
	public String getRequestCode();

	/**
	 * Sets the request code of this temp passenger list.
	 *
	 * @param requestCode the request code of this temp passenger list
	 */
	public void setRequestCode(String requestCode);

	/**
	 * Returns the request state of this temp passenger list.
	 *
	 * @return the request state of this temp passenger list
	 */
	public int getRequestState();

	/**
	 * Sets the request state of this temp passenger list.
	 *
	 * @param requestState the request state of this temp passenger list
	 */
	public void setRequestState(int requestState);

	/**
	 * Returns the document name of this temp passenger list.
	 *
	 * @return the document name of this temp passenger list
	 */
	public long getDocumentName();

	/**
	 * Sets the document name of this temp passenger list.
	 *
	 * @param documentName the document name of this temp passenger list
	 */
	public void setDocumentName(long documentName);

	/**
	 * Returns the user created of this temp passenger list.
	 *
	 * @return the user created of this temp passenger list
	 */
	@AutoEscape
	public String getUserCreated();

	/**
	 * Sets the user created of this temp passenger list.
	 *
	 * @param userCreated the user created of this temp passenger list
	 */
	public void setUserCreated(String userCreated);

	/**
	 * Returns the is arrival of this temp passenger list.
	 *
	 * @return the is arrival of this temp passenger list
	 */
	public int getIsArrival();

	/**
	 * Sets the is arrival of this temp passenger list.
	 *
	 * @param isArrival the is arrival of this temp passenger list
	 */
	public void setIsArrival(int isArrival);

	/**
	 * Returns the name of ship of this temp passenger list.
	 *
	 * @return the name of ship of this temp passenger list
	 */
	@AutoEscape
	public String getNameOfShip();

	/**
	 * Sets the name of ship of this temp passenger list.
	 *
	 * @param nameOfShip the name of ship of this temp passenger list
	 */
	public void setNameOfShip(String nameOfShip);

	/**
	 * Returns the port of arrival code of this temp passenger list.
	 *
	 * @return the port of arrival code of this temp passenger list
	 */
	@AutoEscape
	public String getPortOfArrivalCode();

	/**
	 * Sets the port of arrival code of this temp passenger list.
	 *
	 * @param portOfArrivalCode the port of arrival code of this temp passenger list
	 */
	public void setPortOfArrivalCode(String portOfArrivalCode);

	/**
	 * Returns the date of arrival of this temp passenger list.
	 *
	 * @return the date of arrival of this temp passenger list
	 */
	public Date getDateOfArrival();

	/**
	 * Sets the date of arrival of this temp passenger list.
	 *
	 * @param dateOfArrival the date of arrival of this temp passenger list
	 */
	public void setDateOfArrival(Date dateOfArrival);

	/**
	 * Returns the imo number of this temp passenger list.
	 *
	 * @return the imo number of this temp passenger list
	 */
	@AutoEscape
	public String getImoNumber();

	/**
	 * Sets the imo number of this temp passenger list.
	 *
	 * @param imoNumber the imo number of this temp passenger list
	 */
	public void setImoNumber(String imoNumber);

	/**
	 * Returns the call sign of this temp passenger list.
	 *
	 * @return the call sign of this temp passenger list
	 */
	@AutoEscape
	public String getCallSign();

	/**
	 * Sets the call sign of this temp passenger list.
	 *
	 * @param callSign the call sign of this temp passenger list
	 */
	public void setCallSign(String callSign);

	/**
	 * Returns the voyage number of this temp passenger list.
	 *
	 * @return the voyage number of this temp passenger list
	 */
	@AutoEscape
	public String getVoyageNumber();

	/**
	 * Sets the voyage number of this temp passenger list.
	 *
	 * @param voyageNumber the voyage number of this temp passenger list
	 */
	public void setVoyageNumber(String voyageNumber);

	/**
	 * Returns the flag state of ship of this temp passenger list.
	 *
	 * @return the flag state of ship of this temp passenger list
	 */
	@AutoEscape
	public String getFlagStateOfShip();

	/**
	 * Sets the flag state of ship of this temp passenger list.
	 *
	 * @param flagStateOfShip the flag state of ship of this temp passenger list
	 */
	public void setFlagStateOfShip(String flagStateOfShip);

	/**
	 * Returns the list passengers of this temp passenger list.
	 *
	 * @return the list passengers of this temp passenger list
	 */
	public int getListPassengers();

	/**
	 * Sets the list passengers of this temp passenger list.
	 *
	 * @param listPassengers the list passengers of this temp passenger list
	 */
	public void setListPassengers(int listPassengers);

	/**
	 * Returns the sign place of this temp passenger list.
	 *
	 * @return the sign place of this temp passenger list
	 */
	@AutoEscape
	public String getSignPlace();

	/**
	 * Sets the sign place of this temp passenger list.
	 *
	 * @param signPlace the sign place of this temp passenger list
	 */
	public void setSignPlace(String signPlace);

	/**
	 * Returns the sign date of this temp passenger list.
	 *
	 * @return the sign date of this temp passenger list
	 */
	public Date getSignDate();

	/**
	 * Sets the sign date of this temp passenger list.
	 *
	 * @param signDate the sign date of this temp passenger list
	 */
	public void setSignDate(Date signDate);

	/**
	 * Returns the master signed of this temp passenger list.
	 *
	 * @return the master signed of this temp passenger list
	 */
	public int getMasterSigned();

	/**
	 * Sets the master signed of this temp passenger list.
	 *
	 * @param masterSigned the master signed of this temp passenger list
	 */
	public void setMasterSigned(int masterSigned);

	/**
	 * Returns the master signed image of this temp passenger list.
	 *
	 * @return the master signed image of this temp passenger list
	 */
	public int getMasterSignedImage();

	/**
	 * Sets the master signed image of this temp passenger list.
	 *
	 * @param masterSignedImage the master signed image of this temp passenger list
	 */
	public void setMasterSignedImage(int masterSignedImage);

	/**
	 * Returns the attached file of this temp passenger list.
	 *
	 * @return the attached file of this temp passenger list
	 */
	public long getAttachedFile();

	/**
	 * Sets the attached file of this temp passenger list.
	 *
	 * @param attachedFile the attached file of this temp passenger list
	 */
	public void setAttachedFile(long attachedFile);

	/**
	 * Returns the document year of this temp passenger list.
	 *
	 * @return the document year of this temp passenger list
	 */
	public int getDocumentYear();

	/**
	 * Sets the document year of this temp passenger list.
	 *
	 * @param documentYear the document year of this temp passenger list
	 */
	public void setDocumentYear(int documentYear);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(TempPassengerList tempPassengerList);

	public int hashCode();

	public CacheModel<TempPassengerList> toCacheModel();

	public TempPassengerList toEscapedModel();

	public String toString();

	public String toXmlString();
}