/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.gt.dao.noticeandmessage.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the TempGeneralDeclaration service. Represents a row in the &quot;TEMP_GENERAL_DECLARATION&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link vn.gt.dao.noticeandmessage.model.impl.TempGeneralDeclarationModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link vn.gt.dao.noticeandmessage.model.impl.TempGeneralDeclarationImpl}.
 * </p>
 *
 * @author win_64
 * @see TempGeneralDeclaration
 * @see vn.gt.dao.noticeandmessage.model.impl.TempGeneralDeclarationImpl
 * @see vn.gt.dao.noticeandmessage.model.impl.TempGeneralDeclarationModelImpl
 * @generated
 */
public interface TempGeneralDeclarationModel extends BaseModel<TempGeneralDeclaration> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a temp general declaration model instance should use the {@link TempGeneralDeclaration} interface instead.
	 */

	/**
	 * Returns the primary key of this temp general declaration.
	 *
	 * @return the primary key of this temp general declaration
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this temp general declaration.
	 *
	 * @param primaryKey the primary key of this temp general declaration
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this temp general declaration.
	 *
	 * @return the ID of this temp general declaration
	 */
	public long getId();

	/**
	 * Sets the ID of this temp general declaration.
	 *
	 * @param id the ID of this temp general declaration
	 */
	public void setId(long id);

	/**
	 * Returns the request code of this temp general declaration.
	 *
	 * @return the request code of this temp general declaration
	 */
	@AutoEscape
	public String getRequestCode();

	/**
	 * Sets the request code of this temp general declaration.
	 *
	 * @param requestCode the request code of this temp general declaration
	 */
	public void setRequestCode(String requestCode);

	/**
	 * Returns the request state of this temp general declaration.
	 *
	 * @return the request state of this temp general declaration
	 */
	public int getRequestState();

	/**
	 * Sets the request state of this temp general declaration.
	 *
	 * @param requestState the request state of this temp general declaration
	 */
	public void setRequestState(int requestState);

	/**
	 * Returns the document name of this temp general declaration.
	 *
	 * @return the document name of this temp general declaration
	 */
	public long getDocumentName();

	/**
	 * Sets the document name of this temp general declaration.
	 *
	 * @param documentName the document name of this temp general declaration
	 */
	public void setDocumentName(long documentName);

	/**
	 * Returns the document year of this temp general declaration.
	 *
	 * @return the document year of this temp general declaration
	 */
	public int getDocumentYear();

	/**
	 * Sets the document year of this temp general declaration.
	 *
	 * @param documentYear the document year of this temp general declaration
	 */
	public void setDocumentYear(int documentYear);

	/**
	 * Returns the user created of this temp general declaration.
	 *
	 * @return the user created of this temp general declaration
	 */
	@AutoEscape
	public String getUserCreated();

	/**
	 * Sets the user created of this temp general declaration.
	 *
	 * @param userCreated the user created of this temp general declaration
	 */
	public void setUserCreated(String userCreated);

	/**
	 * Returns the is arrival of this temp general declaration.
	 *
	 * @return the is arrival of this temp general declaration
	 */
	public int getIsArrival();

	/**
	 * Sets the is arrival of this temp general declaration.
	 *
	 * @param isArrival the is arrival of this temp general declaration
	 */
	public void setIsArrival(int isArrival);

	/**
	 * Returns the name of ship of this temp general declaration.
	 *
	 * @return the name of ship of this temp general declaration
	 */
	@AutoEscape
	public String getNameOfShip();

	/**
	 * Sets the name of ship of this temp general declaration.
	 *
	 * @param nameOfShip the name of ship of this temp general declaration
	 */
	public void setNameOfShip(String nameOfShip);

	/**
	 * Returns the ship type code of this temp general declaration.
	 *
	 * @return the ship type code of this temp general declaration
	 */
	@AutoEscape
	public String getShipTypeCode();

	/**
	 * Sets the ship type code of this temp general declaration.
	 *
	 * @param shipTypeCode the ship type code of this temp general declaration
	 */
	public void setShipTypeCode(String shipTypeCode);

	/**
	 * Returns the imo number of this temp general declaration.
	 *
	 * @return the imo number of this temp general declaration
	 */
	@AutoEscape
	public String getImoNumber();

	/**
	 * Sets the imo number of this temp general declaration.
	 *
	 * @param imoNumber the imo number of this temp general declaration
	 */
	public void setImoNumber(String imoNumber);

	/**
	 * Returns the call sign of this temp general declaration.
	 *
	 * @return the call sign of this temp general declaration
	 */
	@AutoEscape
	public String getCallSign();

	/**
	 * Sets the call sign of this temp general declaration.
	 *
	 * @param callSign the call sign of this temp general declaration
	 */
	public void setCallSign(String callSign);

	/**
	 * Returns the voyage number of this temp general declaration.
	 *
	 * @return the voyage number of this temp general declaration
	 */
	@AutoEscape
	public String getVoyageNumber();

	/**
	 * Sets the voyage number of this temp general declaration.
	 *
	 * @param voyageNumber the voyage number of this temp general declaration
	 */
	public void setVoyageNumber(String voyageNumber);

	/**
	 * Returns the port of arrival code of this temp general declaration.
	 *
	 * @return the port of arrival code of this temp general declaration
	 */
	@AutoEscape
	public String getPortOfArrivalCode();

	/**
	 * Sets the port of arrival code of this temp general declaration.
	 *
	 * @param portOfArrivalCode the port of arrival code of this temp general declaration
	 */
	public void setPortOfArrivalCode(String portOfArrivalCode);

	/**
	 * Returns the date of arrival of this temp general declaration.
	 *
	 * @return the date of arrival of this temp general declaration
	 */
	public Date getDateOfArrival();

	/**
	 * Sets the date of arrival of this temp general declaration.
	 *
	 * @param dateOfArrival the date of arrival of this temp general declaration
	 */
	public void setDateOfArrival(Date dateOfArrival);

	/**
	 * Returns the port harbour code of this temp general declaration.
	 *
	 * @return the port harbour code of this temp general declaration
	 */
	@AutoEscape
	public String getPortHarbourCode();

	/**
	 * Sets the port harbour code of this temp general declaration.
	 *
	 * @param portHarbourCode the port harbour code of this temp general declaration
	 */
	public void setPortHarbourCode(String portHarbourCode);

	/**
	 * Returns the port region code of this temp general declaration.
	 *
	 * @return the port region code of this temp general declaration
	 */
	@AutoEscape
	public String getPortRegionCode();

	/**
	 * Sets the port region code of this temp general declaration.
	 *
	 * @param portRegionCode the port region code of this temp general declaration
	 */
	public void setPortRegionCode(String portRegionCode);

	/**
	 * Returns the port wharf code of this temp general declaration.
	 *
	 * @return the port wharf code of this temp general declaration
	 */
	@AutoEscape
	public String getPortWharfCode();

	/**
	 * Sets the port wharf code of this temp general declaration.
	 *
	 * @param portWharfCode the port wharf code of this temp general declaration
	 */
	public void setPortWharfCode(String portWharfCode);

	/**
	 * Returns the flag state of ship of this temp general declaration.
	 *
	 * @return the flag state of ship of this temp general declaration
	 */
	@AutoEscape
	public String getFlagStateOfShip();

	/**
	 * Sets the flag state of ship of this temp general declaration.
	 *
	 * @param flagStateOfShip the flag state of ship of this temp general declaration
	 */
	public void setFlagStateOfShip(String flagStateOfShip);

	/**
	 * Returns the name of master of this temp general declaration.
	 *
	 * @return the name of master of this temp general declaration
	 */
	@AutoEscape
	public String getNameOfMaster();

	/**
	 * Sets the name of master of this temp general declaration.
	 *
	 * @param nameOfMaster the name of master of this temp general declaration
	 */
	public void setNameOfMaster(String nameOfMaster);

	/**
	 * Returns the last port of call code of this temp general declaration.
	 *
	 * @return the last port of call code of this temp general declaration
	 */
	@AutoEscape
	public String getLastPortOfCallCode();

	/**
	 * Sets the last port of call code of this temp general declaration.
	 *
	 * @param lastPortOfCallCode the last port of call code of this temp general declaration
	 */
	public void setLastPortOfCallCode(String lastPortOfCallCode);

	/**
	 * Returns the certificate of registry number of this temp general declaration.
	 *
	 * @return the certificate of registry number of this temp general declaration
	 */
	@AutoEscape
	public String getCertificateOfRegistryNumber();

	/**
	 * Sets the certificate of registry number of this temp general declaration.
	 *
	 * @param certificateOfRegistryNumber the certificate of registry number of this temp general declaration
	 */
	public void setCertificateOfRegistryNumber(
		String certificateOfRegistryNumber);

	/**
	 * Returns the certificate of registry date of this temp general declaration.
	 *
	 * @return the certificate of registry date of this temp general declaration
	 */
	public Date getCertificateOfRegistryDate();

	/**
	 * Sets the certificate of registry date of this temp general declaration.
	 *
	 * @param certificateOfRegistryDate the certificate of registry date of this temp general declaration
	 */
	public void setCertificateOfRegistryDate(Date certificateOfRegistryDate);

	/**
	 * Returns the certificate of registry port name of this temp general declaration.
	 *
	 * @return the certificate of registry port name of this temp general declaration
	 */
	@AutoEscape
	public String getCertificateOfRegistryPortName();

	/**
	 * Sets the certificate of registry port name of this temp general declaration.
	 *
	 * @param certificateOfRegistryPortName the certificate of registry port name of this temp general declaration
	 */
	public void setCertificateOfRegistryPortName(
		String certificateOfRegistryPortName);

	/**
	 * Returns the tax code of shipowners agents of this temp general declaration.
	 *
	 * @return the tax code of shipowners agents of this temp general declaration
	 */
	@AutoEscape
	public String getTaxCodeOfShipownersAgents();

	/**
	 * Sets the tax code of shipowners agents of this temp general declaration.
	 *
	 * @param taxCodeOfShipownersAgents the tax code of shipowners agents of this temp general declaration
	 */
	public void setTaxCodeOfShipownersAgents(String taxCodeOfShipownersAgents);

	/**
	 * Returns the name of shipowners agents of this temp general declaration.
	 *
	 * @return the name of shipowners agents of this temp general declaration
	 */
	@AutoEscape
	public String getNameOfShipownersAgents();

	/**
	 * Sets the name of shipowners agents of this temp general declaration.
	 *
	 * @param nameOfShipownersAgents the name of shipowners agents of this temp general declaration
	 */
	public void setNameOfShipownersAgents(String nameOfShipownersAgents);

	/**
	 * Returns the ship agency address of this temp general declaration.
	 *
	 * @return the ship agency address of this temp general declaration
	 */
	@AutoEscape
	public String getShipAgencyAddress();

	/**
	 * Sets the ship agency address of this temp general declaration.
	 *
	 * @param shipAgencyAddress the ship agency address of this temp general declaration
	 */
	public void setShipAgencyAddress(String shipAgencyAddress);

	/**
	 * Returns the ship agency phone of this temp general declaration.
	 *
	 * @return the ship agency phone of this temp general declaration
	 */
	@AutoEscape
	public String getShipAgencyPhone();

	/**
	 * Sets the ship agency phone of this temp general declaration.
	 *
	 * @param shipAgencyPhone the ship agency phone of this temp general declaration
	 */
	public void setShipAgencyPhone(String shipAgencyPhone);

	/**
	 * Returns the ship agency fax of this temp general declaration.
	 *
	 * @return the ship agency fax of this temp general declaration
	 */
	@AutoEscape
	public String getShipAgencyFax();

	/**
	 * Sets the ship agency fax of this temp general declaration.
	 *
	 * @param shipAgencyFax the ship agency fax of this temp general declaration
	 */
	public void setShipAgencyFax(String shipAgencyFax);

	/**
	 * Returns the ship agency email of this temp general declaration.
	 *
	 * @return the ship agency email of this temp general declaration
	 */
	@AutoEscape
	public String getShipAgencyEmail();

	/**
	 * Sets the ship agency email of this temp general declaration.
	 *
	 * @param shipAgencyEmail the ship agency email of this temp general declaration
	 */
	public void setShipAgencyEmail(String shipAgencyEmail);

	/**
	 * Returns the gross tonnage of this temp general declaration.
	 *
	 * @return the gross tonnage of this temp general declaration
	 */
	public double getGrossTonnage();

	/**
	 * Sets the gross tonnage of this temp general declaration.
	 *
	 * @param grossTonnage the gross tonnage of this temp general declaration
	 */
	public void setGrossTonnage(double grossTonnage);

	/**
	 * Returns the net tonnage of this temp general declaration.
	 *
	 * @return the net tonnage of this temp general declaration
	 */
	public double getNetTonnage();

	/**
	 * Sets the net tonnage of this temp general declaration.
	 *
	 * @param netTonnage the net tonnage of this temp general declaration
	 */
	public void setNetTonnage(double netTonnage);

	/**
	 * Returns the position of ship inport of this temp general declaration.
	 *
	 * @return the position of ship inport of this temp general declaration
	 */
	@AutoEscape
	public String getPositionOfShipInport();

	/**
	 * Sets the position of ship inport of this temp general declaration.
	 *
	 * @param positionOfShipInport the position of ship inport of this temp general declaration
	 */
	public void setPositionOfShipInport(String positionOfShipInport);

	/**
	 * Returns the brief particulars of voyage of this temp general declaration.
	 *
	 * @return the brief particulars of voyage of this temp general declaration
	 */
	@AutoEscape
	public String getBriefParticularsOfVoyage();

	/**
	 * Sets the brief particulars of voyage of this temp general declaration.
	 *
	 * @param briefParticularsOfVoyage the brief particulars of voyage of this temp general declaration
	 */
	public void setBriefParticularsOfVoyage(String briefParticularsOfVoyage);

	/**
	 * Returns the brief description of the cargo of this temp general declaration.
	 *
	 * @return the brief description of the cargo of this temp general declaration
	 */
	@AutoEscape
	public String getBriefDescriptionOfTheCargo();

	/**
	 * Sets the brief description of the cargo of this temp general declaration.
	 *
	 * @param briefDescriptionOfTheCargo the brief description of the cargo of this temp general declaration
	 */
	public void setBriefDescriptionOfTheCargo(String briefDescriptionOfTheCargo);

	/**
	 * Returns the number of crew of this temp general declaration.
	 *
	 * @return the number of crew of this temp general declaration
	 */
	public int getNumberOfCrew();

	/**
	 * Sets the number of crew of this temp general declaration.
	 *
	 * @param numberOfCrew the number of crew of this temp general declaration
	 */
	public void setNumberOfCrew(int numberOfCrew);

	/**
	 * Returns the number of passengers of this temp general declaration.
	 *
	 * @return the number of passengers of this temp general declaration
	 */
	public int getNumberOfPassengers();

	/**
	 * Sets the number of passengers of this temp general declaration.
	 *
	 * @param numberOfPassengers the number of passengers of this temp general declaration
	 */
	public void setNumberOfPassengers(int numberOfPassengers);

	/**
	 * Returns the ship requirements in terms of waste of this temp general declaration.
	 *
	 * @return the ship requirements in terms of waste of this temp general declaration
	 */
	@AutoEscape
	public String getShipRequirementsInTermsOfWaste();

	/**
	 * Sets the ship requirements in terms of waste of this temp general declaration.
	 *
	 * @param shipRequirementsInTermsOfWaste the ship requirements in terms of waste of this temp general declaration
	 */
	public void setShipRequirementsInTermsOfWaste(
		String shipRequirementsInTermsOfWaste);

	/**
	 * Returns the remarks of this temp general declaration.
	 *
	 * @return the remarks of this temp general declaration
	 */
	@AutoEscape
	public String getRemarks();

	/**
	 * Sets the remarks of this temp general declaration.
	 *
	 * @param remarks the remarks of this temp general declaration
	 */
	public void setRemarks(String remarks);

	/**
	 * Returns the number cargo declaration of this temp general declaration.
	 *
	 * @return the number cargo declaration of this temp general declaration
	 */
	@AutoEscape
	public String getNumberCargoDeclaration();

	/**
	 * Sets the number cargo declaration of this temp general declaration.
	 *
	 * @param numberCargoDeclaration the number cargo declaration of this temp general declaration
	 */
	public void setNumberCargoDeclaration(String numberCargoDeclaration);

	/**
	 * Returns the number ship store declaration of this temp general declaration.
	 *
	 * @return the number ship store declaration of this temp general declaration
	 */
	@AutoEscape
	public String getNumberShipStoreDeclaration();

	/**
	 * Sets the number ship store declaration of this temp general declaration.
	 *
	 * @param numberShipStoreDeclaration the number ship store declaration of this temp general declaration
	 */
	public void setNumberShipStoreDeclaration(String numberShipStoreDeclaration);

	/**
	 * Returns the number crew list of this temp general declaration.
	 *
	 * @return the number crew list of this temp general declaration
	 */
	@AutoEscape
	public String getNumberCrewList();

	/**
	 * Sets the number crew list of this temp general declaration.
	 *
	 * @param numberCrewList the number crew list of this temp general declaration
	 */
	public void setNumberCrewList(String numberCrewList);

	/**
	 * Returns the number passenger list of this temp general declaration.
	 *
	 * @return the number passenger list of this temp general declaration
	 */
	@AutoEscape
	public String getNumberPassengerList();

	/**
	 * Sets the number passenger list of this temp general declaration.
	 *
	 * @param numberPassengerList the number passenger list of this temp general declaration
	 */
	public void setNumberPassengerList(String numberPassengerList);

	/**
	 * Returns the number crew effects of this temp general declaration.
	 *
	 * @return the number crew effects of this temp general declaration
	 */
	@AutoEscape
	public String getNumberCrewEffects();

	/**
	 * Sets the number crew effects of this temp general declaration.
	 *
	 * @param numberCrewEffects the number crew effects of this temp general declaration
	 */
	public void setNumberCrewEffects(String numberCrewEffects);

	/**
	 * Returns the number health maritime of this temp general declaration.
	 *
	 * @return the number health maritime of this temp general declaration
	 */
	@AutoEscape
	public String getNumberHealthMaritime();

	/**
	 * Sets the number health maritime of this temp general declaration.
	 *
	 * @param numberHealthMaritime the number health maritime of this temp general declaration
	 */
	public void setNumberHealthMaritime(String numberHealthMaritime);

	/**
	 * Returns the sign place of this temp general declaration.
	 *
	 * @return the sign place of this temp general declaration
	 */
	@AutoEscape
	public String getSignPlace();

	/**
	 * Sets the sign place of this temp general declaration.
	 *
	 * @param signPlace the sign place of this temp general declaration
	 */
	public void setSignPlace(String signPlace);

	/**
	 * Returns the sign date of this temp general declaration.
	 *
	 * @return the sign date of this temp general declaration
	 */
	public Date getSignDate();

	/**
	 * Sets the sign date of this temp general declaration.
	 *
	 * @param signDate the sign date of this temp general declaration
	 */
	public void setSignDate(Date signDate);

	/**
	 * Returns the master signed of this temp general declaration.
	 *
	 * @return the master signed of this temp general declaration
	 */
	public int getMasterSigned();

	/**
	 * Sets the master signed of this temp general declaration.
	 *
	 * @param masterSigned the master signed of this temp general declaration
	 */
	public void setMasterSigned(int masterSigned);

	/**
	 * Returns the master signed image of this temp general declaration.
	 *
	 * @return the master signed image of this temp general declaration
	 */
	public int getMasterSignedImage();

	/**
	 * Sets the master signed image of this temp general declaration.
	 *
	 * @param masterSignedImage the master signed image of this temp general declaration
	 */
	public void setMasterSignedImage(int masterSignedImage);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(TempGeneralDeclaration tempGeneralDeclaration);

	public int hashCode();

	public CacheModel<TempGeneralDeclaration> toCacheModel();

	public TempGeneralDeclaration toEscapedModel();

	public String toString();

	public String toXmlString();
}