/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.gt.dao.danhmucgt.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the DmGtStatus service. Represents a row in the &quot;DM_GT_STATUS&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link vn.gt.dao.danhmucgt.model.impl.DmGtStatusModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link vn.gt.dao.danhmucgt.model.impl.DmGtStatusImpl}.
 * </p>
 *
 * @author win_64
 * @see DmGtStatus
 * @see vn.gt.dao.danhmucgt.model.impl.DmGtStatusImpl
 * @see vn.gt.dao.danhmucgt.model.impl.DmGtStatusModelImpl
 * @generated
 */
public interface DmGtStatusModel extends BaseModel<DmGtStatus> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a dm gt status model instance should use the {@link DmGtStatus} interface instead.
	 */

	/**
	 * Returns the primary key of this dm gt status.
	 *
	 * @return the primary key of this dm gt status
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this dm gt status.
	 *
	 * @param primaryKey the primary key of this dm gt status
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this dm gt status.
	 *
	 * @return the ID of this dm gt status
	 */
	public long getId();

	/**
	 * Sets the ID of this dm gt status.
	 *
	 * @param id the ID of this dm gt status
	 */
	public void setId(long id);

	/**
	 * Returns the status code of this dm gt status.
	 *
	 * @return the status code of this dm gt status
	 */
	public int getStatusCode();

	/**
	 * Sets the status code of this dm gt status.
	 *
	 * @param statusCode the status code of this dm gt status
	 */
	public void setStatusCode(int statusCode);

	/**
	 * Returns the status name of this dm gt status.
	 *
	 * @return the status name of this dm gt status
	 */
	@AutoEscape
	public String getStatusName();

	/**
	 * Sets the status name of this dm gt status.
	 *
	 * @param statusName the status name of this dm gt status
	 */
	public void setStatusName(String statusName);

	/**
	 * Returns the type of this dm gt status.
	 *
	 * @return the type of this dm gt status
	 */
	public int getType();

	/**
	 * Sets the type of this dm gt status.
	 *
	 * @param type the type of this dm gt status
	 */
	public void setType(int type);

	/**
	 * Returns the description of this dm gt status.
	 *
	 * @return the description of this dm gt status
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this dm gt status.
	 *
	 * @param description the description of this dm gt status
	 */
	public void setDescription(String description);

	/**
	 * Returns the is delete of this dm gt status.
	 *
	 * @return the is delete of this dm gt status
	 */
	public int getIsDelete();

	/**
	 * Sets the is delete of this dm gt status.
	 *
	 * @param isDelete the is delete of this dm gt status
	 */
	public void setIsDelete(int isDelete);

	/**
	 * Returns the marked as delete of this dm gt status.
	 *
	 * @return the marked as delete of this dm gt status
	 */
	public int getMarkedAsDelete();

	/**
	 * Sets the marked as delete of this dm gt status.
	 *
	 * @param markedAsDelete the marked as delete of this dm gt status
	 */
	public void setMarkedAsDelete(int markedAsDelete);

	/**
	 * Returns the modified date of this dm gt status.
	 *
	 * @return the modified date of this dm gt status
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this dm gt status.
	 *
	 * @param modifiedDate the modified date of this dm gt status
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the requested date of this dm gt status.
	 *
	 * @return the requested date of this dm gt status
	 */
	public Date getRequestedDate();

	/**
	 * Sets the requested date of this dm gt status.
	 *
	 * @param requestedDate the requested date of this dm gt status
	 */
	public void setRequestedDate(Date requestedDate);

	/**
	 * Returns the sync version of this dm gt status.
	 *
	 * @return the sync version of this dm gt status
	 */
	@AutoEscape
	public String getSyncVersion();

	/**
	 * Sets the sync version of this dm gt status.
	 *
	 * @param syncVersion the sync version of this dm gt status
	 */
	public void setSyncVersion(String syncVersion);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(DmGtStatus dmGtStatus);

	public int hashCode();

	public CacheModel<DmGtStatus> toCacheModel();

	public DmGtStatus toEscapedModel();

	public String toString();

	public String toXmlString();
}