/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.gt.dao.danhmucgt.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the DmGtReportTemplate service. Represents a row in the &quot;DM_GT_REPORT_TEMPLATE&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link vn.gt.dao.danhmucgt.model.impl.DmGtReportTemplateModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link vn.gt.dao.danhmucgt.model.impl.DmGtReportTemplateImpl}.
 * </p>
 *
 * @author win_64
 * @see DmGtReportTemplate
 * @see vn.gt.dao.danhmucgt.model.impl.DmGtReportTemplateImpl
 * @see vn.gt.dao.danhmucgt.model.impl.DmGtReportTemplateModelImpl
 * @generated
 */
public interface DmGtReportTemplateModel extends BaseModel<DmGtReportTemplate> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a dm gt report template model instance should use the {@link DmGtReportTemplate} interface instead.
	 */

	/**
	 * Returns the primary key of this dm gt report template.
	 *
	 * @return the primary key of this dm gt report template
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this dm gt report template.
	 *
	 * @param primaryKey the primary key of this dm gt report template
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this dm gt report template.
	 *
	 * @return the ID of this dm gt report template
	 */
	public long getId();

	/**
	 * Sets the ID of this dm gt report template.
	 *
	 * @param id the ID of this dm gt report template
	 */
	public void setId(long id);

	/**
	 * Returns the report code of this dm gt report template.
	 *
	 * @return the report code of this dm gt report template
	 */
	public int getReportCode();

	/**
	 * Sets the report code of this dm gt report template.
	 *
	 * @param reportCode the report code of this dm gt report template
	 */
	public void setReportCode(int reportCode);

	/**
	 * Returns the report name of this dm gt report template.
	 *
	 * @return the report name of this dm gt report template
	 */
	@AutoEscape
	public String getReportName();

	/**
	 * Sets the report name of this dm gt report template.
	 *
	 * @param reportName the report name of this dm gt report template
	 */
	public void setReportName(String reportName);

	/**
	 * Returns the report type of this dm gt report template.
	 *
	 * @return the report type of this dm gt report template
	 */
	public int getReportType();

	/**
	 * Sets the report type of this dm gt report template.
	 *
	 * @param reportType the report type of this dm gt report template
	 */
	public void setReportType(int reportType);

	/**
	 * Returns the category of this dm gt report template.
	 *
	 * @return the category of this dm gt report template
	 */
	@AutoEscape
	public String getCategory();

	/**
	 * Sets the category of this dm gt report template.
	 *
	 * @param category the category of this dm gt report template
	 */
	public void setCategory(String category);

	/**
	 * Returns the description of this dm gt report template.
	 *
	 * @return the description of this dm gt report template
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this dm gt report template.
	 *
	 * @param description the description of this dm gt report template
	 */
	public void setDescription(String description);

	/**
	 * Returns the is delete of this dm gt report template.
	 *
	 * @return the is delete of this dm gt report template
	 */
	public int getIsDelete();

	/**
	 * Sets the is delete of this dm gt report template.
	 *
	 * @param isDelete the is delete of this dm gt report template
	 */
	public void setIsDelete(int isDelete);

	/**
	 * Returns the marked as delete of this dm gt report template.
	 *
	 * @return the marked as delete of this dm gt report template
	 */
	public int getMarkedAsDelete();

	/**
	 * Sets the marked as delete of this dm gt report template.
	 *
	 * @param markedAsDelete the marked as delete of this dm gt report template
	 */
	public void setMarkedAsDelete(int markedAsDelete);

	/**
	 * Returns the modified date of this dm gt report template.
	 *
	 * @return the modified date of this dm gt report template
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this dm gt report template.
	 *
	 * @param modifiedDate the modified date of this dm gt report template
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the requested date of this dm gt report template.
	 *
	 * @return the requested date of this dm gt report template
	 */
	public Date getRequestedDate();

	/**
	 * Sets the requested date of this dm gt report template.
	 *
	 * @param requestedDate the requested date of this dm gt report template
	 */
	public void setRequestedDate(Date requestedDate);

	/**
	 * Returns the sync version of this dm gt report template.
	 *
	 * @return the sync version of this dm gt report template
	 */
	@AutoEscape
	public String getSyncVersion();

	/**
	 * Sets the sync version of this dm gt report template.
	 *
	 * @param syncVersion the sync version of this dm gt report template
	 */
	public void setSyncVersion(String syncVersion);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(DmGtReportTemplate dmGtReportTemplate);

	public int hashCode();

	public CacheModel<DmGtReportTemplate> toCacheModel();

	public DmGtReportTemplate toEscapedModel();

	public String toString();

	public String toXmlString();
}