/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.gt.dao.danhmucgt.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the DmGtReportCategory service. Represents a row in the &quot;DM_GT_REPORT_CATEGORY&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link vn.gt.dao.danhmucgt.model.impl.DmGtReportCategoryModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link vn.gt.dao.danhmucgt.model.impl.DmGtReportCategoryImpl}.
 * </p>
 *
 * @author win_64
 * @see DmGtReportCategory
 * @see vn.gt.dao.danhmucgt.model.impl.DmGtReportCategoryImpl
 * @see vn.gt.dao.danhmucgt.model.impl.DmGtReportCategoryModelImpl
 * @generated
 */
public interface DmGtReportCategoryModel extends BaseModel<DmGtReportCategory> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a dm gt report category model instance should use the {@link DmGtReportCategory} interface instead.
	 */

	/**
	 * Returns the primary key of this dm gt report category.
	 *
	 * @return the primary key of this dm gt report category
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this dm gt report category.
	 *
	 * @param primaryKey the primary key of this dm gt report category
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this dm gt report category.
	 *
	 * @return the ID of this dm gt report category
	 */
	public long getId();

	/**
	 * Sets the ID of this dm gt report category.
	 *
	 * @param id the ID of this dm gt report category
	 */
	public void setId(long id);

	/**
	 * Returns the category of this dm gt report category.
	 *
	 * @return the category of this dm gt report category
	 */
	@AutoEscape
	public String getCategory();

	/**
	 * Sets the category of this dm gt report category.
	 *
	 * @param category the category of this dm gt report category
	 */
	public void setCategory(String category);

	/**
	 * Returns the category name of this dm gt report category.
	 *
	 * @return the category name of this dm gt report category
	 */
	@AutoEscape
	public String getCategoryName();

	/**
	 * Sets the category name of this dm gt report category.
	 *
	 * @param categoryName the category name of this dm gt report category
	 */
	public void setCategoryName(String categoryName);

	/**
	 * Returns the category order of this dm gt report category.
	 *
	 * @return the category order of this dm gt report category
	 */
	public int getCategoryOrder();

	/**
	 * Sets the category order of this dm gt report category.
	 *
	 * @param categoryOrder the category order of this dm gt report category
	 */
	public void setCategoryOrder(int categoryOrder);

	/**
	 * Returns the is delete of this dm gt report category.
	 *
	 * @return the is delete of this dm gt report category
	 */
	public int getIsDelete();

	/**
	 * Sets the is delete of this dm gt report category.
	 *
	 * @param isDelete the is delete of this dm gt report category
	 */
	public void setIsDelete(int isDelete);

	/**
	 * Returns the marked as delete of this dm gt report category.
	 *
	 * @return the marked as delete of this dm gt report category
	 */
	public int getMarkedAsDelete();

	/**
	 * Sets the marked as delete of this dm gt report category.
	 *
	 * @param markedAsDelete the marked as delete of this dm gt report category
	 */
	public void setMarkedAsDelete(int markedAsDelete);

	/**
	 * Returns the modified date of this dm gt report category.
	 *
	 * @return the modified date of this dm gt report category
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this dm gt report category.
	 *
	 * @param modifiedDate the modified date of this dm gt report category
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the requested date of this dm gt report category.
	 *
	 * @return the requested date of this dm gt report category
	 */
	public Date getRequestedDate();

	/**
	 * Sets the requested date of this dm gt report category.
	 *
	 * @param requestedDate the requested date of this dm gt report category
	 */
	public void setRequestedDate(Date requestedDate);

	/**
	 * Returns the sync version of this dm gt report category.
	 *
	 * @return the sync version of this dm gt report category
	 */
	@AutoEscape
	public String getSyncVersion();

	/**
	 * Sets the sync version of this dm gt report category.
	 *
	 * @param syncVersion the sync version of this dm gt report category
	 */
	public void setSyncVersion(String syncVersion);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(DmGtReportCategory dmGtReportCategory);

	public int hashCode();

	public CacheModel<DmGtReportCategory> toCacheModel();

	public DmGtReportCategory toEscapedModel();

	public String toString();

	public String toXmlString();
}