/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.gt.dao.danhmucgt.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the DmGTFunctionType service. Represents a row in the &quot;DM_GT_FUNCTION_TYPE&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link vn.gt.dao.danhmucgt.model.impl.DmGTFunctionTypeModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link vn.gt.dao.danhmucgt.model.impl.DmGTFunctionTypeImpl}.
 * </p>
 *
 * @author win_64
 * @see DmGTFunctionType
 * @see vn.gt.dao.danhmucgt.model.impl.DmGTFunctionTypeImpl
 * @see vn.gt.dao.danhmucgt.model.impl.DmGTFunctionTypeModelImpl
 * @generated
 */
public interface DmGTFunctionTypeModel extends BaseModel<DmGTFunctionType> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a dm g t function type model instance should use the {@link DmGTFunctionType} interface instead.
	 */

	/**
	 * Returns the primary key of this dm g t function type.
	 *
	 * @return the primary key of this dm g t function type
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this dm g t function type.
	 *
	 * @param primaryKey the primary key of this dm g t function type
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this dm g t function type.
	 *
	 * @return the ID of this dm g t function type
	 */
	public long getId();

	/**
	 * Sets the ID of this dm g t function type.
	 *
	 * @param id the ID of this dm g t function type
	 */
	public void setId(long id);

	/**
	 * Returns the function type code of this dm g t function type.
	 *
	 * @return the function type code of this dm g t function type
	 */
	@AutoEscape
	public String getFunctionTypeCode();

	/**
	 * Sets the function type code of this dm g t function type.
	 *
	 * @param functionTypeCode the function type code of this dm g t function type
	 */
	public void setFunctionTypeCode(String functionTypeCode);

	/**
	 * Returns the function type name of this dm g t function type.
	 *
	 * @return the function type name of this dm g t function type
	 */
	@AutoEscape
	public String getFunctionTypeName();

	/**
	 * Sets the function type name of this dm g t function type.
	 *
	 * @param functionTypeName the function type name of this dm g t function type
	 */
	public void setFunctionTypeName(String functionTypeName);

	/**
	 * Returns the function type name v n of this dm g t function type.
	 *
	 * @return the function type name v n of this dm g t function type
	 */
	@AutoEscape
	public String getFunctionTypeNameVN();

	/**
	 * Sets the function type name v n of this dm g t function type.
	 *
	 * @param functionTypeNameVN the function type name v n of this dm g t function type
	 */
	public void setFunctionTypeNameVN(String functionTypeNameVN);

	/**
	 * Returns the function type order of this dm g t function type.
	 *
	 * @return the function type order of this dm g t function type
	 */
	public int getFunctionTypeOrder();

	/**
	 * Sets the function type order of this dm g t function type.
	 *
	 * @param functionTypeOrder the function type order of this dm g t function type
	 */
	public void setFunctionTypeOrder(int functionTypeOrder);

	/**
	 * Returns the is delete of this dm g t function type.
	 *
	 * @return the is delete of this dm g t function type
	 */
	public int getIsDelete();

	/**
	 * Sets the is delete of this dm g t function type.
	 *
	 * @param isDelete the is delete of this dm g t function type
	 */
	public void setIsDelete(int isDelete);

	/**
	 * Returns the marked as delete of this dm g t function type.
	 *
	 * @return the marked as delete of this dm g t function type
	 */
	public int getMarkedAsDelete();

	/**
	 * Sets the marked as delete of this dm g t function type.
	 *
	 * @param markedAsDelete the marked as delete of this dm g t function type
	 */
	public void setMarkedAsDelete(int markedAsDelete);

	/**
	 * Returns the modified date of this dm g t function type.
	 *
	 * @return the modified date of this dm g t function type
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this dm g t function type.
	 *
	 * @param modifiedDate the modified date of this dm g t function type
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the requested date of this dm g t function type.
	 *
	 * @return the requested date of this dm g t function type
	 */
	public Date getRequestedDate();

	/**
	 * Sets the requested date of this dm g t function type.
	 *
	 * @param requestedDate the requested date of this dm g t function type
	 */
	public void setRequestedDate(Date requestedDate);

	/**
	 * Returns the sync version of this dm g t function type.
	 *
	 * @return the sync version of this dm g t function type
	 */
	@AutoEscape
	public String getSyncVersion();

	/**
	 * Sets the sync version of this dm g t function type.
	 *
	 * @param syncVersion the sync version of this dm g t function type
	 */
	public void setSyncVersion(String syncVersion);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(DmGTFunctionType dmGTFunctionType);

	public int hashCode();

	public CacheModel<DmGTFunctionType> toCacheModel();

	public DmGTFunctionType toEscapedModel();

	public String toString();

	public String toXmlString();
}