/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.gt.dao.danhmuc.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the DmGoodsType service. Represents a row in the &quot;DM_GOODS_TYPE&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link vn.gt.dao.danhmuc.model.impl.DmGoodsTypeModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link vn.gt.dao.danhmuc.model.impl.DmGoodsTypeImpl}.
 * </p>
 *
 * @author win_64
 * @see DmGoodsType
 * @see vn.gt.dao.danhmuc.model.impl.DmGoodsTypeImpl
 * @see vn.gt.dao.danhmuc.model.impl.DmGoodsTypeModelImpl
 * @generated
 */
public interface DmGoodsTypeModel extends BaseModel<DmGoodsType> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a dm goods type model instance should use the {@link DmGoodsType} interface instead.
	 */

	/**
	 * Returns the primary key of this dm goods type.
	 *
	 * @return the primary key of this dm goods type
	 */
	public int getPrimaryKey();

	/**
	 * Sets the primary key of this dm goods type.
	 *
	 * @param primaryKey the primary key of this dm goods type
	 */
	public void setPrimaryKey(int primaryKey);

	/**
	 * Returns the ID of this dm goods type.
	 *
	 * @return the ID of this dm goods type
	 */
	public int getId();

	/**
	 * Sets the ID of this dm goods type.
	 *
	 * @param id the ID of this dm goods type
	 */
	public void setId(int id);

	/**
	 * Returns the goods type code of this dm goods type.
	 *
	 * @return the goods type code of this dm goods type
	 */
	@AutoEscape
	public String getGoodsTypeCode();

	/**
	 * Sets the goods type code of this dm goods type.
	 *
	 * @param goodsTypeCode the goods type code of this dm goods type
	 */
	public void setGoodsTypeCode(String goodsTypeCode);

	/**
	 * Returns the goods type name of this dm goods type.
	 *
	 * @return the goods type name of this dm goods type
	 */
	@AutoEscape
	public String getGoodsTypeName();

	/**
	 * Sets the goods type name of this dm goods type.
	 *
	 * @param goodsTypeName the goods type name of this dm goods type
	 */
	public void setGoodsTypeName(String goodsTypeName);

	/**
	 * Returns the goods type name v n of this dm goods type.
	 *
	 * @return the goods type name v n of this dm goods type
	 */
	@AutoEscape
	public String getGoodsTypeNameVN();

	/**
	 * Sets the goods type name v n of this dm goods type.
	 *
	 * @param goodsTypeNameVN the goods type name v n of this dm goods type
	 */
	public void setGoodsTypeNameVN(String goodsTypeNameVN);

	/**
	 * Returns the goods type order of this dm goods type.
	 *
	 * @return the goods type order of this dm goods type
	 */
	public int getGoodsTypeOrder();

	/**
	 * Sets the goods type order of this dm goods type.
	 *
	 * @param goodsTypeOrder the goods type order of this dm goods type
	 */
	public void setGoodsTypeOrder(int goodsTypeOrder);

	/**
	 * Returns the is delete of this dm goods type.
	 *
	 * @return the is delete of this dm goods type
	 */
	public int getIsDelete();

	/**
	 * Sets the is delete of this dm goods type.
	 *
	 * @param isDelete the is delete of this dm goods type
	 */
	public void setIsDelete(int isDelete);

	/**
	 * Returns the marked as delete of this dm goods type.
	 *
	 * @return the marked as delete of this dm goods type
	 */
	public int getMarkedAsDelete();

	/**
	 * Sets the marked as delete of this dm goods type.
	 *
	 * @param markedAsDelete the marked as delete of this dm goods type
	 */
	public void setMarkedAsDelete(int markedAsDelete);

	/**
	 * Returns the modified date of this dm goods type.
	 *
	 * @return the modified date of this dm goods type
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this dm goods type.
	 *
	 * @param modifiedDate the modified date of this dm goods type
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the requested date of this dm goods type.
	 *
	 * @return the requested date of this dm goods type
	 */
	public Date getRequestedDate();

	/**
	 * Sets the requested date of this dm goods type.
	 *
	 * @param requestedDate the requested date of this dm goods type
	 */
	public void setRequestedDate(Date requestedDate);

	/**
	 * Returns the sync version of this dm goods type.
	 *
	 * @return the sync version of this dm goods type
	 */
	@AutoEscape
	public String getSyncVersion();

	/**
	 * Sets the sync version of this dm goods type.
	 *
	 * @param syncVersion the sync version of this dm goods type
	 */
	public void setSyncVersion(String syncVersion);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(DmGoodsType dmGoodsType);

	public int hashCode();

	public CacheModel<DmGoodsType> toCacheModel();

	public DmGoodsType toEscapedModel();

	public String toString();

	public String toXmlString();
}