/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.gt.dao.danhmuc.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the DmHistorySecurityLevel service. Represents a row in the &quot;DM_HISTORY_SECURITY_LEVEL&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link vn.gt.dao.danhmuc.model.impl.DmHistorySecurityLevelModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link vn.gt.dao.danhmuc.model.impl.DmHistorySecurityLevelImpl}.
 * </p>
 *
 * @author win_64
 * @see DmHistorySecurityLevel
 * @see vn.gt.dao.danhmuc.model.impl.DmHistorySecurityLevelImpl
 * @see vn.gt.dao.danhmuc.model.impl.DmHistorySecurityLevelModelImpl
 * @generated
 */
public interface DmHistorySecurityLevelModel extends BaseModel<DmHistorySecurityLevel> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a dm history security level model instance should use the {@link DmHistorySecurityLevel} interface instead.
	 */

	/**
	 * Returns the primary key of this dm history security level.
	 *
	 * @return the primary key of this dm history security level
	 */
	public int getPrimaryKey();

	/**
	 * Sets the primary key of this dm history security level.
	 *
	 * @param primaryKey the primary key of this dm history security level
	 */
	public void setPrimaryKey(int primaryKey);

	/**
	 * Returns the ID of this dm history security level.
	 *
	 * @return the ID of this dm history security level
	 */
	public int getId();

	/**
	 * Sets the ID of this dm history security level.
	 *
	 * @param id the ID of this dm history security level
	 */
	public void setId(int id);

	/**
	 * Returns the security level code of this dm history security level.
	 *
	 * @return the security level code of this dm history security level
	 */
	@AutoEscape
	public String getSecurityLevelCode();

	/**
	 * Sets the security level code of this dm history security level.
	 *
	 * @param securityLevelCode the security level code of this dm history security level
	 */
	public void setSecurityLevelCode(String securityLevelCode);

	/**
	 * Returns the security level of this dm history security level.
	 *
	 * @return the security level of this dm history security level
	 */
	@AutoEscape
	public String getSecurityLevel();

	/**
	 * Sets the security level of this dm history security level.
	 *
	 * @param securityLevel the security level of this dm history security level
	 */
	public void setSecurityLevel(String securityLevel);

	/**
	 * Returns the security level name of this dm history security level.
	 *
	 * @return the security level name of this dm history security level
	 */
	@AutoEscape
	public String getSecurityLevelName();

	/**
	 * Sets the security level name of this dm history security level.
	 *
	 * @param securityLevelName the security level name of this dm history security level
	 */
	public void setSecurityLevelName(String securityLevelName);

	/**
	 * Returns the is delete of this dm history security level.
	 *
	 * @return the is delete of this dm history security level
	 */
	public int getIsDelete();

	/**
	 * Sets the is delete of this dm history security level.
	 *
	 * @param isDelete the is delete of this dm history security level
	 */
	public void setIsDelete(int isDelete);

	/**
	 * Returns the marked as delete of this dm history security level.
	 *
	 * @return the marked as delete of this dm history security level
	 */
	public int getMarkedAsDelete();

	/**
	 * Sets the marked as delete of this dm history security level.
	 *
	 * @param markedAsDelete the marked as delete of this dm history security level
	 */
	public void setMarkedAsDelete(int markedAsDelete);

	/**
	 * Returns the modified date of this dm history security level.
	 *
	 * @return the modified date of this dm history security level
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this dm history security level.
	 *
	 * @param modifiedDate the modified date of this dm history security level
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the requested date of this dm history security level.
	 *
	 * @return the requested date of this dm history security level
	 */
	public Date getRequestedDate();

	/**
	 * Sets the requested date of this dm history security level.
	 *
	 * @param requestedDate the requested date of this dm history security level
	 */
	public void setRequestedDate(Date requestedDate);

	/**
	 * Returns the sync version of this dm history security level.
	 *
	 * @return the sync version of this dm history security level
	 */
	@AutoEscape
	public String getSyncVersion();

	/**
	 * Sets the sync version of this dm history security level.
	 *
	 * @param syncVersion the sync version of this dm history security level
	 */
	public void setSyncVersion(String syncVersion);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(DmHistorySecurityLevel dmHistorySecurityLevel);

	public int hashCode();

	public CacheModel<DmHistorySecurityLevel> toCacheModel();

	public DmHistorySecurityLevel toEscapedModel();

	public String toString();

	public String toXmlString();
}