/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.gt.dao.danhmuc.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the DmPassportType service. Represents a row in the &quot;DM_PASSPORT_TYPE&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link vn.gt.dao.danhmuc.model.impl.DmPassportTypeModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link vn.gt.dao.danhmuc.model.impl.DmPassportTypeImpl}.
 * </p>
 *
 * @author win_64
 * @see DmPassportType
 * @see vn.gt.dao.danhmuc.model.impl.DmPassportTypeImpl
 * @see vn.gt.dao.danhmuc.model.impl.DmPassportTypeModelImpl
 * @generated
 */
public interface DmPassportTypeModel extends BaseModel<DmPassportType> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a dm passport type model instance should use the {@link DmPassportType} interface instead.
	 */

	/**
	 * Returns the primary key of this dm passport type.
	 *
	 * @return the primary key of this dm passport type
	 */
	public int getPrimaryKey();

	/**
	 * Sets the primary key of this dm passport type.
	 *
	 * @param primaryKey the primary key of this dm passport type
	 */
	public void setPrimaryKey(int primaryKey);

	/**
	 * Returns the ID of this dm passport type.
	 *
	 * @return the ID of this dm passport type
	 */
	public int getId();

	/**
	 * Sets the ID of this dm passport type.
	 *
	 * @param id the ID of this dm passport type
	 */
	public void setId(int id);

	/**
	 * Returns the passport type code of this dm passport type.
	 *
	 * @return the passport type code of this dm passport type
	 */
	@AutoEscape
	public String getPassportTypeCode();

	/**
	 * Sets the passport type code of this dm passport type.
	 *
	 * @param passportTypeCode the passport type code of this dm passport type
	 */
	public void setPassportTypeCode(String passportTypeCode);

	/**
	 * Returns the passport type of this dm passport type.
	 *
	 * @return the passport type of this dm passport type
	 */
	@AutoEscape
	public String getPassportType();

	/**
	 * Sets the passport type of this dm passport type.
	 *
	 * @param passportType the passport type of this dm passport type
	 */
	public void setPassportType(String passportType);

	/**
	 * Returns the passport type name of this dm passport type.
	 *
	 * @return the passport type name of this dm passport type
	 */
	@AutoEscape
	public String getPassportTypeName();

	/**
	 * Sets the passport type name of this dm passport type.
	 *
	 * @param passportTypeName the passport type name of this dm passport type
	 */
	public void setPassportTypeName(String passportTypeName);

	/**
	 * Returns the passport type name v n of this dm passport type.
	 *
	 * @return the passport type name v n of this dm passport type
	 */
	@AutoEscape
	public String getPassportTypeNameVN();

	/**
	 * Sets the passport type name v n of this dm passport type.
	 *
	 * @param passportTypeNameVN the passport type name v n of this dm passport type
	 */
	public void setPassportTypeNameVN(String passportTypeNameVN);

	/**
	 * Returns the is delete of this dm passport type.
	 *
	 * @return the is delete of this dm passport type
	 */
	public int getIsDelete();

	/**
	 * Sets the is delete of this dm passport type.
	 *
	 * @param isDelete the is delete of this dm passport type
	 */
	public void setIsDelete(int isDelete);

	/**
	 * Returns the marked as delete of this dm passport type.
	 *
	 * @return the marked as delete of this dm passport type
	 */
	public int getMarkedAsDelete();

	/**
	 * Sets the marked as delete of this dm passport type.
	 *
	 * @param markedAsDelete the marked as delete of this dm passport type
	 */
	public void setMarkedAsDelete(int markedAsDelete);

	/**
	 * Returns the modified date of this dm passport type.
	 *
	 * @return the modified date of this dm passport type
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this dm passport type.
	 *
	 * @param modifiedDate the modified date of this dm passport type
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the requested date of this dm passport type.
	 *
	 * @return the requested date of this dm passport type
	 */
	public Date getRequestedDate();

	/**
	 * Sets the requested date of this dm passport type.
	 *
	 * @param requestedDate the requested date of this dm passport type
	 */
	public void setRequestedDate(Date requestedDate);

	/**
	 * Returns the sync version of this dm passport type.
	 *
	 * @return the sync version of this dm passport type
	 */
	@AutoEscape
	public String getSyncVersion();

	/**
	 * Sets the sync version of this dm passport type.
	 *
	 * @param syncVersion the sync version of this dm passport type
	 */
	public void setSyncVersion(String syncVersion);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(DmPassportType dmPassportType);

	public int hashCode();

	public CacheModel<DmPassportType> toCacheModel();

	public DmPassportType toEscapedModel();

	public String toString();

	public String toXmlString();
}