/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.gt.dao.danhmuc.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the DmPort service. Represents a row in the &quot;DM_PORT&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link vn.gt.dao.danhmuc.model.impl.DmPortModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link vn.gt.dao.danhmuc.model.impl.DmPortImpl}.
 * </p>
 *
 * @author win_64
 * @see DmPort
 * @see vn.gt.dao.danhmuc.model.impl.DmPortImpl
 * @see vn.gt.dao.danhmuc.model.impl.DmPortModelImpl
 * @generated
 */
public interface DmPortModel extends BaseModel<DmPort> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a dm port model instance should use the {@link DmPort} interface instead.
	 */

	/**
	 * Returns the primary key of this dm port.
	 *
	 * @return the primary key of this dm port
	 */
	public int getPrimaryKey();

	/**
	 * Sets the primary key of this dm port.
	 *
	 * @param primaryKey the primary key of this dm port
	 */
	public void setPrimaryKey(int primaryKey);

	/**
	 * Returns the ID of this dm port.
	 *
	 * @return the ID of this dm port
	 */
	public int getId();

	/**
	 * Sets the ID of this dm port.
	 *
	 * @param id the ID of this dm port
	 */
	public void setId(int id);

	/**
	 * Returns the port code of this dm port.
	 *
	 * @return the port code of this dm port
	 */
	@AutoEscape
	public String getPortCode();

	/**
	 * Sets the port code of this dm port.
	 *
	 * @param portCode the port code of this dm port
	 */
	public void setPortCode(String portCode);

	/**
	 * Returns the lo code of this dm port.
	 *
	 * @return the lo code of this dm port
	 */
	@AutoEscape
	public String getLoCode();

	/**
	 * Sets the lo code of this dm port.
	 *
	 * @param loCode the lo code of this dm port
	 */
	public void setLoCode(String loCode);

	/**
	 * Returns the port name of this dm port.
	 *
	 * @return the port name of this dm port
	 */
	@AutoEscape
	public String getPortName();

	/**
	 * Sets the port name of this dm port.
	 *
	 * @param portName the port name of this dm port
	 */
	public void setPortName(String portName);

	/**
	 * Returns the full name of this dm port.
	 *
	 * @return the full name of this dm port
	 */
	@AutoEscape
	public String getFullName();

	/**
	 * Sets the full name of this dm port.
	 *
	 * @param fullName the full name of this dm port
	 */
	public void setFullName(String fullName);

	/**
	 * Returns the full name v n of this dm port.
	 *
	 * @return the full name v n of this dm port
	 */
	@AutoEscape
	public String getFullNameVN();

	/**
	 * Sets the full name v n of this dm port.
	 *
	 * @param fullNameVN the full name v n of this dm port
	 */
	public void setFullNameVN(String fullNameVN);

	/**
	 * Returns the port type of this dm port.
	 *
	 * @return the port type of this dm port
	 */
	@AutoEscape
	public String getPortType();

	/**
	 * Sets the port type of this dm port.
	 *
	 * @param portType the port type of this dm port
	 */
	public void setPortType(String portType);

	/**
	 * Returns the port order of this dm port.
	 *
	 * @return the port order of this dm port
	 */
	public int getPortOrder();

	/**
	 * Sets the port order of this dm port.
	 *
	 * @param portOrder the port order of this dm port
	 */
	public void setPortOrder(int portOrder);

	/**
	 * Returns the address of this dm port.
	 *
	 * @return the address of this dm port
	 */
	@AutoEscape
	public String getAddress();

	/**
	 * Sets the address of this dm port.
	 *
	 * @param address the address of this dm port
	 */
	public void setAddress(String address);

	/**
	 * Returns the address v n of this dm port.
	 *
	 * @return the address v n of this dm port
	 */
	@AutoEscape
	public String getAddressVN();

	/**
	 * Sets the address v n of this dm port.
	 *
	 * @param addressVN the address v n of this dm port
	 */
	public void setAddressVN(String addressVN);

	/**
	 * Returns the state code of this dm port.
	 *
	 * @return the state code of this dm port
	 */
	@AutoEscape
	public String getStateCode();

	/**
	 * Sets the state code of this dm port.
	 *
	 * @param stateCode the state code of this dm port
	 */
	public void setStateCode(String stateCode);

	/**
	 * Returns the citycode of this dm port.
	 *
	 * @return the citycode of this dm port
	 */
	@AutoEscape
	public String getCitycode();

	/**
	 * Sets the citycode of this dm port.
	 *
	 * @param citycode the citycode of this dm port
	 */
	public void setCitycode(String citycode);

	/**
	 * Returns the is delete of this dm port.
	 *
	 * @return the is delete of this dm port
	 */
	public int getIsDelete();

	/**
	 * Sets the is delete of this dm port.
	 *
	 * @param isDelete the is delete of this dm port
	 */
	public void setIsDelete(int isDelete);

	/**
	 * Returns the marked as delete of this dm port.
	 *
	 * @return the marked as delete of this dm port
	 */
	public int getMarkedAsDelete();

	/**
	 * Sets the marked as delete of this dm port.
	 *
	 * @param markedAsDelete the marked as delete of this dm port
	 */
	public void setMarkedAsDelete(int markedAsDelete);

	/**
	 * Returns the modified date of this dm port.
	 *
	 * @return the modified date of this dm port
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this dm port.
	 *
	 * @param modifiedDate the modified date of this dm port
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the requested date of this dm port.
	 *
	 * @return the requested date of this dm port
	 */
	public Date getRequestedDate();

	/**
	 * Sets the requested date of this dm port.
	 *
	 * @param requestedDate the requested date of this dm port
	 */
	public void setRequestedDate(Date requestedDate);

	/**
	 * Returns the sync version of this dm port.
	 *
	 * @return the sync version of this dm port
	 */
	@AutoEscape
	public String getSyncVersion();

	/**
	 * Sets the sync version of this dm port.
	 *
	 * @param syncVersion the sync version of this dm port
	 */
	public void setSyncVersion(String syncVersion);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(DmPort dmPort);

	public int hashCode();

	public CacheModel<DmPort> toCacheModel();

	public DmPort toEscapedModel();

	public String toString();

	public String toXmlString();
}