/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.gt.dao.danhmuc.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the DmTestN01Request service. Represents a row in the &quot;dm_test_n01_request&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link vn.gt.dao.danhmuc.model.impl.DmTestN01RequestModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link vn.gt.dao.danhmuc.model.impl.DmTestN01RequestImpl}.
 * </p>
 *
 * @author win_64
 * @see DmTestN01Request
 * @see vn.gt.dao.danhmuc.model.impl.DmTestN01RequestImpl
 * @see vn.gt.dao.danhmuc.model.impl.DmTestN01RequestModelImpl
 * @generated
 */
public interface DmTestN01RequestModel extends BaseModel<DmTestN01Request> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a dm test n01 request model instance should use the {@link DmTestN01Request} interface instead.
	 */

	/**
	 * Returns the primary key of this dm test n01 request.
	 *
	 * @return the primary key of this dm test n01 request
	 */
	public int getPrimaryKey();

	/**
	 * Sets the primary key of this dm test n01 request.
	 *
	 * @param primaryKey the primary key of this dm test n01 request
	 */
	public void setPrimaryKey(int primaryKey);

	/**
	 * Returns the request i d of this dm test n01 request.
	 *
	 * @return the request i d of this dm test n01 request
	 */
	public int getRequestID();

	/**
	 * Sets the request i d of this dm test n01 request.
	 *
	 * @param requestID the request i d of this dm test n01 request
	 */
	public void setRequestID(int requestID);

	/**
	 * Returns the enterprise code of this dm test n01 request.
	 *
	 * @return the enterprise code of this dm test n01 request
	 */
	@AutoEscape
	public String getEnterpriseCode();

	/**
	 * Sets the enterprise code of this dm test n01 request.
	 *
	 * @param enterpriseCode the enterprise code of this dm test n01 request
	 */
	public void setEnterpriseCode(String enterpriseCode);

	/**
	 * Returns the ten du an of this dm test n01 request.
	 *
	 * @return the ten du an of this dm test n01 request
	 */
	@AutoEscape
	public String getTenDuAn();

	/**
	 * Sets the ten du an of this dm test n01 request.
	 *
	 * @param tenDuAn the ten du an of this dm test n01 request
	 */
	public void setTenDuAn(String tenDuAn);

	/**
	 * Returns the su can thiet dau tu of this dm test n01 request.
	 *
	 * @return the su can thiet dau tu of this dm test n01 request
	 */
	@AutoEscape
	public String getSuCanThietDauTu();

	/**
	 * Sets the su can thiet dau tu of this dm test n01 request.
	 *
	 * @param suCanThietDauTu the su can thiet dau tu of this dm test n01 request
	 */
	public void setSuCanThietDauTu(String suCanThietDauTu);

	/**
	 * Returns the vi tri of this dm test n01 request.
	 *
	 * @return the vi tri of this dm test n01 request
	 */
	@AutoEscape
	public String getViTri();

	/**
	 * Sets the vi tri of this dm test n01 request.
	 *
	 * @param viTri the vi tri of this dm test n01 request
	 */
	public void setViTri(String viTri);

	/**
	 * Returns the loai tau bien gioi han vao cang of this dm test n01 request.
	 *
	 * @return the loai tau bien gioi han vao cang of this dm test n01 request
	 */
	@AutoEscape
	public String getLoaiTauBienGioiHanVaoCang();

	/**
	 * Sets the loai tau bien gioi han vao cang of this dm test n01 request.
	 *
	 * @param loaiTauBienGioiHanVaoCang the loai tau bien gioi han vao cang of this dm test n01 request
	 */
	public void setLoaiTauBienGioiHanVaoCang(String loaiTauBienGioiHanVaoCang);

	/**
	 * Returns the so luong cau cang of this dm test n01 request.
	 *
	 * @return the so luong cau cang of this dm test n01 request
	 */
	@AutoEscape
	public String getSoLuongCauCang();

	/**
	 * Sets the so luong cau cang of this dm test n01 request.
	 *
	 * @param soLuongCauCang the so luong cau cang of this dm test n01 request
	 */
	public void setSoLuongCauCang(String soLuongCauCang);

	/**
	 * Returns the tong dien tich xay dung du kien of this dm test n01 request.
	 *
	 * @return the tong dien tich xay dung du kien of this dm test n01 request
	 */
	@AutoEscape
	public String getTongDienTichXayDungDuKien();

	/**
	 * Sets the tong dien tich xay dung du kien of this dm test n01 request.
	 *
	 * @param tongDienTichXayDungDuKien the tong dien tich xay dung du kien of this dm test n01 request
	 */
	public void setTongDienTichXayDungDuKien(String tongDienTichXayDungDuKien);

	/**
	 * Returns the tai lieulien quan of this dm test n01 request.
	 *
	 * @return the tai lieulien quan of this dm test n01 request
	 */
	@AutoEscape
	public String getTaiLieulienQuan();

	/**
	 * Sets the tai lieulien quan of this dm test n01 request.
	 *
	 * @param taiLieulienQuan the tai lieulien quan of this dm test n01 request
	 */
	public void setTaiLieulienQuan(String taiLieulienQuan);

	/**
	 * Returns the modified date of this dm test n01 request.
	 *
	 * @return the modified date of this dm test n01 request
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this dm test n01 request.
	 *
	 * @param modifiedDate the modified date of this dm test n01 request
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the modified user of this dm test n01 request.
	 *
	 * @return the modified user of this dm test n01 request
	 */
	@AutoEscape
	public String getModifiedUser();

	/**
	 * Sets the modified user of this dm test n01 request.
	 *
	 * @param modifiedUser the modified user of this dm test n01 request
	 */
	public void setModifiedUser(String modifiedUser);

	/**
	 * Returns the is authorized of this dm test n01 request.
	 *
	 * @return the is authorized of this dm test n01 request
	 */
	public int getIsAuthorized();

	/**
	 * Sets the is authorized of this dm test n01 request.
	 *
	 * @param isAuthorized the is authorized of this dm test n01 request
	 */
	public void setIsAuthorized(int isAuthorized);

	/**
	 * Returns the authorized date of this dm test n01 request.
	 *
	 * @return the authorized date of this dm test n01 request
	 */
	public Date getAuthorizedDate();

	/**
	 * Sets the authorized date of this dm test n01 request.
	 *
	 * @param authorizedDate the authorized date of this dm test n01 request
	 */
	public void setAuthorizedDate(Date authorizedDate);

	/**
	 * Returns the authorized user of this dm test n01 request.
	 *
	 * @return the authorized user of this dm test n01 request
	 */
	@AutoEscape
	public String getAuthorizedUser();

	/**
	 * Sets the authorized user of this dm test n01 request.
	 *
	 * @param authorizedUser the authorized user of this dm test n01 request
	 */
	public void setAuthorizedUser(String authorizedUser);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(DmTestN01Request dmTestN01Request);

	public int hashCode();

	public CacheModel<DmTestN01Request> toCacheModel();

	public DmTestN01Request toEscapedModel();

	public String toString();

	public String toXmlString();
}