/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.gt.dao.common.service.base;

import com.liferay.counter.service.CounterLocalService;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.bean.IdentifiableBean;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.service.ResourceLocalService;
import com.liferay.portal.service.ResourceService;
import com.liferay.portal.service.UserLocalService;
import com.liferay.portal.service.UserService;
import com.liferay.portal.service.base.PrincipalBean;
import com.liferay.portal.service.persistence.ResourcePersistence;
import com.liferay.portal.service.persistence.UserPersistence;

import vn.gt.dao.common.model.LogMessageValidation;
import vn.gt.dao.common.service.LogMessageValidationLocalService;
import vn.gt.dao.common.service.LogMessageValidationService;
import vn.gt.dao.common.service.UserPortLocalService;
import vn.gt.dao.common.service.UserPortService;
import vn.gt.dao.common.service.persistence.LogMessageValidationPersistence;
import vn.gt.dao.common.service.persistence.UserPortPersistence;

import javax.sql.DataSource;

/**
 * The base implementation of the log message validation remote service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link vn.gt.dao.common.service.impl.LogMessageValidationServiceImpl}.
 * </p>
 *
 * @author win_64
 * @see vn.gt.dao.common.service.impl.LogMessageValidationServiceImpl
 * @see vn.gt.dao.common.service.LogMessageValidationServiceUtil
 * @generated
 */
public abstract class LogMessageValidationServiceBaseImpl extends PrincipalBean
	implements LogMessageValidationService, IdentifiableBean {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link vn.gt.dao.common.service.LogMessageValidationServiceUtil} to access the log message validation remote service.
	 */

	/**
	 * Returns the log message validation local service.
	 *
	 * @return the log message validation local service
	 */
	public LogMessageValidationLocalService getLogMessageValidationLocalService() {
		return logMessageValidationLocalService;
	}

	/**
	 * Sets the log message validation local service.
	 *
	 * @param logMessageValidationLocalService the log message validation local service
	 */
	public void setLogMessageValidationLocalService(
		LogMessageValidationLocalService logMessageValidationLocalService) {
		this.logMessageValidationLocalService = logMessageValidationLocalService;
	}

	/**
	 * Returns the log message validation remote service.
	 *
	 * @return the log message validation remote service
	 */
	public LogMessageValidationService getLogMessageValidationService() {
		return logMessageValidationService;
	}

	/**
	 * Sets the log message validation remote service.
	 *
	 * @param logMessageValidationService the log message validation remote service
	 */
	public void setLogMessageValidationService(
		LogMessageValidationService logMessageValidationService) {
		this.logMessageValidationService = logMessageValidationService;
	}

	/**
	 * Returns the log message validation persistence.
	 *
	 * @return the log message validation persistence
	 */
	public LogMessageValidationPersistence getLogMessageValidationPersistence() {
		return logMessageValidationPersistence;
	}

	/**
	 * Sets the log message validation persistence.
	 *
	 * @param logMessageValidationPersistence the log message validation persistence
	 */
	public void setLogMessageValidationPersistence(
		LogMessageValidationPersistence logMessageValidationPersistence) {
		this.logMessageValidationPersistence = logMessageValidationPersistence;
	}

	/**
	 * Returns the user port local service.
	 *
	 * @return the user port local service
	 */
	public UserPortLocalService getUserPortLocalService() {
		return userPortLocalService;
	}

	/**
	 * Sets the user port local service.
	 *
	 * @param userPortLocalService the user port local service
	 */
	public void setUserPortLocalService(
		UserPortLocalService userPortLocalService) {
		this.userPortLocalService = userPortLocalService;
	}

	/**
	 * Returns the user port remote service.
	 *
	 * @return the user port remote service
	 */
	public UserPortService getUserPortService() {
		return userPortService;
	}

	/**
	 * Sets the user port remote service.
	 *
	 * @param userPortService the user port remote service
	 */
	public void setUserPortService(UserPortService userPortService) {
		this.userPortService = userPortService;
	}

	/**
	 * Returns the user port persistence.
	 *
	 * @return the user port persistence
	 */
	public UserPortPersistence getUserPortPersistence() {
		return userPortPersistence;
	}

	/**
	 * Sets the user port persistence.
	 *
	 * @param userPortPersistence the user port persistence
	 */
	public void setUserPortPersistence(UserPortPersistence userPortPersistence) {
		this.userPortPersistence = userPortPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the resource remote service.
	 *
	 * @return the resource remote service
	 */
	public ResourceService getResourceService() {
		return resourceService;
	}

	/**
	 * Sets the resource remote service.
	 *
	 * @param resourceService the resource remote service
	 */
	public void setResourceService(ResourceService resourceService) {
		this.resourceService = resourceService;
	}

	/**
	 * Returns the resource persistence.
	 *
	 * @return the resource persistence
	 */
	public ResourcePersistence getResourcePersistence() {
		return resourcePersistence;
	}

	/**
	 * Sets the resource persistence.
	 *
	 * @param resourcePersistence the resource persistence
	 */
	public void setResourcePersistence(ResourcePersistence resourcePersistence) {
		this.resourcePersistence = resourcePersistence;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user remote service.
	 *
	 * @return the user remote service
	 */
	public UserService getUserService() {
		return userService;
	}

	/**
	 * Sets the user remote service.
	 *
	 * @param userService the user remote service
	 */
	public void setUserService(UserService userService) {
		this.userService = userService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
	}

	public void destroy() {
	}

	/**
	 * Returns the Spring bean ID for this bean.
	 *
	 * @return the Spring bean ID for this bean
	 */
	public String getBeanIdentifier() {
		return _beanIdentifier;
	}

	/**
	 * Sets the Spring bean ID for this bean.
	 *
	 * @param beanIdentifier the Spring bean ID for this bean
	 */
	public void setBeanIdentifier(String beanIdentifier) {
		_beanIdentifier = beanIdentifier;
	}

	protected Class<?> getModelClass() {
		return LogMessageValidation.class;
	}

	protected String getModelClassName() {
		return LogMessageValidation.class.getName();
	}

	/**
	 * Performs an SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) throws SystemException {
		try {
			DataSource dataSource = logMessageValidationPersistence.getDataSource();

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql, new int[0]);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = LogMessageValidationLocalService.class)
	protected LogMessageValidationLocalService logMessageValidationLocalService;
	@BeanReference(type = LogMessageValidationService.class)
	protected LogMessageValidationService logMessageValidationService;
	@BeanReference(type = LogMessageValidationPersistence.class)
	protected LogMessageValidationPersistence logMessageValidationPersistence;
	@BeanReference(type = UserPortLocalService.class)
	protected UserPortLocalService userPortLocalService;
	@BeanReference(type = UserPortService.class)
	protected UserPortService userPortService;
	@BeanReference(type = UserPortPersistence.class)
	protected UserPortPersistence userPortPersistence;
	@BeanReference(type = CounterLocalService.class)
	protected CounterLocalService counterLocalService;
	@BeanReference(type = ResourceLocalService.class)
	protected ResourceLocalService resourceLocalService;
	@BeanReference(type = ResourceService.class)
	protected ResourceService resourceService;
	@BeanReference(type = ResourcePersistence.class)
	protected ResourcePersistence resourcePersistence;
	@BeanReference(type = UserLocalService.class)
	protected UserLocalService userLocalService;
	@BeanReference(type = UserService.class)
	protected UserService userService;
	@BeanReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
	private String _beanIdentifier;
}