/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.gt.dao.common.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import vn.gt.dao.common.model.UserPort;
import vn.gt.dao.common.model.UserPortModel;
import vn.gt.dao.common.model.UserPortSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

/**
 * The base model implementation for the UserPort service. Represents a row in the &quot;user_port&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link vn.gt.dao.common.model.UserPortModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link UserPortImpl}.
 * </p>
 *
 * @author win_64
 * @see UserPortImpl
 * @see vn.gt.dao.common.model.UserPort
 * @see vn.gt.dao.common.model.UserPortModel
 * @generated
 */
@JSON(strict = true)
public class UserPortModelImpl extends BaseModelImpl<UserPort>
	implements UserPortModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a user port model instance should use the {@link vn.gt.dao.common.model.UserPort} interface instead.
	 */
	public static final String TABLE_NAME = "user_port";
	public static final Object[][] TABLE_COLUMNS = {
			{ "id", Types.BIGINT },
			{ "PortCode", Types.VARCHAR },
			{ "userid", Types.BIGINT },
			{ "createdate", Types.TIMESTAMP },
			{ "status", Types.INTEGER }
		};
	public static final String TABLE_SQL_CREATE = "create table user_port (id LONG not null primary key,PortCode VARCHAR(75) null,userid LONG,createdate DATE null,status INTEGER)";
	public static final String TABLE_SQL_DROP = "drop table user_port";
	public static final String ORDER_BY_JPQL = " ORDER BY userPort.id ASC";
	public static final String ORDER_BY_SQL = " ORDER BY user_port.id ASC";
	public static final String DATA_SOURCE = "gtDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.vn.gt.dao.common.model.UserPort"),
			false);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.vn.gt.dao.common.model.UserPort"),
			false);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.vn.gt.dao.common.model.UserPort"),
			true);
	public static long PORTCODE_COLUMN_BITMASK = 1L;
	public static long USERID_COLUMN_BITMASK = 2L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static UserPort toModel(UserPortSoap soapModel) {
		UserPort model = new UserPortImpl();

		model.setId(soapModel.getId());
		model.setPortCode(soapModel.getPortCode());
		model.setUserId(soapModel.getUserId());
		model.setCreateDate(soapModel.getCreateDate());
		model.setStatus(soapModel.getStatus());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<UserPort> toModels(UserPortSoap[] soapModels) {
		List<UserPort> models = new ArrayList<UserPort>(soapModels.length);

		for (UserPortSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.vn.gt.dao.common.model.UserPort"));

	public UserPortModelImpl() {
	}

	public long getPrimaryKey() {
		return _id;
	}

	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	public Serializable getPrimaryKeyObj() {
		return new Long(_id);
	}

	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	public Class<?> getModelClass() {
		return UserPort.class;
	}

	public String getModelClassName() {
		return UserPort.class.getName();
	}

	@JSON
	public long getId() {
		return _id;
	}

	public void setId(long id) {
		_columnBitmask = -1L;

		_id = id;
	}

	@JSON
	public String getPortCode() {
		if (_portCode == null) {
			return StringPool.BLANK;
		}
		else {
			return _portCode;
		}
	}

	public void setPortCode(String portCode) {
		_columnBitmask |= PORTCODE_COLUMN_BITMASK;

		if (_originalPortCode == null) {
			_originalPortCode = _portCode;
		}

		_portCode = portCode;
	}

	public String getOriginalPortCode() {
		return GetterUtil.getString(_originalPortCode);
	}

	@JSON
	public long getUserId() {
		return _userId;
	}

	public void setUserId(long userId) {
		_columnBitmask |= USERID_COLUMN_BITMASK;

		if (!_setOriginalUserId) {
			_setOriginalUserId = true;

			_originalUserId = _userId;
		}

		_userId = userId;
	}

	public String getUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
	}

	public void setUserUuid(String userUuid) {
		_userUuid = userUuid;
	}

	public long getOriginalUserId() {
		return _originalUserId;
	}

	@JSON
	public Date getCreateDate() {
		return _createDate;
	}

	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	public int getStatus() {
		return _status;
	}

	public void setStatus(int status) {
		_status = status;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public UserPort toEscapedModel() {
		if (_escapedModelProxy == null) {
			_escapedModelProxy = (UserPort)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelProxyInterfaces,
					new AutoEscapeBeanHandler(this));
		}

		return _escapedModelProxy;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		if (_expandoBridge == null) {
			_expandoBridge = ExpandoBridgeFactoryUtil.getExpandoBridge(0,
					UserPort.class.getName(), getPrimaryKey());
		}

		return _expandoBridge;
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		getExpandoBridge().setAttributes(serviceContext);
	}

	@Override
	public Object clone() {
		UserPortImpl userPortImpl = new UserPortImpl();

		userPortImpl.setId(getId());
		userPortImpl.setPortCode(getPortCode());
		userPortImpl.setUserId(getUserId());
		userPortImpl.setCreateDate(getCreateDate());
		userPortImpl.setStatus(getStatus());

		userPortImpl.resetOriginalValues();

		return userPortImpl;
	}

	public int compareTo(UserPort userPort) {
		int value = 0;

		if (getId() < userPort.getId()) {
			value = -1;
		}
		else if (getId() > userPort.getId()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		UserPort userPort = null;

		try {
			userPort = (UserPort)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		long primaryKey = userPort.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		UserPortModelImpl userPortModelImpl = this;

		userPortModelImpl._originalPortCode = userPortModelImpl._portCode;

		userPortModelImpl._originalUserId = userPortModelImpl._userId;

		userPortModelImpl._setOriginalUserId = false;

		userPortModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<UserPort> toCacheModel() {
		UserPortCacheModel userPortCacheModel = new UserPortCacheModel();

		userPortCacheModel.id = getId();

		userPortCacheModel.portCode = getPortCode();

		String portCode = userPortCacheModel.portCode;

		if ((portCode != null) && (portCode.length() == 0)) {
			userPortCacheModel.portCode = null;
		}

		userPortCacheModel.userId = getUserId();

		Date createDate = getCreateDate();

		if (createDate != null) {
			userPortCacheModel.createDate = createDate.getTime();
		}
		else {
			userPortCacheModel.createDate = Long.MIN_VALUE;
		}

		userPortCacheModel.status = getStatus();

		return userPortCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(11);

		sb.append("{id=");
		sb.append(getId());
		sb.append(", portCode=");
		sb.append(getPortCode());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", status=");
		sb.append(getStatus());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(19);

		sb.append("<model><model-name>");
		sb.append("vn.gt.dao.common.model.UserPort");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>id</column-name><column-value><![CDATA[");
		sb.append(getId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>portCode</column-name><column-value><![CDATA[");
		sb.append(getPortCode());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>status</column-name><column-value><![CDATA[");
		sb.append(getStatus());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = UserPort.class.getClassLoader();
	private static Class<?>[] _escapedModelProxyInterfaces = new Class[] {
			UserPort.class
		};
	private long _id;
	private String _portCode;
	private String _originalPortCode;
	private long _userId;
	private String _userUuid;
	private long _originalUserId;
	private boolean _setOriginalUserId;
	private Date _createDate;
	private int _status;
	private transient ExpandoBridge _expandoBridge;
	private long _columnBitmask;
	private UserPort _escapedModelProxy;
}