/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.gt.dao.noticeandmessage.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import vn.gt.dao.noticeandmessage.model.Modify;
import vn.gt.dao.noticeandmessage.model.ModifyModel;
import vn.gt.dao.noticeandmessage.model.ModifySoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

/**
 * The base model implementation for the Modify service. Represents a row in the &quot;gt_modify&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link vn.gt.dao.noticeandmessage.model.ModifyModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ModifyImpl}.
 * </p>
 *
 * @author win_64
 * @see ModifyImpl
 * @see vn.gt.dao.noticeandmessage.model.Modify
 * @see vn.gt.dao.noticeandmessage.model.ModifyModel
 * @generated
 */
@JSON(strict = true)
public class ModifyModelImpl extends BaseModelImpl<Modify>
	implements ModifyModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a modify model instance should use the {@link vn.gt.dao.noticeandmessage.model.Modify} interface instead.
	 */
	public static final String TABLE_NAME = "gt_modify";
	public static final Object[][] TABLE_COLUMNS = {
			{ "ID", Types.BIGINT },
			{ "modifycode", Types.VARCHAR },
			{ "modifydesc", Types.VARCHAR },
			{ "organization", Types.VARCHAR },
			{ "division", Types.VARCHAR },
			{ "name", Types.VARCHAR },
			{ "modifydate", Types.TIMESTAMP },
			{ "documentname", Types.BIGINT },
			{ "documentyear", Types.BIGINT }
		};
	public static final String TABLE_SQL_CREATE = "create table gt_modify (ID LONG not null primary key,modifycode VARCHAR(75) null,modifydesc VARCHAR(75) null,organization VARCHAR(75) null,division VARCHAR(75) null,name VARCHAR(75) null,modifydate DATE null,documentname LONG,documentyear LONG)";
	public static final String TABLE_SQL_DROP = "drop table gt_modify";
	public static final String ORDER_BY_JPQL = " ORDER BY modify.id ASC";
	public static final String ORDER_BY_SQL = " ORDER BY gt_modify.ID ASC";
	public static final String DATA_SOURCE = "gtDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.vn.gt.dao.noticeandmessage.model.Modify"),
			false);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.vn.gt.dao.noticeandmessage.model.Modify"),
			false);
	public static final boolean COLUMN_BITMASK_ENABLED = false;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static Modify toModel(ModifySoap soapModel) {
		Modify model = new ModifyImpl();

		model.setId(soapModel.getId());
		model.setModifyCode(soapModel.getModifyCode());
		model.setModifyDesc(soapModel.getModifyDesc());
		model.setOrganization(soapModel.getOrganization());
		model.setDivision(soapModel.getDivision());
		model.setName(soapModel.getName());
		model.setModifyDate(soapModel.getModifyDate());
		model.setDocumentName(soapModel.getDocumentName());
		model.setDocumentYear(soapModel.getDocumentYear());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<Modify> toModels(ModifySoap[] soapModels) {
		List<Modify> models = new ArrayList<Modify>(soapModels.length);

		for (ModifySoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.vn.gt.dao.noticeandmessage.model.Modify"));

	public ModifyModelImpl() {
	}

	public long getPrimaryKey() {
		return _id;
	}

	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	public Serializable getPrimaryKeyObj() {
		return new Long(_id);
	}

	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	public Class<?> getModelClass() {
		return Modify.class;
	}

	public String getModelClassName() {
		return Modify.class.getName();
	}

	@JSON
	public long getId() {
		return _id;
	}

	public void setId(long id) {
		_id = id;
	}

	@JSON
	public String getModifyCode() {
		if (_modifyCode == null) {
			return StringPool.BLANK;
		}
		else {
			return _modifyCode;
		}
	}

	public void setModifyCode(String modifyCode) {
		_modifyCode = modifyCode;
	}

	@JSON
	public String getModifyDesc() {
		if (_modifyDesc == null) {
			return StringPool.BLANK;
		}
		else {
			return _modifyDesc;
		}
	}

	public void setModifyDesc(String modifyDesc) {
		_modifyDesc = modifyDesc;
	}

	@JSON
	public String getOrganization() {
		if (_organization == null) {
			return StringPool.BLANK;
		}
		else {
			return _organization;
		}
	}

	public void setOrganization(String organization) {
		_organization = organization;
	}

	@JSON
	public String getDivision() {
		if (_division == null) {
			return StringPool.BLANK;
		}
		else {
			return _division;
		}
	}

	public void setDivision(String division) {
		_division = division;
	}

	@JSON
	public String getName() {
		if (_name == null) {
			return StringPool.BLANK;
		}
		else {
			return _name;
		}
	}

	public void setName(String name) {
		_name = name;
	}

	@JSON
	public Date getModifyDate() {
		return _modifyDate;
	}

	public void setModifyDate(Date modifyDate) {
		_modifyDate = modifyDate;
	}

	@JSON
	public long getDocumentName() {
		return _documentName;
	}

	public void setDocumentName(long documentName) {
		_documentName = documentName;
	}

	@JSON
	public long getDocumentYear() {
		return _documentYear;
	}

	public void setDocumentYear(long documentYear) {
		_documentYear = documentYear;
	}

	@Override
	public Modify toEscapedModel() {
		if (_escapedModelProxy == null) {
			_escapedModelProxy = (Modify)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelProxyInterfaces,
					new AutoEscapeBeanHandler(this));
		}

		return _escapedModelProxy;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		if (_expandoBridge == null) {
			_expandoBridge = ExpandoBridgeFactoryUtil.getExpandoBridge(0,
					Modify.class.getName(), getPrimaryKey());
		}

		return _expandoBridge;
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		getExpandoBridge().setAttributes(serviceContext);
	}

	@Override
	public Object clone() {
		ModifyImpl modifyImpl = new ModifyImpl();

		modifyImpl.setId(getId());
		modifyImpl.setModifyCode(getModifyCode());
		modifyImpl.setModifyDesc(getModifyDesc());
		modifyImpl.setOrganization(getOrganization());
		modifyImpl.setDivision(getDivision());
		modifyImpl.setName(getName());
		modifyImpl.setModifyDate(getModifyDate());
		modifyImpl.setDocumentName(getDocumentName());
		modifyImpl.setDocumentYear(getDocumentYear());

		modifyImpl.resetOriginalValues();

		return modifyImpl;
	}

	public int compareTo(Modify modify) {
		int value = 0;

		if (getId() < modify.getId()) {
			value = -1;
		}
		else if (getId() > modify.getId()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		Modify modify = null;

		try {
			modify = (Modify)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		long primaryKey = modify.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<Modify> toCacheModel() {
		ModifyCacheModel modifyCacheModel = new ModifyCacheModel();

		modifyCacheModel.id = getId();

		modifyCacheModel.modifyCode = getModifyCode();

		String modifyCode = modifyCacheModel.modifyCode;

		if ((modifyCode != null) && (modifyCode.length() == 0)) {
			modifyCacheModel.modifyCode = null;
		}

		modifyCacheModel.modifyDesc = getModifyDesc();

		String modifyDesc = modifyCacheModel.modifyDesc;

		if ((modifyDesc != null) && (modifyDesc.length() == 0)) {
			modifyCacheModel.modifyDesc = null;
		}

		modifyCacheModel.organization = getOrganization();

		String organization = modifyCacheModel.organization;

		if ((organization != null) && (organization.length() == 0)) {
			modifyCacheModel.organization = null;
		}

		modifyCacheModel.division = getDivision();

		String division = modifyCacheModel.division;

		if ((division != null) && (division.length() == 0)) {
			modifyCacheModel.division = null;
		}

		modifyCacheModel.name = getName();

		String name = modifyCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			modifyCacheModel.name = null;
		}

		Date modifyDate = getModifyDate();

		if (modifyDate != null) {
			modifyCacheModel.modifyDate = modifyDate.getTime();
		}
		else {
			modifyCacheModel.modifyDate = Long.MIN_VALUE;
		}

		modifyCacheModel.documentName = getDocumentName();

		modifyCacheModel.documentYear = getDocumentYear();

		return modifyCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(19);

		sb.append("{id=");
		sb.append(getId());
		sb.append(", modifyCode=");
		sb.append(getModifyCode());
		sb.append(", modifyDesc=");
		sb.append(getModifyDesc());
		sb.append(", organization=");
		sb.append(getOrganization());
		sb.append(", division=");
		sb.append(getDivision());
		sb.append(", name=");
		sb.append(getName());
		sb.append(", modifyDate=");
		sb.append(getModifyDate());
		sb.append(", documentName=");
		sb.append(getDocumentName());
		sb.append(", documentYear=");
		sb.append(getDocumentYear());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(31);

		sb.append("<model><model-name>");
		sb.append("vn.gt.dao.noticeandmessage.model.Modify");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>id</column-name><column-value><![CDATA[");
		sb.append(getId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifyCode</column-name><column-value><![CDATA[");
		sb.append(getModifyCode());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifyDesc</column-name><column-value><![CDATA[");
		sb.append(getModifyDesc());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>organization</column-name><column-value><![CDATA[");
		sb.append(getOrganization());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>division</column-name><column-value><![CDATA[");
		sb.append(getDivision());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>name</column-name><column-value><![CDATA[");
		sb.append(getName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifyDate</column-name><column-value><![CDATA[");
		sb.append(getModifyDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>documentName</column-name><column-value><![CDATA[");
		sb.append(getDocumentName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>documentYear</column-name><column-value><![CDATA[");
		sb.append(getDocumentYear());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = Modify.class.getClassLoader();
	private static Class<?>[] _escapedModelProxyInterfaces = new Class[] {
			Modify.class
		};
	private long _id;
	private String _modifyCode;
	private String _modifyDesc;
	private String _organization;
	private String _division;
	private String _name;
	private Date _modifyDate;
	private long _documentName;
	private long _documentYear;
	private transient ExpandoBridge _expandoBridge;
	private Modify _escapedModelProxy;
}