/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.gt.dao.noticeandmessage.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import vn.gt.dao.noticeandmessage.model.TempCargoDeclaration;
import vn.gt.dao.noticeandmessage.model.TempCargoDeclarationModel;
import vn.gt.dao.noticeandmessage.model.TempCargoDeclarationSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

/**
 * The base model implementation for the TempCargoDeclaration service. Represents a row in the &quot;TEMP_CARGO_DECLARATION&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link vn.gt.dao.noticeandmessage.model.TempCargoDeclarationModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link TempCargoDeclarationImpl}.
 * </p>
 *
 * @author win_64
 * @see TempCargoDeclarationImpl
 * @see vn.gt.dao.noticeandmessage.model.TempCargoDeclaration
 * @see vn.gt.dao.noticeandmessage.model.TempCargoDeclarationModel
 * @generated
 */
@JSON(strict = true)
public class TempCargoDeclarationModelImpl extends BaseModelImpl<TempCargoDeclaration>
	implements TempCargoDeclarationModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a temp cargo declaration model instance should use the {@link vn.gt.dao.noticeandmessage.model.TempCargoDeclaration} interface instead.
	 */
	public static final String TABLE_NAME = "TEMP_CARGO_DECLARATION";
	public static final Object[][] TABLE_COLUMNS = {
			{ "ID", Types.BIGINT },
			{ "RequestCode", Types.VARCHAR },
			{ "RequestState", Types.INTEGER },
			{ "DocumentName", Types.BIGINT },
			{ "UserCreated", Types.VARCHAR },
			{ "isArrival", Types.INTEGER },
			{ "NameOfShip", Types.VARCHAR },
			{ "IMONumber", Types.VARCHAR },
			{ "Callsign", Types.VARCHAR },
			{ "VoyageNumber", Types.VARCHAR },
			{ "PortReport", Types.VARCHAR },
			{ "FlagStateOfShip", Types.VARCHAR },
			{ "NameOfMaster", Types.VARCHAR },
			{ "PortOfLoading", Types.VARCHAR },
			{ "ListGoods", Types.INTEGER },
			{ "SignPlace", Types.VARCHAR },
			{ "SignDate", Types.TIMESTAMP },
			{ "MasterSigned", Types.INTEGER },
			{ "MasterSignedImage", Types.INTEGER },
			{ "AttachedFile", Types.BIGINT },
			{ "DocumentYear", Types.INTEGER }
		};
	public static final String TABLE_SQL_CREATE = "create table TEMP_CARGO_DECLARATION (ID LONG not null primary key,RequestCode VARCHAR(75) null,RequestState INTEGER,DocumentName LONG,UserCreated VARCHAR(75) null,isArrival INTEGER,NameOfShip VARCHAR(75) null,IMONumber VARCHAR(75) null,Callsign VARCHAR(75) null,VoyageNumber VARCHAR(75) null,PortReport VARCHAR(75) null,FlagStateOfShip VARCHAR(75) null,NameOfMaster VARCHAR(75) null,PortOfLoading VARCHAR(75) null,ListGoods INTEGER,SignPlace VARCHAR(75) null,SignDate DATE null,MasterSigned INTEGER,MasterSignedImage INTEGER,AttachedFile LONG,DocumentYear INTEGER)";
	public static final String TABLE_SQL_DROP = "drop table TEMP_CARGO_DECLARATION";
	public static final String ORDER_BY_JPQL = " ORDER BY tempCargoDeclaration.id ASC";
	public static final String ORDER_BY_SQL = " ORDER BY TEMP_CARGO_DECLARATION.ID ASC";
	public static final String DATA_SOURCE = "gtDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.vn.gt.dao.noticeandmessage.model.TempCargoDeclaration"),
			false);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.vn.gt.dao.noticeandmessage.model.TempCargoDeclaration"),
			false);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.vn.gt.dao.noticeandmessage.model.TempCargoDeclaration"),
			true);
	public static long DOCUMENTNAME_COLUMN_BITMASK = 1L;
	public static long DOCUMENTYEAR_COLUMN_BITMASK = 2L;
	public static long REQUESTCODE_COLUMN_BITMASK = 4L;
	public static long REQUESTSTATE_COLUMN_BITMASK = 8L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static TempCargoDeclaration toModel(
		TempCargoDeclarationSoap soapModel) {
		TempCargoDeclaration model = new TempCargoDeclarationImpl();

		model.setId(soapModel.getId());
		model.setRequestCode(soapModel.getRequestCode());
		model.setRequestState(soapModel.getRequestState());
		model.setDocumentName(soapModel.getDocumentName());
		model.setUserCreated(soapModel.getUserCreated());
		model.setIsArrival(soapModel.getIsArrival());
		model.setNameOfShip(soapModel.getNameOfShip());
		model.setImoNumber(soapModel.getImoNumber());
		model.setCallsign(soapModel.getCallsign());
		model.setVoyageNumber(soapModel.getVoyageNumber());
		model.setPortReport(soapModel.getPortReport());
		model.setFlagStateOfShip(soapModel.getFlagStateOfShip());
		model.setNameOfMaster(soapModel.getNameOfMaster());
		model.setPortOfLoading(soapModel.getPortOfLoading());
		model.setListGoods(soapModel.getListGoods());
		model.setSignPlace(soapModel.getSignPlace());
		model.setSignDate(soapModel.getSignDate());
		model.setMasterSigned(soapModel.getMasterSigned());
		model.setMasterSignedImage(soapModel.getMasterSignedImage());
		model.setAttachedFile(soapModel.getAttachedFile());
		model.setDocumentYear(soapModel.getDocumentYear());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<TempCargoDeclaration> toModels(
		TempCargoDeclarationSoap[] soapModels) {
		List<TempCargoDeclaration> models = new ArrayList<TempCargoDeclaration>(soapModels.length);

		for (TempCargoDeclarationSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.vn.gt.dao.noticeandmessage.model.TempCargoDeclaration"));

	public TempCargoDeclarationModelImpl() {
	}

	public long getPrimaryKey() {
		return _id;
	}

	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	public Serializable getPrimaryKeyObj() {
		return new Long(_id);
	}

	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	public Class<?> getModelClass() {
		return TempCargoDeclaration.class;
	}

	public String getModelClassName() {
		return TempCargoDeclaration.class.getName();
	}

	@JSON
	public long getId() {
		return _id;
	}

	public void setId(long id) {
		_columnBitmask = -1L;

		_id = id;
	}

	@JSON
	public String getRequestCode() {
		if (_requestCode == null) {
			return StringPool.BLANK;
		}
		else {
			return _requestCode;
		}
	}

	public void setRequestCode(String requestCode) {
		_columnBitmask |= REQUESTCODE_COLUMN_BITMASK;

		if (_originalRequestCode == null) {
			_originalRequestCode = _requestCode;
		}

		_requestCode = requestCode;
	}

	public String getOriginalRequestCode() {
		return GetterUtil.getString(_originalRequestCode);
	}

	@JSON
	public int getRequestState() {
		return _requestState;
	}

	public void setRequestState(int requestState) {
		_columnBitmask |= REQUESTSTATE_COLUMN_BITMASK;

		if (!_setOriginalRequestState) {
			_setOriginalRequestState = true;

			_originalRequestState = _requestState;
		}

		_requestState = requestState;
	}

	public int getOriginalRequestState() {
		return _originalRequestState;
	}

	@JSON
	public long getDocumentName() {
		return _documentName;
	}

	public void setDocumentName(long documentName) {
		_columnBitmask |= DOCUMENTNAME_COLUMN_BITMASK;

		if (!_setOriginalDocumentName) {
			_setOriginalDocumentName = true;

			_originalDocumentName = _documentName;
		}

		_documentName = documentName;
	}

	public long getOriginalDocumentName() {
		return _originalDocumentName;
	}

	@JSON
	public String getUserCreated() {
		if (_userCreated == null) {
			return StringPool.BLANK;
		}
		else {
			return _userCreated;
		}
	}

	public void setUserCreated(String userCreated) {
		_userCreated = userCreated;
	}

	@JSON
	public int getIsArrival() {
		return _isArrival;
	}

	public void setIsArrival(int isArrival) {
		_isArrival = isArrival;
	}

	@JSON
	public String getNameOfShip() {
		if (_nameOfShip == null) {
			return StringPool.BLANK;
		}
		else {
			return _nameOfShip;
		}
	}

	public void setNameOfShip(String nameOfShip) {
		_nameOfShip = nameOfShip;
	}

	@JSON
	public String getImoNumber() {
		if (_imoNumber == null) {
			return StringPool.BLANK;
		}
		else {
			return _imoNumber;
		}
	}

	public void setImoNumber(String imoNumber) {
		_imoNumber = imoNumber;
	}

	@JSON
	public String getCallsign() {
		if (_callsign == null) {
			return StringPool.BLANK;
		}
		else {
			return _callsign;
		}
	}

	public void setCallsign(String callsign) {
		_callsign = callsign;
	}

	@JSON
	public String getVoyageNumber() {
		if (_voyageNumber == null) {
			return StringPool.BLANK;
		}
		else {
			return _voyageNumber;
		}
	}

	public void setVoyageNumber(String voyageNumber) {
		_voyageNumber = voyageNumber;
	}

	@JSON
	public String getPortReport() {
		if (_portReport == null) {
			return StringPool.BLANK;
		}
		else {
			return _portReport;
		}
	}

	public void setPortReport(String portReport) {
		_portReport = portReport;
	}

	@JSON
	public String getFlagStateOfShip() {
		if (_flagStateOfShip == null) {
			return StringPool.BLANK;
		}
		else {
			return _flagStateOfShip;
		}
	}

	public void setFlagStateOfShip(String flagStateOfShip) {
		_flagStateOfShip = flagStateOfShip;
	}

	@JSON
	public String getNameOfMaster() {
		if (_nameOfMaster == null) {
			return StringPool.BLANK;
		}
		else {
			return _nameOfMaster;
		}
	}

	public void setNameOfMaster(String nameOfMaster) {
		_nameOfMaster = nameOfMaster;
	}

	@JSON
	public String getPortOfLoading() {
		if (_portOfLoading == null) {
			return StringPool.BLANK;
		}
		else {
			return _portOfLoading;
		}
	}

	public void setPortOfLoading(String portOfLoading) {
		_portOfLoading = portOfLoading;
	}

	@JSON
	public int getListGoods() {
		return _listGoods;
	}

	public void setListGoods(int listGoods) {
		_listGoods = listGoods;
	}

	@JSON
	public String getSignPlace() {
		if (_signPlace == null) {
			return StringPool.BLANK;
		}
		else {
			return _signPlace;
		}
	}

	public void setSignPlace(String signPlace) {
		_signPlace = signPlace;
	}

	@JSON
	public Date getSignDate() {
		return _signDate;
	}

	public void setSignDate(Date signDate) {
		_signDate = signDate;
	}

	@JSON
	public int getMasterSigned() {
		return _masterSigned;
	}

	public void setMasterSigned(int masterSigned) {
		_masterSigned = masterSigned;
	}

	@JSON
	public int getMasterSignedImage() {
		return _masterSignedImage;
	}

	public void setMasterSignedImage(int masterSignedImage) {
		_masterSignedImage = masterSignedImage;
	}

	@JSON
	public long getAttachedFile() {
		return _attachedFile;
	}

	public void setAttachedFile(long attachedFile) {
		_attachedFile = attachedFile;
	}

	@JSON
	public int getDocumentYear() {
		return _documentYear;
	}

	public void setDocumentYear(int documentYear) {
		_columnBitmask |= DOCUMENTYEAR_COLUMN_BITMASK;

		if (!_setOriginalDocumentYear) {
			_setOriginalDocumentYear = true;

			_originalDocumentYear = _documentYear;
		}

		_documentYear = documentYear;
	}

	public int getOriginalDocumentYear() {
		return _originalDocumentYear;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public TempCargoDeclaration toEscapedModel() {
		if (_escapedModelProxy == null) {
			_escapedModelProxy = (TempCargoDeclaration)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelProxyInterfaces,
					new AutoEscapeBeanHandler(this));
		}

		return _escapedModelProxy;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		if (_expandoBridge == null) {
			_expandoBridge = ExpandoBridgeFactoryUtil.getExpandoBridge(0,
					TempCargoDeclaration.class.getName(), getPrimaryKey());
		}

		return _expandoBridge;
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		getExpandoBridge().setAttributes(serviceContext);
	}

	@Override
	public Object clone() {
		TempCargoDeclarationImpl tempCargoDeclarationImpl = new TempCargoDeclarationImpl();

		tempCargoDeclarationImpl.setId(getId());
		tempCargoDeclarationImpl.setRequestCode(getRequestCode());
		tempCargoDeclarationImpl.setRequestState(getRequestState());
		tempCargoDeclarationImpl.setDocumentName(getDocumentName());
		tempCargoDeclarationImpl.setUserCreated(getUserCreated());
		tempCargoDeclarationImpl.setIsArrival(getIsArrival());
		tempCargoDeclarationImpl.setNameOfShip(getNameOfShip());
		tempCargoDeclarationImpl.setImoNumber(getImoNumber());
		tempCargoDeclarationImpl.setCallsign(getCallsign());
		tempCargoDeclarationImpl.setVoyageNumber(getVoyageNumber());
		tempCargoDeclarationImpl.setPortReport(getPortReport());
		tempCargoDeclarationImpl.setFlagStateOfShip(getFlagStateOfShip());
		tempCargoDeclarationImpl.setNameOfMaster(getNameOfMaster());
		tempCargoDeclarationImpl.setPortOfLoading(getPortOfLoading());
		tempCargoDeclarationImpl.setListGoods(getListGoods());
		tempCargoDeclarationImpl.setSignPlace(getSignPlace());
		tempCargoDeclarationImpl.setSignDate(getSignDate());
		tempCargoDeclarationImpl.setMasterSigned(getMasterSigned());
		tempCargoDeclarationImpl.setMasterSignedImage(getMasterSignedImage());
		tempCargoDeclarationImpl.setAttachedFile(getAttachedFile());
		tempCargoDeclarationImpl.setDocumentYear(getDocumentYear());

		tempCargoDeclarationImpl.resetOriginalValues();

		return tempCargoDeclarationImpl;
	}

	public int compareTo(TempCargoDeclaration tempCargoDeclaration) {
		int value = 0;

		if (getId() < tempCargoDeclaration.getId()) {
			value = -1;
		}
		else if (getId() > tempCargoDeclaration.getId()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		TempCargoDeclaration tempCargoDeclaration = null;

		try {
			tempCargoDeclaration = (TempCargoDeclaration)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		long primaryKey = tempCargoDeclaration.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		TempCargoDeclarationModelImpl tempCargoDeclarationModelImpl = this;

		tempCargoDeclarationModelImpl._originalRequestCode = tempCargoDeclarationModelImpl._requestCode;

		tempCargoDeclarationModelImpl._originalRequestState = tempCargoDeclarationModelImpl._requestState;

		tempCargoDeclarationModelImpl._setOriginalRequestState = false;

		tempCargoDeclarationModelImpl._originalDocumentName = tempCargoDeclarationModelImpl._documentName;

		tempCargoDeclarationModelImpl._setOriginalDocumentName = false;

		tempCargoDeclarationModelImpl._originalDocumentYear = tempCargoDeclarationModelImpl._documentYear;

		tempCargoDeclarationModelImpl._setOriginalDocumentYear = false;

		tempCargoDeclarationModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<TempCargoDeclaration> toCacheModel() {
		TempCargoDeclarationCacheModel tempCargoDeclarationCacheModel = new TempCargoDeclarationCacheModel();

		tempCargoDeclarationCacheModel.id = getId();

		tempCargoDeclarationCacheModel.requestCode = getRequestCode();

		String requestCode = tempCargoDeclarationCacheModel.requestCode;

		if ((requestCode != null) && (requestCode.length() == 0)) {
			tempCargoDeclarationCacheModel.requestCode = null;
		}

		tempCargoDeclarationCacheModel.requestState = getRequestState();

		tempCargoDeclarationCacheModel.documentName = getDocumentName();

		tempCargoDeclarationCacheModel.userCreated = getUserCreated();

		String userCreated = tempCargoDeclarationCacheModel.userCreated;

		if ((userCreated != null) && (userCreated.length() == 0)) {
			tempCargoDeclarationCacheModel.userCreated = null;
		}

		tempCargoDeclarationCacheModel.isArrival = getIsArrival();

		tempCargoDeclarationCacheModel.nameOfShip = getNameOfShip();

		String nameOfShip = tempCargoDeclarationCacheModel.nameOfShip;

		if ((nameOfShip != null) && (nameOfShip.length() == 0)) {
			tempCargoDeclarationCacheModel.nameOfShip = null;
		}

		tempCargoDeclarationCacheModel.imoNumber = getImoNumber();

		String imoNumber = tempCargoDeclarationCacheModel.imoNumber;

		if ((imoNumber != null) && (imoNumber.length() == 0)) {
			tempCargoDeclarationCacheModel.imoNumber = null;
		}

		tempCargoDeclarationCacheModel.callsign = getCallsign();

		String callsign = tempCargoDeclarationCacheModel.callsign;

		if ((callsign != null) && (callsign.length() == 0)) {
			tempCargoDeclarationCacheModel.callsign = null;
		}

		tempCargoDeclarationCacheModel.voyageNumber = getVoyageNumber();

		String voyageNumber = tempCargoDeclarationCacheModel.voyageNumber;

		if ((voyageNumber != null) && (voyageNumber.length() == 0)) {
			tempCargoDeclarationCacheModel.voyageNumber = null;
		}

		tempCargoDeclarationCacheModel.portReport = getPortReport();

		String portReport = tempCargoDeclarationCacheModel.portReport;

		if ((portReport != null) && (portReport.length() == 0)) {
			tempCargoDeclarationCacheModel.portReport = null;
		}

		tempCargoDeclarationCacheModel.flagStateOfShip = getFlagStateOfShip();

		String flagStateOfShip = tempCargoDeclarationCacheModel.flagStateOfShip;

		if ((flagStateOfShip != null) && (flagStateOfShip.length() == 0)) {
			tempCargoDeclarationCacheModel.flagStateOfShip = null;
		}

		tempCargoDeclarationCacheModel.nameOfMaster = getNameOfMaster();

		String nameOfMaster = tempCargoDeclarationCacheModel.nameOfMaster;

		if ((nameOfMaster != null) && (nameOfMaster.length() == 0)) {
			tempCargoDeclarationCacheModel.nameOfMaster = null;
		}

		tempCargoDeclarationCacheModel.portOfLoading = getPortOfLoading();

		String portOfLoading = tempCargoDeclarationCacheModel.portOfLoading;

		if ((portOfLoading != null) && (portOfLoading.length() == 0)) {
			tempCargoDeclarationCacheModel.portOfLoading = null;
		}

		tempCargoDeclarationCacheModel.listGoods = getListGoods();

		tempCargoDeclarationCacheModel.signPlace = getSignPlace();

		String signPlace = tempCargoDeclarationCacheModel.signPlace;

		if ((signPlace != null) && (signPlace.length() == 0)) {
			tempCargoDeclarationCacheModel.signPlace = null;
		}

		Date signDate = getSignDate();

		if (signDate != null) {
			tempCargoDeclarationCacheModel.signDate = signDate.getTime();
		}
		else {
			tempCargoDeclarationCacheModel.signDate = Long.MIN_VALUE;
		}

		tempCargoDeclarationCacheModel.masterSigned = getMasterSigned();

		tempCargoDeclarationCacheModel.masterSignedImage = getMasterSignedImage();

		tempCargoDeclarationCacheModel.attachedFile = getAttachedFile();

		tempCargoDeclarationCacheModel.documentYear = getDocumentYear();

		return tempCargoDeclarationCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(43);

		sb.append("{id=");
		sb.append(getId());
		sb.append(", requestCode=");
		sb.append(getRequestCode());
		sb.append(", requestState=");
		sb.append(getRequestState());
		sb.append(", documentName=");
		sb.append(getDocumentName());
		sb.append(", userCreated=");
		sb.append(getUserCreated());
		sb.append(", isArrival=");
		sb.append(getIsArrival());
		sb.append(", nameOfShip=");
		sb.append(getNameOfShip());
		sb.append(", imoNumber=");
		sb.append(getImoNumber());
		sb.append(", callsign=");
		sb.append(getCallsign());
		sb.append(", voyageNumber=");
		sb.append(getVoyageNumber());
		sb.append(", portReport=");
		sb.append(getPortReport());
		sb.append(", flagStateOfShip=");
		sb.append(getFlagStateOfShip());
		sb.append(", nameOfMaster=");
		sb.append(getNameOfMaster());
		sb.append(", portOfLoading=");
		sb.append(getPortOfLoading());
		sb.append(", listGoods=");
		sb.append(getListGoods());
		sb.append(", signPlace=");
		sb.append(getSignPlace());
		sb.append(", signDate=");
		sb.append(getSignDate());
		sb.append(", masterSigned=");
		sb.append(getMasterSigned());
		sb.append(", masterSignedImage=");
		sb.append(getMasterSignedImage());
		sb.append(", attachedFile=");
		sb.append(getAttachedFile());
		sb.append(", documentYear=");
		sb.append(getDocumentYear());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(67);

		sb.append("<model><model-name>");
		sb.append("vn.gt.dao.noticeandmessage.model.TempCargoDeclaration");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>id</column-name><column-value><![CDATA[");
		sb.append(getId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>requestCode</column-name><column-value><![CDATA[");
		sb.append(getRequestCode());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>requestState</column-name><column-value><![CDATA[");
		sb.append(getRequestState());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>documentName</column-name><column-value><![CDATA[");
		sb.append(getDocumentName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userCreated</column-name><column-value><![CDATA[");
		sb.append(getUserCreated());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>isArrival</column-name><column-value><![CDATA[");
		sb.append(getIsArrival());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>nameOfShip</column-name><column-value><![CDATA[");
		sb.append(getNameOfShip());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>imoNumber</column-name><column-value><![CDATA[");
		sb.append(getImoNumber());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>callsign</column-name><column-value><![CDATA[");
		sb.append(getCallsign());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>voyageNumber</column-name><column-value><![CDATA[");
		sb.append(getVoyageNumber());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>portReport</column-name><column-value><![CDATA[");
		sb.append(getPortReport());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>flagStateOfShip</column-name><column-value><![CDATA[");
		sb.append(getFlagStateOfShip());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>nameOfMaster</column-name><column-value><![CDATA[");
		sb.append(getNameOfMaster());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>portOfLoading</column-name><column-value><![CDATA[");
		sb.append(getPortOfLoading());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>listGoods</column-name><column-value><![CDATA[");
		sb.append(getListGoods());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>signPlace</column-name><column-value><![CDATA[");
		sb.append(getSignPlace());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>signDate</column-name><column-value><![CDATA[");
		sb.append(getSignDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>masterSigned</column-name><column-value><![CDATA[");
		sb.append(getMasterSigned());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>masterSignedImage</column-name><column-value><![CDATA[");
		sb.append(getMasterSignedImage());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>attachedFile</column-name><column-value><![CDATA[");
		sb.append(getAttachedFile());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>documentYear</column-name><column-value><![CDATA[");
		sb.append(getDocumentYear());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = TempCargoDeclaration.class.getClassLoader();
	private static Class<?>[] _escapedModelProxyInterfaces = new Class[] {
			TempCargoDeclaration.class
		};
	private long _id;
	private String _requestCode;
	private String _originalRequestCode;
	private int _requestState;
	private int _originalRequestState;
	private boolean _setOriginalRequestState;
	private long _documentName;
	private long _originalDocumentName;
	private boolean _setOriginalDocumentName;
	private String _userCreated;
	private int _isArrival;
	private String _nameOfShip;
	private String _imoNumber;
	private String _callsign;
	private String _voyageNumber;
	private String _portReport;
	private String _flagStateOfShip;
	private String _nameOfMaster;
	private String _portOfLoading;
	private int _listGoods;
	private String _signPlace;
	private Date _signDate;
	private int _masterSigned;
	private int _masterSignedImage;
	private long _attachedFile;
	private int _documentYear;
	private int _originalDocumentYear;
	private boolean _setOriginalDocumentYear;
	private transient ExpandoBridge _expandoBridge;
	private long _columnBitmask;
	private TempCargoDeclaration _escapedModelProxy;
}