/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.gt.dao.noticeandmessage.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import vn.gt.dao.noticeandmessage.model.TempDocument;
import vn.gt.dao.noticeandmessage.model.TempDocumentModel;
import vn.gt.dao.noticeandmessage.model.TempDocumentSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

/**
 * The base model implementation for the TempDocument service. Represents a row in the &quot;TEMP_DOCUMENT&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link vn.gt.dao.noticeandmessage.model.TempDocumentModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link TempDocumentImpl}.
 * </p>
 *
 * @author win_64
 * @see TempDocumentImpl
 * @see vn.gt.dao.noticeandmessage.model.TempDocument
 * @see vn.gt.dao.noticeandmessage.model.TempDocumentModel
 * @generated
 */
@JSON(strict = true)
public class TempDocumentModelImpl extends BaseModelImpl<TempDocument>
	implements TempDocumentModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a temp document model instance should use the {@link vn.gt.dao.noticeandmessage.model.TempDocument} interface instead.
	 */
	public static final String TABLE_NAME = "TEMP_DOCUMENT";
	public static final Object[][] TABLE_COLUMNS = {
			{ "ID", Types.BIGINT },
			{ "RequestCode", Types.VARCHAR },
			{ "RequestState", Types.INTEGER },
			{ "DocumentName", Types.BIGINT },
			{ "DocumentYear", Types.INTEGER },
			{ "DocumentTypeCode", Types.VARCHAR },
			{ "UserCreated", Types.VARCHAR },
			{ "ShipAgencyCode", Types.VARCHAR },
			{ "ShipName", Types.VARCHAR },
			{ "ShipTypeCode", Types.VARCHAR },
			{ "StateCode", Types.VARCHAR },
			{ "ShipCaptain", Types.VARCHAR },
			{ "IMO", Types.VARCHAR },
			{ "GRT", Types.DOUBLE },
			{ "NT", Types.DOUBLE },
			{ "DWT", Types.DOUBLE },
			{ "UnitGRT", Types.VARCHAR },
			{ "UnitNT", Types.VARCHAR },
			{ "UnitDWT", Types.VARCHAR },
			{ "CallSign", Types.VARCHAR },
			{ "PreDocumentName", Types.VARCHAR },
			{ "CreatedDate", Types.TIMESTAMP },
			{ "LastModifiedDate", Types.TIMESTAMP },
			{ "FlowFlag", Types.INTEGER },
			{ "DocumentStatusCode", Types.INTEGER },
			{ "LocationCode", Types.VARCHAR },
			{ "MaritimeCode", Types.VARCHAR },
			{ "PortRegionCode", Types.VARCHAR },
			{ "PortCode", Types.VARCHAR },
			{ "LastPortCode", Types.VARCHAR },
			{ "ShipPosition", Types.INTEGER },
			{ "ShipOwnerCode", Types.VARCHAR },
			{ "ArrivalShipAgency", Types.VARCHAR },
			{ "DepartureShipAgency", Types.VARCHAR },
			{ "ShipDateFrom", Types.TIMESTAMP },
			{ "ShipDateTo", Types.TIMESTAMP }
		};
	public static final String TABLE_SQL_CREATE = "create table TEMP_DOCUMENT (ID LONG not null primary key,RequestCode VARCHAR(75) null,RequestState INTEGER,DocumentName LONG,DocumentYear INTEGER,DocumentTypeCode VARCHAR(75) null,UserCreated VARCHAR(75) null,ShipAgencyCode VARCHAR(75) null,ShipName VARCHAR(75) null,ShipTypeCode VARCHAR(75) null,StateCode VARCHAR(75) null,ShipCaptain VARCHAR(75) null,IMO VARCHAR(75) null,GRT DOUBLE,NT DOUBLE,DWT DOUBLE,UnitGRT VARCHAR(75) null,UnitNT VARCHAR(75) null,UnitDWT VARCHAR(75) null,CallSign VARCHAR(75) null,PreDocumentName VARCHAR(75) null,CreatedDate DATE null,LastModifiedDate DATE null,FlowFlag INTEGER,DocumentStatusCode INTEGER,LocationCode VARCHAR(75) null,MaritimeCode VARCHAR(75) null,PortRegionCode VARCHAR(75) null,PortCode VARCHAR(75) null,LastPortCode VARCHAR(75) null,ShipPosition INTEGER,ShipOwnerCode VARCHAR(75) null,ArrivalShipAgency VARCHAR(75) null,DepartureShipAgency VARCHAR(75) null,ShipDateFrom DATE null,ShipDateTo DATE null)";
	public static final String TABLE_SQL_DROP = "drop table TEMP_DOCUMENT";
	public static final String ORDER_BY_JPQL = " ORDER BY tempDocument.id ASC";
	public static final String ORDER_BY_SQL = " ORDER BY TEMP_DOCUMENT.ID ASC";
	public static final String DATA_SOURCE = "gtDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.vn.gt.dao.noticeandmessage.model.TempDocument"),
			false);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.vn.gt.dao.noticeandmessage.model.TempDocument"),
			false);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.vn.gt.dao.noticeandmessage.model.TempDocument"),
			true);
	public static long DOCUMENTNAME_COLUMN_BITMASK = 1L;
	public static long DOCUMENTYEAR_COLUMN_BITMASK = 2L;
	public static long REQUESTCODE_COLUMN_BITMASK = 4L;
	public static long REQUESTSTATE_COLUMN_BITMASK = 8L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static TempDocument toModel(TempDocumentSoap soapModel) {
		TempDocument model = new TempDocumentImpl();

		model.setId(soapModel.getId());
		model.setRequestCode(soapModel.getRequestCode());
		model.setRequestState(soapModel.getRequestState());
		model.setDocumentName(soapModel.getDocumentName());
		model.setDocumentYear(soapModel.getDocumentYear());
		model.setDocumentTypeCode(soapModel.getDocumentTypeCode());
		model.setUserCreated(soapModel.getUserCreated());
		model.setShipAgencyCode(soapModel.getShipAgencyCode());
		model.setShipName(soapModel.getShipName());
		model.setShipTypeCode(soapModel.getShipTypeCode());
		model.setStateCode(soapModel.getStateCode());
		model.setShipCaptain(soapModel.getShipCaptain());
		model.setImo(soapModel.getImo());
		model.setGrt(soapModel.getGrt());
		model.setNt(soapModel.getNt());
		model.setDwt(soapModel.getDwt());
		model.setUnitGRT(soapModel.getUnitGRT());
		model.setUnitNT(soapModel.getUnitNT());
		model.setUnitDWT(soapModel.getUnitDWT());
		model.setCallSign(soapModel.getCallSign());
		model.setPreDocumentName(soapModel.getPreDocumentName());
		model.setCreatedDate(soapModel.getCreatedDate());
		model.setLastModifiedDate(soapModel.getLastModifiedDate());
		model.setFlowFlag(soapModel.getFlowFlag());
		model.setDocumentStatusCode(soapModel.getDocumentStatusCode());
		model.setLocationCode(soapModel.getLocationCode());
		model.setMaritimeCode(soapModel.getMaritimeCode());
		model.setPortRegionCode(soapModel.getPortRegionCode());
		model.setPortCode(soapModel.getPortCode());
		model.setLastPortCode(soapModel.getLastPortCode());
		model.setShipPosition(soapModel.getShipPosition());
		model.setShipOwnerCode(soapModel.getShipOwnerCode());
		model.setArrivalShipAgency(soapModel.getArrivalShipAgency());
		model.setDepartureShipAgency(soapModel.getDepartureShipAgency());
		model.setShipDateFrom(soapModel.getShipDateFrom());
		model.setShipDateTo(soapModel.getShipDateTo());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<TempDocument> toModels(TempDocumentSoap[] soapModels) {
		List<TempDocument> models = new ArrayList<TempDocument>(soapModels.length);

		for (TempDocumentSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.vn.gt.dao.noticeandmessage.model.TempDocument"));

	public TempDocumentModelImpl() {
	}

	public long getPrimaryKey() {
		return _id;
	}

	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	public Serializable getPrimaryKeyObj() {
		return new Long(_id);
	}

	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	public Class<?> getModelClass() {
		return TempDocument.class;
	}

	public String getModelClassName() {
		return TempDocument.class.getName();
	}

	@JSON
	public long getId() {
		return _id;
	}

	public void setId(long id) {
		_columnBitmask = -1L;

		_id = id;
	}

	@JSON
	public String getRequestCode() {
		if (_requestCode == null) {
			return StringPool.BLANK;
		}
		else {
			return _requestCode;
		}
	}

	public void setRequestCode(String requestCode) {
		_columnBitmask |= REQUESTCODE_COLUMN_BITMASK;

		if (_originalRequestCode == null) {
			_originalRequestCode = _requestCode;
		}

		_requestCode = requestCode;
	}

	public String getOriginalRequestCode() {
		return GetterUtil.getString(_originalRequestCode);
	}

	@JSON
	public int getRequestState() {
		return _requestState;
	}

	public void setRequestState(int requestState) {
		_columnBitmask |= REQUESTSTATE_COLUMN_BITMASK;

		if (!_setOriginalRequestState) {
			_setOriginalRequestState = true;

			_originalRequestState = _requestState;
		}

		_requestState = requestState;
	}

	public int getOriginalRequestState() {
		return _originalRequestState;
	}

	@JSON
	public long getDocumentName() {
		return _documentName;
	}

	public void setDocumentName(long documentName) {
		_columnBitmask |= DOCUMENTNAME_COLUMN_BITMASK;

		if (!_setOriginalDocumentName) {
			_setOriginalDocumentName = true;

			_originalDocumentName = _documentName;
		}

		_documentName = documentName;
	}

	public long getOriginalDocumentName() {
		return _originalDocumentName;
	}

	@JSON
	public int getDocumentYear() {
		return _documentYear;
	}

	public void setDocumentYear(int documentYear) {
		_columnBitmask |= DOCUMENTYEAR_COLUMN_BITMASK;

		if (!_setOriginalDocumentYear) {
			_setOriginalDocumentYear = true;

			_originalDocumentYear = _documentYear;
		}

		_documentYear = documentYear;
	}

	public int getOriginalDocumentYear() {
		return _originalDocumentYear;
	}

	@JSON
	public String getDocumentTypeCode() {
		if (_documentTypeCode == null) {
			return StringPool.BLANK;
		}
		else {
			return _documentTypeCode;
		}
	}

	public void setDocumentTypeCode(String documentTypeCode) {
		_documentTypeCode = documentTypeCode;
	}

	@JSON
	public String getUserCreated() {
		if (_userCreated == null) {
			return StringPool.BLANK;
		}
		else {
			return _userCreated;
		}
	}

	public void setUserCreated(String userCreated) {
		_userCreated = userCreated;
	}

	@JSON
	public String getShipAgencyCode() {
		if (_shipAgencyCode == null) {
			return StringPool.BLANK;
		}
		else {
			return _shipAgencyCode;
		}
	}

	public void setShipAgencyCode(String shipAgencyCode) {
		_shipAgencyCode = shipAgencyCode;
	}

	@JSON
	public String getShipName() {
		if (_shipName == null) {
			return StringPool.BLANK;
		}
		else {
			return _shipName;
		}
	}

	public void setShipName(String shipName) {
		_shipName = shipName;
	}

	@JSON
	public String getShipTypeCode() {
		if (_shipTypeCode == null) {
			return StringPool.BLANK;
		}
		else {
			return _shipTypeCode;
		}
	}

	public void setShipTypeCode(String shipTypeCode) {
		_shipTypeCode = shipTypeCode;
	}

	@JSON
	public String getStateCode() {
		if (_stateCode == null) {
			return StringPool.BLANK;
		}
		else {
			return _stateCode;
		}
	}

	public void setStateCode(String stateCode) {
		_stateCode = stateCode;
	}

	@JSON
	public String getShipCaptain() {
		if (_shipCaptain == null) {
			return StringPool.BLANK;
		}
		else {
			return _shipCaptain;
		}
	}

	public void setShipCaptain(String shipCaptain) {
		_shipCaptain = shipCaptain;
	}

	@JSON
	public String getImo() {
		if (_imo == null) {
			return StringPool.BLANK;
		}
		else {
			return _imo;
		}
	}

	public void setImo(String imo) {
		_imo = imo;
	}

	@JSON
	public double getGrt() {
		return _grt;
	}

	public void setGrt(double grt) {
		_grt = grt;
	}

	@JSON
	public double getNt() {
		return _nt;
	}

	public void setNt(double nt) {
		_nt = nt;
	}

	@JSON
	public double getDwt() {
		return _dwt;
	}

	public void setDwt(double dwt) {
		_dwt = dwt;
	}

	@JSON
	public String getUnitGRT() {
		if (_unitGRT == null) {
			return StringPool.BLANK;
		}
		else {
			return _unitGRT;
		}
	}

	public void setUnitGRT(String unitGRT) {
		_unitGRT = unitGRT;
	}

	@JSON
	public String getUnitNT() {
		if (_unitNT == null) {
			return StringPool.BLANK;
		}
		else {
			return _unitNT;
		}
	}

	public void setUnitNT(String unitNT) {
		_unitNT = unitNT;
	}

	@JSON
	public String getUnitDWT() {
		if (_unitDWT == null) {
			return StringPool.BLANK;
		}
		else {
			return _unitDWT;
		}
	}

	public void setUnitDWT(String unitDWT) {
		_unitDWT = unitDWT;
	}

	@JSON
	public String getCallSign() {
		if (_callSign == null) {
			return StringPool.BLANK;
		}
		else {
			return _callSign;
		}
	}

	public void setCallSign(String callSign) {
		_callSign = callSign;
	}

	@JSON
	public String getPreDocumentName() {
		if (_preDocumentName == null) {
			return StringPool.BLANK;
		}
		else {
			return _preDocumentName;
		}
	}

	public void setPreDocumentName(String preDocumentName) {
		_preDocumentName = preDocumentName;
	}

	@JSON
	public Date getCreatedDate() {
		return _createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		_createdDate = createdDate;
	}

	@JSON
	public Date getLastModifiedDate() {
		return _lastModifiedDate;
	}

	public void setLastModifiedDate(Date lastModifiedDate) {
		_lastModifiedDate = lastModifiedDate;
	}

	@JSON
	public int getFlowFlag() {
		return _flowFlag;
	}

	public void setFlowFlag(int flowFlag) {
		_flowFlag = flowFlag;
	}

	@JSON
	public int getDocumentStatusCode() {
		return _documentStatusCode;
	}

	public void setDocumentStatusCode(int documentStatusCode) {
		_documentStatusCode = documentStatusCode;
	}

	@JSON
	public String getLocationCode() {
		if (_locationCode == null) {
			return StringPool.BLANK;
		}
		else {
			return _locationCode;
		}
	}

	public void setLocationCode(String locationCode) {
		_locationCode = locationCode;
	}

	@JSON
	public String getMaritimeCode() {
		if (_maritimeCode == null) {
			return StringPool.BLANK;
		}
		else {
			return _maritimeCode;
		}
	}

	public void setMaritimeCode(String maritimeCode) {
		_maritimeCode = maritimeCode;
	}

	@JSON
	public String getPortRegionCode() {
		if (_portRegionCode == null) {
			return StringPool.BLANK;
		}
		else {
			return _portRegionCode;
		}
	}

	public void setPortRegionCode(String portRegionCode) {
		_portRegionCode = portRegionCode;
	}

	@JSON
	public String getPortCode() {
		if (_portCode == null) {
			return StringPool.BLANK;
		}
		else {
			return _portCode;
		}
	}

	public void setPortCode(String portCode) {
		_portCode = portCode;
	}

	@JSON
	public String getLastPortCode() {
		if (_lastPortCode == null) {
			return StringPool.BLANK;
		}
		else {
			return _lastPortCode;
		}
	}

	public void setLastPortCode(String lastPortCode) {
		_lastPortCode = lastPortCode;
	}

	@JSON
	public int getShipPosition() {
		return _shipPosition;
	}

	public void setShipPosition(int shipPosition) {
		_shipPosition = shipPosition;
	}

	@JSON
	public String getShipOwnerCode() {
		if (_shipOwnerCode == null) {
			return StringPool.BLANK;
		}
		else {
			return _shipOwnerCode;
		}
	}

	public void setShipOwnerCode(String shipOwnerCode) {
		_shipOwnerCode = shipOwnerCode;
	}

	@JSON
	public String getArrivalShipAgency() {
		if (_arrivalShipAgency == null) {
			return StringPool.BLANK;
		}
		else {
			return _arrivalShipAgency;
		}
	}

	public void setArrivalShipAgency(String arrivalShipAgency) {
		_arrivalShipAgency = arrivalShipAgency;
	}

	@JSON
	public String getDepartureShipAgency() {
		if (_departureShipAgency == null) {
			return StringPool.BLANK;
		}
		else {
			return _departureShipAgency;
		}
	}

	public void setDepartureShipAgency(String departureShipAgency) {
		_departureShipAgency = departureShipAgency;
	}

	@JSON
	public Date getShipDateFrom() {
		return _shipDateFrom;
	}

	public void setShipDateFrom(Date shipDateFrom) {
		_shipDateFrom = shipDateFrom;
	}

	@JSON
	public Date getShipDateTo() {
		return _shipDateTo;
	}

	public void setShipDateTo(Date shipDateTo) {
		_shipDateTo = shipDateTo;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public TempDocument toEscapedModel() {
		if (_escapedModelProxy == null) {
			_escapedModelProxy = (TempDocument)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelProxyInterfaces,
					new AutoEscapeBeanHandler(this));
		}

		return _escapedModelProxy;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		if (_expandoBridge == null) {
			_expandoBridge = ExpandoBridgeFactoryUtil.getExpandoBridge(0,
					TempDocument.class.getName(), getPrimaryKey());
		}

		return _expandoBridge;
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		getExpandoBridge().setAttributes(serviceContext);
	}

	@Override
	public Object clone() {
		TempDocumentImpl tempDocumentImpl = new TempDocumentImpl();

		tempDocumentImpl.setId(getId());
		tempDocumentImpl.setRequestCode(getRequestCode());
		tempDocumentImpl.setRequestState(getRequestState());
		tempDocumentImpl.setDocumentName(getDocumentName());
		tempDocumentImpl.setDocumentYear(getDocumentYear());
		tempDocumentImpl.setDocumentTypeCode(getDocumentTypeCode());
		tempDocumentImpl.setUserCreated(getUserCreated());
		tempDocumentImpl.setShipAgencyCode(getShipAgencyCode());
		tempDocumentImpl.setShipName(getShipName());
		tempDocumentImpl.setShipTypeCode(getShipTypeCode());
		tempDocumentImpl.setStateCode(getStateCode());
		tempDocumentImpl.setShipCaptain(getShipCaptain());
		tempDocumentImpl.setImo(getImo());
		tempDocumentImpl.setGrt(getGrt());
		tempDocumentImpl.setNt(getNt());
		tempDocumentImpl.setDwt(getDwt());
		tempDocumentImpl.setUnitGRT(getUnitGRT());
		tempDocumentImpl.setUnitNT(getUnitNT());
		tempDocumentImpl.setUnitDWT(getUnitDWT());
		tempDocumentImpl.setCallSign(getCallSign());
		tempDocumentImpl.setPreDocumentName(getPreDocumentName());
		tempDocumentImpl.setCreatedDate(getCreatedDate());
		tempDocumentImpl.setLastModifiedDate(getLastModifiedDate());
		tempDocumentImpl.setFlowFlag(getFlowFlag());
		tempDocumentImpl.setDocumentStatusCode(getDocumentStatusCode());
		tempDocumentImpl.setLocationCode(getLocationCode());
		tempDocumentImpl.setMaritimeCode(getMaritimeCode());
		tempDocumentImpl.setPortRegionCode(getPortRegionCode());
		tempDocumentImpl.setPortCode(getPortCode());
		tempDocumentImpl.setLastPortCode(getLastPortCode());
		tempDocumentImpl.setShipPosition(getShipPosition());
		tempDocumentImpl.setShipOwnerCode(getShipOwnerCode());
		tempDocumentImpl.setArrivalShipAgency(getArrivalShipAgency());
		tempDocumentImpl.setDepartureShipAgency(getDepartureShipAgency());
		tempDocumentImpl.setShipDateFrom(getShipDateFrom());
		tempDocumentImpl.setShipDateTo(getShipDateTo());

		tempDocumentImpl.resetOriginalValues();

		return tempDocumentImpl;
	}

	public int compareTo(TempDocument tempDocument) {
		int value = 0;

		if (getId() < tempDocument.getId()) {
			value = -1;
		}
		else if (getId() > tempDocument.getId()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		TempDocument tempDocument = null;

		try {
			tempDocument = (TempDocument)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		long primaryKey = tempDocument.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		TempDocumentModelImpl tempDocumentModelImpl = this;

		tempDocumentModelImpl._originalRequestCode = tempDocumentModelImpl._requestCode;

		tempDocumentModelImpl._originalRequestState = tempDocumentModelImpl._requestState;

		tempDocumentModelImpl._setOriginalRequestState = false;

		tempDocumentModelImpl._originalDocumentName = tempDocumentModelImpl._documentName;

		tempDocumentModelImpl._setOriginalDocumentName = false;

		tempDocumentModelImpl._originalDocumentYear = tempDocumentModelImpl._documentYear;

		tempDocumentModelImpl._setOriginalDocumentYear = false;

		tempDocumentModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<TempDocument> toCacheModel() {
		TempDocumentCacheModel tempDocumentCacheModel = new TempDocumentCacheModel();

		tempDocumentCacheModel.id = getId();

		tempDocumentCacheModel.requestCode = getRequestCode();

		String requestCode = tempDocumentCacheModel.requestCode;

		if ((requestCode != null) && (requestCode.length() == 0)) {
			tempDocumentCacheModel.requestCode = null;
		}

		tempDocumentCacheModel.requestState = getRequestState();

		tempDocumentCacheModel.documentName = getDocumentName();

		tempDocumentCacheModel.documentYear = getDocumentYear();

		tempDocumentCacheModel.documentTypeCode = getDocumentTypeCode();

		String documentTypeCode = tempDocumentCacheModel.documentTypeCode;

		if ((documentTypeCode != null) && (documentTypeCode.length() == 0)) {
			tempDocumentCacheModel.documentTypeCode = null;
		}

		tempDocumentCacheModel.userCreated = getUserCreated();

		String userCreated = tempDocumentCacheModel.userCreated;

		if ((userCreated != null) && (userCreated.length() == 0)) {
			tempDocumentCacheModel.userCreated = null;
		}

		tempDocumentCacheModel.shipAgencyCode = getShipAgencyCode();

		String shipAgencyCode = tempDocumentCacheModel.shipAgencyCode;

		if ((shipAgencyCode != null) && (shipAgencyCode.length() == 0)) {
			tempDocumentCacheModel.shipAgencyCode = null;
		}

		tempDocumentCacheModel.shipName = getShipName();

		String shipName = tempDocumentCacheModel.shipName;

		if ((shipName != null) && (shipName.length() == 0)) {
			tempDocumentCacheModel.shipName = null;
		}

		tempDocumentCacheModel.shipTypeCode = getShipTypeCode();

		String shipTypeCode = tempDocumentCacheModel.shipTypeCode;

		if ((shipTypeCode != null) && (shipTypeCode.length() == 0)) {
			tempDocumentCacheModel.shipTypeCode = null;
		}

		tempDocumentCacheModel.stateCode = getStateCode();

		String stateCode = tempDocumentCacheModel.stateCode;

		if ((stateCode != null) && (stateCode.length() == 0)) {
			tempDocumentCacheModel.stateCode = null;
		}

		tempDocumentCacheModel.shipCaptain = getShipCaptain();

		String shipCaptain = tempDocumentCacheModel.shipCaptain;

		if ((shipCaptain != null) && (shipCaptain.length() == 0)) {
			tempDocumentCacheModel.shipCaptain = null;
		}

		tempDocumentCacheModel.imo = getImo();

		String imo = tempDocumentCacheModel.imo;

		if ((imo != null) && (imo.length() == 0)) {
			tempDocumentCacheModel.imo = null;
		}

		tempDocumentCacheModel.grt = getGrt();

		tempDocumentCacheModel.nt = getNt();

		tempDocumentCacheModel.dwt = getDwt();

		tempDocumentCacheModel.unitGRT = getUnitGRT();

		String unitGRT = tempDocumentCacheModel.unitGRT;

		if ((unitGRT != null) && (unitGRT.length() == 0)) {
			tempDocumentCacheModel.unitGRT = null;
		}

		tempDocumentCacheModel.unitNT = getUnitNT();

		String unitNT = tempDocumentCacheModel.unitNT;

		if ((unitNT != null) && (unitNT.length() == 0)) {
			tempDocumentCacheModel.unitNT = null;
		}

		tempDocumentCacheModel.unitDWT = getUnitDWT();

		String unitDWT = tempDocumentCacheModel.unitDWT;

		if ((unitDWT != null) && (unitDWT.length() == 0)) {
			tempDocumentCacheModel.unitDWT = null;
		}

		tempDocumentCacheModel.callSign = getCallSign();

		String callSign = tempDocumentCacheModel.callSign;

		if ((callSign != null) && (callSign.length() == 0)) {
			tempDocumentCacheModel.callSign = null;
		}

		tempDocumentCacheModel.preDocumentName = getPreDocumentName();

		String preDocumentName = tempDocumentCacheModel.preDocumentName;

		if ((preDocumentName != null) && (preDocumentName.length() == 0)) {
			tempDocumentCacheModel.preDocumentName = null;
		}

		Date createdDate = getCreatedDate();

		if (createdDate != null) {
			tempDocumentCacheModel.createdDate = createdDate.getTime();
		}
		else {
			tempDocumentCacheModel.createdDate = Long.MIN_VALUE;
		}

		Date lastModifiedDate = getLastModifiedDate();

		if (lastModifiedDate != null) {
			tempDocumentCacheModel.lastModifiedDate = lastModifiedDate.getTime();
		}
		else {
			tempDocumentCacheModel.lastModifiedDate = Long.MIN_VALUE;
		}

		tempDocumentCacheModel.flowFlag = getFlowFlag();

		tempDocumentCacheModel.documentStatusCode = getDocumentStatusCode();

		tempDocumentCacheModel.locationCode = getLocationCode();

		String locationCode = tempDocumentCacheModel.locationCode;

		if ((locationCode != null) && (locationCode.length() == 0)) {
			tempDocumentCacheModel.locationCode = null;
		}

		tempDocumentCacheModel.maritimeCode = getMaritimeCode();

		String maritimeCode = tempDocumentCacheModel.maritimeCode;

		if ((maritimeCode != null) && (maritimeCode.length() == 0)) {
			tempDocumentCacheModel.maritimeCode = null;
		}

		tempDocumentCacheModel.portRegionCode = getPortRegionCode();

		String portRegionCode = tempDocumentCacheModel.portRegionCode;

		if ((portRegionCode != null) && (portRegionCode.length() == 0)) {
			tempDocumentCacheModel.portRegionCode = null;
		}

		tempDocumentCacheModel.portCode = getPortCode();

		String portCode = tempDocumentCacheModel.portCode;

		if ((portCode != null) && (portCode.length() == 0)) {
			tempDocumentCacheModel.portCode = null;
		}

		tempDocumentCacheModel.lastPortCode = getLastPortCode();

		String lastPortCode = tempDocumentCacheModel.lastPortCode;

		if ((lastPortCode != null) && (lastPortCode.length() == 0)) {
			tempDocumentCacheModel.lastPortCode = null;
		}

		tempDocumentCacheModel.shipPosition = getShipPosition();

		tempDocumentCacheModel.shipOwnerCode = getShipOwnerCode();

		String shipOwnerCode = tempDocumentCacheModel.shipOwnerCode;

		if ((shipOwnerCode != null) && (shipOwnerCode.length() == 0)) {
			tempDocumentCacheModel.shipOwnerCode = null;
		}

		tempDocumentCacheModel.arrivalShipAgency = getArrivalShipAgency();

		String arrivalShipAgency = tempDocumentCacheModel.arrivalShipAgency;

		if ((arrivalShipAgency != null) && (arrivalShipAgency.length() == 0)) {
			tempDocumentCacheModel.arrivalShipAgency = null;
		}

		tempDocumentCacheModel.departureShipAgency = getDepartureShipAgency();

		String departureShipAgency = tempDocumentCacheModel.departureShipAgency;

		if ((departureShipAgency != null) &&
				(departureShipAgency.length() == 0)) {
			tempDocumentCacheModel.departureShipAgency = null;
		}

		Date shipDateFrom = getShipDateFrom();

		if (shipDateFrom != null) {
			tempDocumentCacheModel.shipDateFrom = shipDateFrom.getTime();
		}
		else {
			tempDocumentCacheModel.shipDateFrom = Long.MIN_VALUE;
		}

		Date shipDateTo = getShipDateTo();

		if (shipDateTo != null) {
			tempDocumentCacheModel.shipDateTo = shipDateTo.getTime();
		}
		else {
			tempDocumentCacheModel.shipDateTo = Long.MIN_VALUE;
		}

		return tempDocumentCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(73);

		sb.append("{id=");
		sb.append(getId());
		sb.append(", requestCode=");
		sb.append(getRequestCode());
		sb.append(", requestState=");
		sb.append(getRequestState());
		sb.append(", documentName=");
		sb.append(getDocumentName());
		sb.append(", documentYear=");
		sb.append(getDocumentYear());
		sb.append(", documentTypeCode=");
		sb.append(getDocumentTypeCode());
		sb.append(", userCreated=");
		sb.append(getUserCreated());
		sb.append(", shipAgencyCode=");
		sb.append(getShipAgencyCode());
		sb.append(", shipName=");
		sb.append(getShipName());
		sb.append(", shipTypeCode=");
		sb.append(getShipTypeCode());
		sb.append(", stateCode=");
		sb.append(getStateCode());
		sb.append(", shipCaptain=");
		sb.append(getShipCaptain());
		sb.append(", imo=");
		sb.append(getImo());
		sb.append(", grt=");
		sb.append(getGrt());
		sb.append(", nt=");
		sb.append(getNt());
		sb.append(", dwt=");
		sb.append(getDwt());
		sb.append(", unitGRT=");
		sb.append(getUnitGRT());
		sb.append(", unitNT=");
		sb.append(getUnitNT());
		sb.append(", unitDWT=");
		sb.append(getUnitDWT());
		sb.append(", callSign=");
		sb.append(getCallSign());
		sb.append(", preDocumentName=");
		sb.append(getPreDocumentName());
		sb.append(", createdDate=");
		sb.append(getCreatedDate());
		sb.append(", lastModifiedDate=");
		sb.append(getLastModifiedDate());
		sb.append(", flowFlag=");
		sb.append(getFlowFlag());
		sb.append(", documentStatusCode=");
		sb.append(getDocumentStatusCode());
		sb.append(", locationCode=");
		sb.append(getLocationCode());
		sb.append(", maritimeCode=");
		sb.append(getMaritimeCode());
		sb.append(", portRegionCode=");
		sb.append(getPortRegionCode());
		sb.append(", portCode=");
		sb.append(getPortCode());
		sb.append(", lastPortCode=");
		sb.append(getLastPortCode());
		sb.append(", shipPosition=");
		sb.append(getShipPosition());
		sb.append(", shipOwnerCode=");
		sb.append(getShipOwnerCode());
		sb.append(", arrivalShipAgency=");
		sb.append(getArrivalShipAgency());
		sb.append(", departureShipAgency=");
		sb.append(getDepartureShipAgency());
		sb.append(", shipDateFrom=");
		sb.append(getShipDateFrom());
		sb.append(", shipDateTo=");
		sb.append(getShipDateTo());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(112);

		sb.append("<model><model-name>");
		sb.append("vn.gt.dao.noticeandmessage.model.TempDocument");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>id</column-name><column-value><![CDATA[");
		sb.append(getId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>requestCode</column-name><column-value><![CDATA[");
		sb.append(getRequestCode());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>requestState</column-name><column-value><![CDATA[");
		sb.append(getRequestState());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>documentName</column-name><column-value><![CDATA[");
		sb.append(getDocumentName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>documentYear</column-name><column-value><![CDATA[");
		sb.append(getDocumentYear());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>documentTypeCode</column-name><column-value><![CDATA[");
		sb.append(getDocumentTypeCode());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userCreated</column-name><column-value><![CDATA[");
		sb.append(getUserCreated());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>shipAgencyCode</column-name><column-value><![CDATA[");
		sb.append(getShipAgencyCode());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>shipName</column-name><column-value><![CDATA[");
		sb.append(getShipName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>shipTypeCode</column-name><column-value><![CDATA[");
		sb.append(getShipTypeCode());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>stateCode</column-name><column-value><![CDATA[");
		sb.append(getStateCode());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>shipCaptain</column-name><column-value><![CDATA[");
		sb.append(getShipCaptain());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>imo</column-name><column-value><![CDATA[");
		sb.append(getImo());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>grt</column-name><column-value><![CDATA[");
		sb.append(getGrt());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>nt</column-name><column-value><![CDATA[");
		sb.append(getNt());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>dwt</column-name><column-value><![CDATA[");
		sb.append(getDwt());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>unitGRT</column-name><column-value><![CDATA[");
		sb.append(getUnitGRT());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>unitNT</column-name><column-value><![CDATA[");
		sb.append(getUnitNT());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>unitDWT</column-name><column-value><![CDATA[");
		sb.append(getUnitDWT());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>callSign</column-name><column-value><![CDATA[");
		sb.append(getCallSign());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>preDocumentName</column-name><column-value><![CDATA[");
		sb.append(getPreDocumentName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createdDate</column-name><column-value><![CDATA[");
		sb.append(getCreatedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>lastModifiedDate</column-name><column-value><![CDATA[");
		sb.append(getLastModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>flowFlag</column-name><column-value><![CDATA[");
		sb.append(getFlowFlag());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>documentStatusCode</column-name><column-value><![CDATA[");
		sb.append(getDocumentStatusCode());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>locationCode</column-name><column-value><![CDATA[");
		sb.append(getLocationCode());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>maritimeCode</column-name><column-value><![CDATA[");
		sb.append(getMaritimeCode());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>portRegionCode</column-name><column-value><![CDATA[");
		sb.append(getPortRegionCode());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>portCode</column-name><column-value><![CDATA[");
		sb.append(getPortCode());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>lastPortCode</column-name><column-value><![CDATA[");
		sb.append(getLastPortCode());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>shipPosition</column-name><column-value><![CDATA[");
		sb.append(getShipPosition());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>shipOwnerCode</column-name><column-value><![CDATA[");
		sb.append(getShipOwnerCode());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>arrivalShipAgency</column-name><column-value><![CDATA[");
		sb.append(getArrivalShipAgency());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>departureShipAgency</column-name><column-value><![CDATA[");
		sb.append(getDepartureShipAgency());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>shipDateFrom</column-name><column-value><![CDATA[");
		sb.append(getShipDateFrom());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>shipDateTo</column-name><column-value><![CDATA[");
		sb.append(getShipDateTo());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = TempDocument.class.getClassLoader();
	private static Class<?>[] _escapedModelProxyInterfaces = new Class[] {
			TempDocument.class
		};
	private long _id;
	private String _requestCode;
	private String _originalRequestCode;
	private int _requestState;
	private int _originalRequestState;
	private boolean _setOriginalRequestState;
	private long _documentName;
	private long _originalDocumentName;
	private boolean _setOriginalDocumentName;
	private int _documentYear;
	private int _originalDocumentYear;
	private boolean _setOriginalDocumentYear;
	private String _documentTypeCode;
	private String _userCreated;
	private String _shipAgencyCode;
	private String _shipName;
	private String _shipTypeCode;
	private String _stateCode;
	private String _shipCaptain;
	private String _imo;
	private double _grt;
	private double _nt;
	private double _dwt;
	private String _unitGRT;
	private String _unitNT;
	private String _unitDWT;
	private String _callSign;
	private String _preDocumentName;
	private Date _createdDate;
	private Date _lastModifiedDate;
	private int _flowFlag;
	private int _documentStatusCode;
	private String _locationCode;
	private String _maritimeCode;
	private String _portRegionCode;
	private String _portCode;
	private String _lastPortCode;
	private int _shipPosition;
	private String _shipOwnerCode;
	private String _arrivalShipAgency;
	private String _departureShipAgency;
	private Date _shipDateFrom;
	private Date _shipDateTo;
	private transient ExpandoBridge _expandoBridge;
	private long _columnBitmask;
	private TempDocument _escapedModelProxy;
}