/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.gt.dao.noticeandmessage.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import vn.gt.dao.noticeandmessage.model.TempCrewEffectsItems;
import vn.gt.dao.noticeandmessage.service.TempCrewEffectsItemsLocalServiceUtil;

/**
 * The extended model base implementation for the TempCrewEffectsItems service. Represents a row in the &quot;TEMP_CREW_EFFECTS_ITEMS&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link TempCrewEffectsItemsImpl}.
 * </p>
 *
 * @author win_64
 * @see TempCrewEffectsItemsImpl
 * @see vn.gt.dao.noticeandmessage.model.TempCrewEffectsItems
 * @generated
 */
public abstract class TempCrewEffectsItemsBaseImpl
	extends TempCrewEffectsItemsModelImpl implements TempCrewEffectsItems {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a temp crew effects items model instance should use the {@link TempCrewEffectsItems} interface instead.
	 */
	public void persist() throws SystemException {
		if (this.isNew()) {
			TempCrewEffectsItemsLocalServiceUtil.addTempCrewEffectsItems(this);
		}
		else {
			TempCrewEffectsItemsLocalServiceUtil.updateTempCrewEffectsItems(this);
		}
	}
}