/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.gt.dao.noticeandmessage.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import vn.gt.dao.noticeandmessage.model.TempGoodsItems;
import vn.gt.dao.noticeandmessage.model.TempGoodsItemsModel;
import vn.gt.dao.noticeandmessage.model.TempGoodsItemsSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.List;

/**
 * The base model implementation for the TempGoodsItems service. Represents a row in the &quot;TEMP_GOODS_ITEMS&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link vn.gt.dao.noticeandmessage.model.TempGoodsItemsModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link TempGoodsItemsImpl}.
 * </p>
 *
 * @author win_64
 * @see TempGoodsItemsImpl
 * @see vn.gt.dao.noticeandmessage.model.TempGoodsItems
 * @see vn.gt.dao.noticeandmessage.model.TempGoodsItemsModel
 * @generated
 */
@JSON(strict = true)
public class TempGoodsItemsModelImpl extends BaseModelImpl<TempGoodsItems>
	implements TempGoodsItemsModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a temp goods items model instance should use the {@link vn.gt.dao.noticeandmessage.model.TempGoodsItems} interface instead.
	 */
	public static final String TABLE_NAME = "TEMP_GOODS_ITEMS";
	public static final Object[][] TABLE_COLUMNS = {
			{ "ID", Types.BIGINT },
			{ "RequestCode", Types.VARCHAR },
			{ "BillOfLadingNo", Types.VARCHAR },
			{ "GoodItemCode", Types.VARCHAR },
			{ "GoodItemDescription", Types.VARCHAR },
			{ "NumberOfPackage", Types.BIGINT },
			{ "KindOfPackages", Types.VARCHAR },
			{ "MarksandNosofGoods", Types.VARCHAR },
			{ "GrossWeight", Types.DOUBLE },
			{ "GrossWeightUnit", Types.VARCHAR },
			{ "Measurement", Types.DOUBLE },
			{ "MeasurementUnit", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table TEMP_GOODS_ITEMS (ID LONG not null primary key,RequestCode VARCHAR(75) null,BillOfLadingNo VARCHAR(75) null,GoodItemCode VARCHAR(75) null,GoodItemDescription VARCHAR(75) null,NumberOfPackage LONG,KindOfPackages VARCHAR(75) null,MarksandNosofGoods VARCHAR(75) null,GrossWeight DOUBLE,GrossWeightUnit VARCHAR(75) null,Measurement DOUBLE,MeasurementUnit VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table TEMP_GOODS_ITEMS";
	public static final String ORDER_BY_JPQL = " ORDER BY tempGoodsItems.id ASC";
	public static final String ORDER_BY_SQL = " ORDER BY TEMP_GOODS_ITEMS.ID ASC";
	public static final String DATA_SOURCE = "gtDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.vn.gt.dao.noticeandmessage.model.TempGoodsItems"),
			false);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.vn.gt.dao.noticeandmessage.model.TempGoodsItems"),
			false);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.vn.gt.dao.noticeandmessage.model.TempGoodsItems"),
			true);
	public static long REQUESTCODE_COLUMN_BITMASK = 1L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static TempGoodsItems toModel(TempGoodsItemsSoap soapModel) {
		TempGoodsItems model = new TempGoodsItemsImpl();

		model.setId(soapModel.getId());
		model.setRequestCode(soapModel.getRequestCode());
		model.setBillOfLadingNo(soapModel.getBillOfLadingNo());
		model.setGoodItemCode(soapModel.getGoodItemCode());
		model.setGoodItemDescription(soapModel.getGoodItemDescription());
		model.setNumberOfPackage(soapModel.getNumberOfPackage());
		model.setKindOfPackages(soapModel.getKindOfPackages());
		model.setMarksandNosofGoods(soapModel.getMarksandNosofGoods());
		model.setGrossWeight(soapModel.getGrossWeight());
		model.setGrossWeightUnit(soapModel.getGrossWeightUnit());
		model.setMeasurement(soapModel.getMeasurement());
		model.setMeasurementUnit(soapModel.getMeasurementUnit());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<TempGoodsItems> toModels(TempGoodsItemsSoap[] soapModels) {
		List<TempGoodsItems> models = new ArrayList<TempGoodsItems>(soapModels.length);

		for (TempGoodsItemsSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.vn.gt.dao.noticeandmessage.model.TempGoodsItems"));

	public TempGoodsItemsModelImpl() {
	}

	public long getPrimaryKey() {
		return _id;
	}

	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	public Serializable getPrimaryKeyObj() {
		return new Long(_id);
	}

	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	public Class<?> getModelClass() {
		return TempGoodsItems.class;
	}

	public String getModelClassName() {
		return TempGoodsItems.class.getName();
	}

	@JSON
	public long getId() {
		return _id;
	}

	public void setId(long id) {
		_columnBitmask = -1L;

		_id = id;
	}

	@JSON
	public String getRequestCode() {
		if (_requestCode == null) {
			return StringPool.BLANK;
		}
		else {
			return _requestCode;
		}
	}

	public void setRequestCode(String requestCode) {
		_columnBitmask |= REQUESTCODE_COLUMN_BITMASK;

		if (_originalRequestCode == null) {
			_originalRequestCode = _requestCode;
		}

		_requestCode = requestCode;
	}

	public String getOriginalRequestCode() {
		return GetterUtil.getString(_originalRequestCode);
	}

	@JSON
	public String getBillOfLadingNo() {
		if (_billOfLadingNo == null) {
			return StringPool.BLANK;
		}
		else {
			return _billOfLadingNo;
		}
	}

	public void setBillOfLadingNo(String billOfLadingNo) {
		_billOfLadingNo = billOfLadingNo;
	}

	@JSON
	public String getGoodItemCode() {
		if (_goodItemCode == null) {
			return StringPool.BLANK;
		}
		else {
			return _goodItemCode;
		}
	}

	public void setGoodItemCode(String goodItemCode) {
		_goodItemCode = goodItemCode;
	}

	@JSON
	public String getGoodItemDescription() {
		if (_goodItemDescription == null) {
			return StringPool.BLANK;
		}
		else {
			return _goodItemDescription;
		}
	}

	public void setGoodItemDescription(String goodItemDescription) {
		_goodItemDescription = goodItemDescription;
	}

	@JSON
	public long getNumberOfPackage() {
		return _numberOfPackage;
	}

	public void setNumberOfPackage(long numberOfPackage) {
		_numberOfPackage = numberOfPackage;
	}

	@JSON
	public String getKindOfPackages() {
		if (_kindOfPackages == null) {
			return StringPool.BLANK;
		}
		else {
			return _kindOfPackages;
		}
	}

	public void setKindOfPackages(String kindOfPackages) {
		_kindOfPackages = kindOfPackages;
	}

	@JSON
	public String getMarksandNosofGoods() {
		if (_marksandNosofGoods == null) {
			return StringPool.BLANK;
		}
		else {
			return _marksandNosofGoods;
		}
	}

	public void setMarksandNosofGoods(String marksandNosofGoods) {
		_marksandNosofGoods = marksandNosofGoods;
	}

	@JSON
	public double getGrossWeight() {
		return _grossWeight;
	}

	public void setGrossWeight(double grossWeight) {
		_grossWeight = grossWeight;
	}

	@JSON
	public String getGrossWeightUnit() {
		if (_grossWeightUnit == null) {
			return StringPool.BLANK;
		}
		else {
			return _grossWeightUnit;
		}
	}

	public void setGrossWeightUnit(String grossWeightUnit) {
		_grossWeightUnit = grossWeightUnit;
	}

	@JSON
	public double getMeasurement() {
		return _measurement;
	}

	public void setMeasurement(double measurement) {
		_measurement = measurement;
	}

	@JSON
	public String getMeasurementUnit() {
		if (_measurementUnit == null) {
			return StringPool.BLANK;
		}
		else {
			return _measurementUnit;
		}
	}

	public void setMeasurementUnit(String measurementUnit) {
		_measurementUnit = measurementUnit;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public TempGoodsItems toEscapedModel() {
		if (_escapedModelProxy == null) {
			_escapedModelProxy = (TempGoodsItems)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelProxyInterfaces,
					new AutoEscapeBeanHandler(this));
		}

		return _escapedModelProxy;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		if (_expandoBridge == null) {
			_expandoBridge = ExpandoBridgeFactoryUtil.getExpandoBridge(0,
					TempGoodsItems.class.getName(), getPrimaryKey());
		}

		return _expandoBridge;
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		getExpandoBridge().setAttributes(serviceContext);
	}

	@Override
	public Object clone() {
		TempGoodsItemsImpl tempGoodsItemsImpl = new TempGoodsItemsImpl();

		tempGoodsItemsImpl.setId(getId());
		tempGoodsItemsImpl.setRequestCode(getRequestCode());
		tempGoodsItemsImpl.setBillOfLadingNo(getBillOfLadingNo());
		tempGoodsItemsImpl.setGoodItemCode(getGoodItemCode());
		tempGoodsItemsImpl.setGoodItemDescription(getGoodItemDescription());
		tempGoodsItemsImpl.setNumberOfPackage(getNumberOfPackage());
		tempGoodsItemsImpl.setKindOfPackages(getKindOfPackages());
		tempGoodsItemsImpl.setMarksandNosofGoods(getMarksandNosofGoods());
		tempGoodsItemsImpl.setGrossWeight(getGrossWeight());
		tempGoodsItemsImpl.setGrossWeightUnit(getGrossWeightUnit());
		tempGoodsItemsImpl.setMeasurement(getMeasurement());
		tempGoodsItemsImpl.setMeasurementUnit(getMeasurementUnit());

		tempGoodsItemsImpl.resetOriginalValues();

		return tempGoodsItemsImpl;
	}

	public int compareTo(TempGoodsItems tempGoodsItems) {
		int value = 0;

		if (getId() < tempGoodsItems.getId()) {
			value = -1;
		}
		else if (getId() > tempGoodsItems.getId()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		TempGoodsItems tempGoodsItems = null;

		try {
			tempGoodsItems = (TempGoodsItems)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		long primaryKey = tempGoodsItems.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		TempGoodsItemsModelImpl tempGoodsItemsModelImpl = this;

		tempGoodsItemsModelImpl._originalRequestCode = tempGoodsItemsModelImpl._requestCode;

		tempGoodsItemsModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<TempGoodsItems> toCacheModel() {
		TempGoodsItemsCacheModel tempGoodsItemsCacheModel = new TempGoodsItemsCacheModel();

		tempGoodsItemsCacheModel.id = getId();

		tempGoodsItemsCacheModel.requestCode = getRequestCode();

		String requestCode = tempGoodsItemsCacheModel.requestCode;

		if ((requestCode != null) && (requestCode.length() == 0)) {
			tempGoodsItemsCacheModel.requestCode = null;
		}

		tempGoodsItemsCacheModel.billOfLadingNo = getBillOfLadingNo();

		String billOfLadingNo = tempGoodsItemsCacheModel.billOfLadingNo;

		if ((billOfLadingNo != null) && (billOfLadingNo.length() == 0)) {
			tempGoodsItemsCacheModel.billOfLadingNo = null;
		}

		tempGoodsItemsCacheModel.goodItemCode = getGoodItemCode();

		String goodItemCode = tempGoodsItemsCacheModel.goodItemCode;

		if ((goodItemCode != null) && (goodItemCode.length() == 0)) {
			tempGoodsItemsCacheModel.goodItemCode = null;
		}

		tempGoodsItemsCacheModel.goodItemDescription = getGoodItemDescription();

		String goodItemDescription = tempGoodsItemsCacheModel.goodItemDescription;

		if ((goodItemDescription != null) &&
				(goodItemDescription.length() == 0)) {
			tempGoodsItemsCacheModel.goodItemDescription = null;
		}

		tempGoodsItemsCacheModel.numberOfPackage = getNumberOfPackage();

		tempGoodsItemsCacheModel.kindOfPackages = getKindOfPackages();

		String kindOfPackages = tempGoodsItemsCacheModel.kindOfPackages;

		if ((kindOfPackages != null) && (kindOfPackages.length() == 0)) {
			tempGoodsItemsCacheModel.kindOfPackages = null;
		}

		tempGoodsItemsCacheModel.marksandNosofGoods = getMarksandNosofGoods();

		String marksandNosofGoods = tempGoodsItemsCacheModel.marksandNosofGoods;

		if ((marksandNosofGoods != null) && (marksandNosofGoods.length() == 0)) {
			tempGoodsItemsCacheModel.marksandNosofGoods = null;
		}

		tempGoodsItemsCacheModel.grossWeight = getGrossWeight();

		tempGoodsItemsCacheModel.grossWeightUnit = getGrossWeightUnit();

		String grossWeightUnit = tempGoodsItemsCacheModel.grossWeightUnit;

		if ((grossWeightUnit != null) && (grossWeightUnit.length() == 0)) {
			tempGoodsItemsCacheModel.grossWeightUnit = null;
		}

		tempGoodsItemsCacheModel.measurement = getMeasurement();

		tempGoodsItemsCacheModel.measurementUnit = getMeasurementUnit();

		String measurementUnit = tempGoodsItemsCacheModel.measurementUnit;

		if ((measurementUnit != null) && (measurementUnit.length() == 0)) {
			tempGoodsItemsCacheModel.measurementUnit = null;
		}

		return tempGoodsItemsCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(25);

		sb.append("{id=");
		sb.append(getId());
		sb.append(", requestCode=");
		sb.append(getRequestCode());
		sb.append(", billOfLadingNo=");
		sb.append(getBillOfLadingNo());
		sb.append(", goodItemCode=");
		sb.append(getGoodItemCode());
		sb.append(", goodItemDescription=");
		sb.append(getGoodItemDescription());
		sb.append(", numberOfPackage=");
		sb.append(getNumberOfPackage());
		sb.append(", kindOfPackages=");
		sb.append(getKindOfPackages());
		sb.append(", marksandNosofGoods=");
		sb.append(getMarksandNosofGoods());
		sb.append(", grossWeight=");
		sb.append(getGrossWeight());
		sb.append(", grossWeightUnit=");
		sb.append(getGrossWeightUnit());
		sb.append(", measurement=");
		sb.append(getMeasurement());
		sb.append(", measurementUnit=");
		sb.append(getMeasurementUnit());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(40);

		sb.append("<model><model-name>");
		sb.append("vn.gt.dao.noticeandmessage.model.TempGoodsItems");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>id</column-name><column-value><![CDATA[");
		sb.append(getId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>requestCode</column-name><column-value><![CDATA[");
		sb.append(getRequestCode());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>billOfLadingNo</column-name><column-value><![CDATA[");
		sb.append(getBillOfLadingNo());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>goodItemCode</column-name><column-value><![CDATA[");
		sb.append(getGoodItemCode());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>goodItemDescription</column-name><column-value><![CDATA[");
		sb.append(getGoodItemDescription());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>numberOfPackage</column-name><column-value><![CDATA[");
		sb.append(getNumberOfPackage());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>kindOfPackages</column-name><column-value><![CDATA[");
		sb.append(getKindOfPackages());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>marksandNosofGoods</column-name><column-value><![CDATA[");
		sb.append(getMarksandNosofGoods());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>grossWeight</column-name><column-value><![CDATA[");
		sb.append(getGrossWeight());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>grossWeightUnit</column-name><column-value><![CDATA[");
		sb.append(getGrossWeightUnit());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>measurement</column-name><column-value><![CDATA[");
		sb.append(getMeasurement());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>measurementUnit</column-name><column-value><![CDATA[");
		sb.append(getMeasurementUnit());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = TempGoodsItems.class.getClassLoader();
	private static Class<?>[] _escapedModelProxyInterfaces = new Class[] {
			TempGoodsItems.class
		};
	private long _id;
	private String _requestCode;
	private String _originalRequestCode;
	private String _billOfLadingNo;
	private String _goodItemCode;
	private String _goodItemDescription;
	private long _numberOfPackage;
	private String _kindOfPackages;
	private String _marksandNosofGoods;
	private double _grossWeight;
	private String _grossWeightUnit;
	private double _measurement;
	private String _measurementUnit;
	private transient ExpandoBridge _expandoBridge;
	private long _columnBitmask;
	private TempGoodsItems _escapedModelProxy;
}