/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.gt.dao.noticeandmessage.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import vn.gt.dao.noticeandmessage.model.TempDeclarationForPlantQuarantine;
import vn.gt.dao.noticeandmessage.model.TempDeclarationForPlantQuarantineModel;
import vn.gt.dao.noticeandmessage.model.TempDeclarationForPlantQuarantineSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

/**
 * The base model implementation for the TempDeclarationForPlantQuarantine service. Represents a row in the &quot;temp_plant_quarantine&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link vn.gt.dao.noticeandmessage.model.TempDeclarationForPlantQuarantineModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link TempDeclarationForPlantQuarantineImpl}.
 * </p>
 *
 * @author win_64
 * @see TempDeclarationForPlantQuarantineImpl
 * @see vn.gt.dao.noticeandmessage.model.TempDeclarationForPlantQuarantine
 * @see vn.gt.dao.noticeandmessage.model.TempDeclarationForPlantQuarantineModel
 * @generated
 */
@JSON(strict = true)
public class TempDeclarationForPlantQuarantineModelImpl extends BaseModelImpl<TempDeclarationForPlantQuarantine>
	implements TempDeclarationForPlantQuarantineModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a temp declaration for plant quarantine model instance should use the {@link vn.gt.dao.noticeandmessage.model.TempDeclarationForPlantQuarantine} interface instead.
	 */
	public static final String TABLE_NAME = "temp_plant_quarantine";
	public static final Object[][] TABLE_COLUMNS = {
			{ "ID", Types.BIGINT },
			{ "RequestCode", Types.VARCHAR },
			{ "RequestState", Types.INTEGER },
			{ "DocumentName", Types.BIGINT },
			{ "UserCreated", Types.VARCHAR },
			{ "NameOfShip", Types.VARCHAR },
			{ "FlagStateOfShip", Types.VARCHAR },
			{ "NameOfMaster", Types.VARCHAR },
			{ "DoctorName", Types.VARCHAR },
			{ "NumberOfCrew", Types.INTEGER },
			{ "NumberOfPassengers", Types.INTEGER },
			{ "LastPortOfCallCode", Types.VARCHAR },
			{ "NextPortOfCallCode", Types.VARCHAR },
			{ "FirstPortOfLoadingCode", Types.VARCHAR },
			{ "DateOfDeparture", Types.TIMESTAMP },
			{ "PlantNameFirst", Types.VARCHAR },
			{ "PlantNameBetween", Types.VARCHAR },
			{ "PlantNameThis", Types.VARCHAR },
			{ "SignPlace", Types.VARCHAR },
			{ "SignDate", Types.TIMESTAMP },
			{ "MasterSigned", Types.INTEGER },
			{ "MasterSignedImage", Types.INTEGER },
			{ "AttachedFile", Types.BIGINT },
			{ "DocumentYear", Types.INTEGER }
		};
	public static final String TABLE_SQL_CREATE = "create table temp_plant_quarantine (ID LONG not null primary key,RequestCode VARCHAR(75) null,RequestState INTEGER,DocumentName LONG,UserCreated VARCHAR(75) null,NameOfShip VARCHAR(75) null,FlagStateOfShip VARCHAR(75) null,NameOfMaster VARCHAR(75) null,DoctorName VARCHAR(75) null,NumberOfCrew INTEGER,NumberOfPassengers INTEGER,LastPortOfCallCode VARCHAR(75) null,NextPortOfCallCode VARCHAR(75) null,FirstPortOfLoadingCode VARCHAR(75) null,DateOfDeparture DATE null,PlantNameFirst VARCHAR(75) null,PlantNameBetween VARCHAR(75) null,PlantNameThis VARCHAR(75) null,SignPlace VARCHAR(75) null,SignDate DATE null,MasterSigned INTEGER,MasterSignedImage INTEGER,AttachedFile LONG,DocumentYear INTEGER)";
	public static final String TABLE_SQL_DROP = "drop table temp_plant_quarantine";
	public static final String ORDER_BY_JPQL = " ORDER BY tempDeclarationForPlantQuarantine.id ASC";
	public static final String ORDER_BY_SQL = " ORDER BY temp_plant_quarantine.ID ASC";
	public static final String DATA_SOURCE = "gtDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.vn.gt.dao.noticeandmessage.model.TempDeclarationForPlantQuarantine"),
			false);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.vn.gt.dao.noticeandmessage.model.TempDeclarationForPlantQuarantine"),
			false);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.vn.gt.dao.noticeandmessage.model.TempDeclarationForPlantQuarantine"),
			true);
	public static long DOCUMENTNAME_COLUMN_BITMASK = 1L;
	public static long DOCUMENTYEAR_COLUMN_BITMASK = 2L;
	public static long REQUESTCODE_COLUMN_BITMASK = 4L;
	public static long REQUESTSTATE_COLUMN_BITMASK = 8L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static TempDeclarationForPlantQuarantine toModel(
		TempDeclarationForPlantQuarantineSoap soapModel) {
		TempDeclarationForPlantQuarantine model = new TempDeclarationForPlantQuarantineImpl();

		model.setId(soapModel.getId());
		model.setRequestCode(soapModel.getRequestCode());
		model.setRequestState(soapModel.getRequestState());
		model.setDocumentName(soapModel.getDocumentName());
		model.setUserCreated(soapModel.getUserCreated());
		model.setNameOfShip(soapModel.getNameOfShip());
		model.setFlagStateOfShip(soapModel.getFlagStateOfShip());
		model.setNameOfMaster(soapModel.getNameOfMaster());
		model.setDoctorName(soapModel.getDoctorName());
		model.setNumberOfCrew(soapModel.getNumberOfCrew());
		model.setNumberOfPassengers(soapModel.getNumberOfPassengers());
		model.setLastPortOfCallCode(soapModel.getLastPortOfCallCode());
		model.setNextPortOfCallCode(soapModel.getNextPortOfCallCode());
		model.setFirstPortOfLoadingCode(soapModel.getFirstPortOfLoadingCode());
		model.setDateOfdeparture(soapModel.getDateOfdeparture());
		model.setPlantNameFirst(soapModel.getPlantNameFirst());
		model.setPlantNameBetween(soapModel.getPlantNameBetween());
		model.setPlantNameThis(soapModel.getPlantNameThis());
		model.setSignPlace(soapModel.getSignPlace());
		model.setSignDate(soapModel.getSignDate());
		model.setMasterSigned(soapModel.getMasterSigned());
		model.setMasterSignedImage(soapModel.getMasterSignedImage());
		model.setAttachedFile(soapModel.getAttachedFile());
		model.setDocumentYear(soapModel.getDocumentYear());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<TempDeclarationForPlantQuarantine> toModels(
		TempDeclarationForPlantQuarantineSoap[] soapModels) {
		List<TempDeclarationForPlantQuarantine> models = new ArrayList<TempDeclarationForPlantQuarantine>(soapModels.length);

		for (TempDeclarationForPlantQuarantineSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.vn.gt.dao.noticeandmessage.model.TempDeclarationForPlantQuarantine"));

	public TempDeclarationForPlantQuarantineModelImpl() {
	}

	public long getPrimaryKey() {
		return _id;
	}

	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	public Serializable getPrimaryKeyObj() {
		return new Long(_id);
	}

	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	public Class<?> getModelClass() {
		return TempDeclarationForPlantQuarantine.class;
	}

	public String getModelClassName() {
		return TempDeclarationForPlantQuarantine.class.getName();
	}

	@JSON
	public long getId() {
		return _id;
	}

	public void setId(long id) {
		_columnBitmask = -1L;

		_id = id;
	}

	@JSON
	public String getRequestCode() {
		if (_requestCode == null) {
			return StringPool.BLANK;
		}
		else {
			return _requestCode;
		}
	}

	public void setRequestCode(String requestCode) {
		_columnBitmask |= REQUESTCODE_COLUMN_BITMASK;

		if (_originalRequestCode == null) {
			_originalRequestCode = _requestCode;
		}

		_requestCode = requestCode;
	}

	public String getOriginalRequestCode() {
		return GetterUtil.getString(_originalRequestCode);
	}

	@JSON
	public int getRequestState() {
		return _requestState;
	}

	public void setRequestState(int requestState) {
		_columnBitmask |= REQUESTSTATE_COLUMN_BITMASK;

		if (!_setOriginalRequestState) {
			_setOriginalRequestState = true;

			_originalRequestState = _requestState;
		}

		_requestState = requestState;
	}

	public int getOriginalRequestState() {
		return _originalRequestState;
	}

	@JSON
	public long getDocumentName() {
		return _documentName;
	}

	public void setDocumentName(long documentName) {
		_columnBitmask |= DOCUMENTNAME_COLUMN_BITMASK;

		if (!_setOriginalDocumentName) {
			_setOriginalDocumentName = true;

			_originalDocumentName = _documentName;
		}

		_documentName = documentName;
	}

	public long getOriginalDocumentName() {
		return _originalDocumentName;
	}

	@JSON
	public String getUserCreated() {
		if (_userCreated == null) {
			return StringPool.BLANK;
		}
		else {
			return _userCreated;
		}
	}

	public void setUserCreated(String userCreated) {
		_userCreated = userCreated;
	}

	@JSON
	public String getNameOfShip() {
		if (_nameOfShip == null) {
			return StringPool.BLANK;
		}
		else {
			return _nameOfShip;
		}
	}

	public void setNameOfShip(String nameOfShip) {
		_nameOfShip = nameOfShip;
	}

	@JSON
	public String getFlagStateOfShip() {
		if (_flagStateOfShip == null) {
			return StringPool.BLANK;
		}
		else {
			return _flagStateOfShip;
		}
	}

	public void setFlagStateOfShip(String flagStateOfShip) {
		_flagStateOfShip = flagStateOfShip;
	}

	@JSON
	public String getNameOfMaster() {
		if (_nameOfMaster == null) {
			return StringPool.BLANK;
		}
		else {
			return _nameOfMaster;
		}
	}

	public void setNameOfMaster(String nameOfMaster) {
		_nameOfMaster = nameOfMaster;
	}

	@JSON
	public String getDoctorName() {
		if (_doctorName == null) {
			return StringPool.BLANK;
		}
		else {
			return _doctorName;
		}
	}

	public void setDoctorName(String doctorName) {
		_doctorName = doctorName;
	}

	@JSON
	public int getNumberOfCrew() {
		return _numberOfCrew;
	}

	public void setNumberOfCrew(int numberOfCrew) {
		_numberOfCrew = numberOfCrew;
	}

	@JSON
	public int getNumberOfPassengers() {
		return _numberOfPassengers;
	}

	public void setNumberOfPassengers(int numberOfPassengers) {
		_numberOfPassengers = numberOfPassengers;
	}

	@JSON
	public String getLastPortOfCallCode() {
		if (_lastPortOfCallCode == null) {
			return StringPool.BLANK;
		}
		else {
			return _lastPortOfCallCode;
		}
	}

	public void setLastPortOfCallCode(String lastPortOfCallCode) {
		_lastPortOfCallCode = lastPortOfCallCode;
	}

	@JSON
	public String getNextPortOfCallCode() {
		if (_nextPortOfCallCode == null) {
			return StringPool.BLANK;
		}
		else {
			return _nextPortOfCallCode;
		}
	}

	public void setNextPortOfCallCode(String nextPortOfCallCode) {
		_nextPortOfCallCode = nextPortOfCallCode;
	}

	@JSON
	public String getFirstPortOfLoadingCode() {
		if (_firstPortOfLoadingCode == null) {
			return StringPool.BLANK;
		}
		else {
			return _firstPortOfLoadingCode;
		}
	}

	public void setFirstPortOfLoadingCode(String firstPortOfLoadingCode) {
		_firstPortOfLoadingCode = firstPortOfLoadingCode;
	}

	@JSON
	public Date getDateOfdeparture() {
		return _dateOfdeparture;
	}

	public void setDateOfdeparture(Date dateOfdeparture) {
		_dateOfdeparture = dateOfdeparture;
	}

	@JSON
	public String getPlantNameFirst() {
		if (_plantNameFirst == null) {
			return StringPool.BLANK;
		}
		else {
			return _plantNameFirst;
		}
	}

	public void setPlantNameFirst(String plantNameFirst) {
		_plantNameFirst = plantNameFirst;
	}

	@JSON
	public String getPlantNameBetween() {
		if (_plantNameBetween == null) {
			return StringPool.BLANK;
		}
		else {
			return _plantNameBetween;
		}
	}

	public void setPlantNameBetween(String plantNameBetween) {
		_plantNameBetween = plantNameBetween;
	}

	@JSON
	public String getPlantNameThis() {
		if (_plantNameThis == null) {
			return StringPool.BLANK;
		}
		else {
			return _plantNameThis;
		}
	}

	public void setPlantNameThis(String plantNameThis) {
		_plantNameThis = plantNameThis;
	}

	@JSON
	public String getSignPlace() {
		if (_signPlace == null) {
			return StringPool.BLANK;
		}
		else {
			return _signPlace;
		}
	}

	public void setSignPlace(String signPlace) {
		_signPlace = signPlace;
	}

	@JSON
	public Date getSignDate() {
		return _signDate;
	}

	public void setSignDate(Date signDate) {
		_signDate = signDate;
	}

	@JSON
	public int getMasterSigned() {
		return _masterSigned;
	}

	public void setMasterSigned(int masterSigned) {
		_masterSigned = masterSigned;
	}

	@JSON
	public int getMasterSignedImage() {
		return _masterSignedImage;
	}

	public void setMasterSignedImage(int masterSignedImage) {
		_masterSignedImage = masterSignedImage;
	}

	@JSON
	public long getAttachedFile() {
		return _attachedFile;
	}

	public void setAttachedFile(long attachedFile) {
		_attachedFile = attachedFile;
	}

	@JSON
	public int getDocumentYear() {
		return _documentYear;
	}

	public void setDocumentYear(int documentYear) {
		_columnBitmask |= DOCUMENTYEAR_COLUMN_BITMASK;

		if (!_setOriginalDocumentYear) {
			_setOriginalDocumentYear = true;

			_originalDocumentYear = _documentYear;
		}

		_documentYear = documentYear;
	}

	public int getOriginalDocumentYear() {
		return _originalDocumentYear;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public TempDeclarationForPlantQuarantine toEscapedModel() {
		if (_escapedModelProxy == null) {
			_escapedModelProxy = (TempDeclarationForPlantQuarantine)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelProxyInterfaces,
					new AutoEscapeBeanHandler(this));
		}

		return _escapedModelProxy;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		if (_expandoBridge == null) {
			_expandoBridge = ExpandoBridgeFactoryUtil.getExpandoBridge(0,
					TempDeclarationForPlantQuarantine.class.getName(),
					getPrimaryKey());
		}

		return _expandoBridge;
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		getExpandoBridge().setAttributes(serviceContext);
	}

	@Override
	public Object clone() {
		TempDeclarationForPlantQuarantineImpl tempDeclarationForPlantQuarantineImpl =
			new TempDeclarationForPlantQuarantineImpl();

		tempDeclarationForPlantQuarantineImpl.setId(getId());
		tempDeclarationForPlantQuarantineImpl.setRequestCode(getRequestCode());
		tempDeclarationForPlantQuarantineImpl.setRequestState(getRequestState());
		tempDeclarationForPlantQuarantineImpl.setDocumentName(getDocumentName());
		tempDeclarationForPlantQuarantineImpl.setUserCreated(getUserCreated());
		tempDeclarationForPlantQuarantineImpl.setNameOfShip(getNameOfShip());
		tempDeclarationForPlantQuarantineImpl.setFlagStateOfShip(getFlagStateOfShip());
		tempDeclarationForPlantQuarantineImpl.setNameOfMaster(getNameOfMaster());
		tempDeclarationForPlantQuarantineImpl.setDoctorName(getDoctorName());
		tempDeclarationForPlantQuarantineImpl.setNumberOfCrew(getNumberOfCrew());
		tempDeclarationForPlantQuarantineImpl.setNumberOfPassengers(getNumberOfPassengers());
		tempDeclarationForPlantQuarantineImpl.setLastPortOfCallCode(getLastPortOfCallCode());
		tempDeclarationForPlantQuarantineImpl.setNextPortOfCallCode(getNextPortOfCallCode());
		tempDeclarationForPlantQuarantineImpl.setFirstPortOfLoadingCode(getFirstPortOfLoadingCode());
		tempDeclarationForPlantQuarantineImpl.setDateOfdeparture(getDateOfdeparture());
		tempDeclarationForPlantQuarantineImpl.setPlantNameFirst(getPlantNameFirst());
		tempDeclarationForPlantQuarantineImpl.setPlantNameBetween(getPlantNameBetween());
		tempDeclarationForPlantQuarantineImpl.setPlantNameThis(getPlantNameThis());
		tempDeclarationForPlantQuarantineImpl.setSignPlace(getSignPlace());
		tempDeclarationForPlantQuarantineImpl.setSignDate(getSignDate());
		tempDeclarationForPlantQuarantineImpl.setMasterSigned(getMasterSigned());
		tempDeclarationForPlantQuarantineImpl.setMasterSignedImage(getMasterSignedImage());
		tempDeclarationForPlantQuarantineImpl.setAttachedFile(getAttachedFile());
		tempDeclarationForPlantQuarantineImpl.setDocumentYear(getDocumentYear());

		tempDeclarationForPlantQuarantineImpl.resetOriginalValues();

		return tempDeclarationForPlantQuarantineImpl;
	}

	public int compareTo(
		TempDeclarationForPlantQuarantine tempDeclarationForPlantQuarantine) {
		int value = 0;

		if (getId() < tempDeclarationForPlantQuarantine.getId()) {
			value = -1;
		}
		else if (getId() > tempDeclarationForPlantQuarantine.getId()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		TempDeclarationForPlantQuarantine tempDeclarationForPlantQuarantine = null;

		try {
			tempDeclarationForPlantQuarantine = (TempDeclarationForPlantQuarantine)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		long primaryKey = tempDeclarationForPlantQuarantine.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		TempDeclarationForPlantQuarantineModelImpl tempDeclarationForPlantQuarantineModelImpl =
			this;

		tempDeclarationForPlantQuarantineModelImpl._originalRequestCode = tempDeclarationForPlantQuarantineModelImpl._requestCode;

		tempDeclarationForPlantQuarantineModelImpl._originalRequestState = tempDeclarationForPlantQuarantineModelImpl._requestState;

		tempDeclarationForPlantQuarantineModelImpl._setOriginalRequestState = false;

		tempDeclarationForPlantQuarantineModelImpl._originalDocumentName = tempDeclarationForPlantQuarantineModelImpl._documentName;

		tempDeclarationForPlantQuarantineModelImpl._setOriginalDocumentName = false;

		tempDeclarationForPlantQuarantineModelImpl._originalDocumentYear = tempDeclarationForPlantQuarantineModelImpl._documentYear;

		tempDeclarationForPlantQuarantineModelImpl._setOriginalDocumentYear = false;

		tempDeclarationForPlantQuarantineModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<TempDeclarationForPlantQuarantine> toCacheModel() {
		TempDeclarationForPlantQuarantineCacheModel tempDeclarationForPlantQuarantineCacheModel =
			new TempDeclarationForPlantQuarantineCacheModel();

		tempDeclarationForPlantQuarantineCacheModel.id = getId();

		tempDeclarationForPlantQuarantineCacheModel.requestCode = getRequestCode();

		String requestCode = tempDeclarationForPlantQuarantineCacheModel.requestCode;

		if ((requestCode != null) && (requestCode.length() == 0)) {
			tempDeclarationForPlantQuarantineCacheModel.requestCode = null;
		}

		tempDeclarationForPlantQuarantineCacheModel.requestState = getRequestState();

		tempDeclarationForPlantQuarantineCacheModel.documentName = getDocumentName();

		tempDeclarationForPlantQuarantineCacheModel.userCreated = getUserCreated();

		String userCreated = tempDeclarationForPlantQuarantineCacheModel.userCreated;

		if ((userCreated != null) && (userCreated.length() == 0)) {
			tempDeclarationForPlantQuarantineCacheModel.userCreated = null;
		}

		tempDeclarationForPlantQuarantineCacheModel.nameOfShip = getNameOfShip();

		String nameOfShip = tempDeclarationForPlantQuarantineCacheModel.nameOfShip;

		if ((nameOfShip != null) && (nameOfShip.length() == 0)) {
			tempDeclarationForPlantQuarantineCacheModel.nameOfShip = null;
		}

		tempDeclarationForPlantQuarantineCacheModel.flagStateOfShip = getFlagStateOfShip();

		String flagStateOfShip = tempDeclarationForPlantQuarantineCacheModel.flagStateOfShip;

		if ((flagStateOfShip != null) && (flagStateOfShip.length() == 0)) {
			tempDeclarationForPlantQuarantineCacheModel.flagStateOfShip = null;
		}

		tempDeclarationForPlantQuarantineCacheModel.nameOfMaster = getNameOfMaster();

		String nameOfMaster = tempDeclarationForPlantQuarantineCacheModel.nameOfMaster;

		if ((nameOfMaster != null) && (nameOfMaster.length() == 0)) {
			tempDeclarationForPlantQuarantineCacheModel.nameOfMaster = null;
		}

		tempDeclarationForPlantQuarantineCacheModel.doctorName = getDoctorName();

		String doctorName = tempDeclarationForPlantQuarantineCacheModel.doctorName;

		if ((doctorName != null) && (doctorName.length() == 0)) {
			tempDeclarationForPlantQuarantineCacheModel.doctorName = null;
		}

		tempDeclarationForPlantQuarantineCacheModel.numberOfCrew = getNumberOfCrew();

		tempDeclarationForPlantQuarantineCacheModel.numberOfPassengers = getNumberOfPassengers();

		tempDeclarationForPlantQuarantineCacheModel.lastPortOfCallCode = getLastPortOfCallCode();

		String lastPortOfCallCode = tempDeclarationForPlantQuarantineCacheModel.lastPortOfCallCode;

		if ((lastPortOfCallCode != null) && (lastPortOfCallCode.length() == 0)) {
			tempDeclarationForPlantQuarantineCacheModel.lastPortOfCallCode = null;
		}

		tempDeclarationForPlantQuarantineCacheModel.nextPortOfCallCode = getNextPortOfCallCode();

		String nextPortOfCallCode = tempDeclarationForPlantQuarantineCacheModel.nextPortOfCallCode;

		if ((nextPortOfCallCode != null) && (nextPortOfCallCode.length() == 0)) {
			tempDeclarationForPlantQuarantineCacheModel.nextPortOfCallCode = null;
		}

		tempDeclarationForPlantQuarantineCacheModel.firstPortOfLoadingCode = getFirstPortOfLoadingCode();

		String firstPortOfLoadingCode = tempDeclarationForPlantQuarantineCacheModel.firstPortOfLoadingCode;

		if ((firstPortOfLoadingCode != null) &&
				(firstPortOfLoadingCode.length() == 0)) {
			tempDeclarationForPlantQuarantineCacheModel.firstPortOfLoadingCode = null;
		}

		Date dateOfdeparture = getDateOfdeparture();

		if (dateOfdeparture != null) {
			tempDeclarationForPlantQuarantineCacheModel.dateOfdeparture = dateOfdeparture.getTime();
		}
		else {
			tempDeclarationForPlantQuarantineCacheModel.dateOfdeparture = Long.MIN_VALUE;
		}

		tempDeclarationForPlantQuarantineCacheModel.plantNameFirst = getPlantNameFirst();

		String plantNameFirst = tempDeclarationForPlantQuarantineCacheModel.plantNameFirst;

		if ((plantNameFirst != null) && (plantNameFirst.length() == 0)) {
			tempDeclarationForPlantQuarantineCacheModel.plantNameFirst = null;
		}

		tempDeclarationForPlantQuarantineCacheModel.plantNameBetween = getPlantNameBetween();

		String plantNameBetween = tempDeclarationForPlantQuarantineCacheModel.plantNameBetween;

		if ((plantNameBetween != null) && (plantNameBetween.length() == 0)) {
			tempDeclarationForPlantQuarantineCacheModel.plantNameBetween = null;
		}

		tempDeclarationForPlantQuarantineCacheModel.plantNameThis = getPlantNameThis();

		String plantNameThis = tempDeclarationForPlantQuarantineCacheModel.plantNameThis;

		if ((plantNameThis != null) && (plantNameThis.length() == 0)) {
			tempDeclarationForPlantQuarantineCacheModel.plantNameThis = null;
		}

		tempDeclarationForPlantQuarantineCacheModel.signPlace = getSignPlace();

		String signPlace = tempDeclarationForPlantQuarantineCacheModel.signPlace;

		if ((signPlace != null) && (signPlace.length() == 0)) {
			tempDeclarationForPlantQuarantineCacheModel.signPlace = null;
		}

		Date signDate = getSignDate();

		if (signDate != null) {
			tempDeclarationForPlantQuarantineCacheModel.signDate = signDate.getTime();
		}
		else {
			tempDeclarationForPlantQuarantineCacheModel.signDate = Long.MIN_VALUE;
		}

		tempDeclarationForPlantQuarantineCacheModel.masterSigned = getMasterSigned();

		tempDeclarationForPlantQuarantineCacheModel.masterSignedImage = getMasterSignedImage();

		tempDeclarationForPlantQuarantineCacheModel.attachedFile = getAttachedFile();

		tempDeclarationForPlantQuarantineCacheModel.documentYear = getDocumentYear();

		return tempDeclarationForPlantQuarantineCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(49);

		sb.append("{id=");
		sb.append(getId());
		sb.append(", requestCode=");
		sb.append(getRequestCode());
		sb.append(", requestState=");
		sb.append(getRequestState());
		sb.append(", documentName=");
		sb.append(getDocumentName());
		sb.append(", userCreated=");
		sb.append(getUserCreated());
		sb.append(", nameOfShip=");
		sb.append(getNameOfShip());
		sb.append(", flagStateOfShip=");
		sb.append(getFlagStateOfShip());
		sb.append(", nameOfMaster=");
		sb.append(getNameOfMaster());
		sb.append(", doctorName=");
		sb.append(getDoctorName());
		sb.append(", numberOfCrew=");
		sb.append(getNumberOfCrew());
		sb.append(", numberOfPassengers=");
		sb.append(getNumberOfPassengers());
		sb.append(", lastPortOfCallCode=");
		sb.append(getLastPortOfCallCode());
		sb.append(", nextPortOfCallCode=");
		sb.append(getNextPortOfCallCode());
		sb.append(", firstPortOfLoadingCode=");
		sb.append(getFirstPortOfLoadingCode());
		sb.append(", dateOfdeparture=");
		sb.append(getDateOfdeparture());
		sb.append(", plantNameFirst=");
		sb.append(getPlantNameFirst());
		sb.append(", plantNameBetween=");
		sb.append(getPlantNameBetween());
		sb.append(", plantNameThis=");
		sb.append(getPlantNameThis());
		sb.append(", signPlace=");
		sb.append(getSignPlace());
		sb.append(", signDate=");
		sb.append(getSignDate());
		sb.append(", masterSigned=");
		sb.append(getMasterSigned());
		sb.append(", masterSignedImage=");
		sb.append(getMasterSignedImage());
		sb.append(", attachedFile=");
		sb.append(getAttachedFile());
		sb.append(", documentYear=");
		sb.append(getDocumentYear());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(76);

		sb.append("<model><model-name>");
		sb.append(
			"vn.gt.dao.noticeandmessage.model.TempDeclarationForPlantQuarantine");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>id</column-name><column-value><![CDATA[");
		sb.append(getId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>requestCode</column-name><column-value><![CDATA[");
		sb.append(getRequestCode());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>requestState</column-name><column-value><![CDATA[");
		sb.append(getRequestState());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>documentName</column-name><column-value><![CDATA[");
		sb.append(getDocumentName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userCreated</column-name><column-value><![CDATA[");
		sb.append(getUserCreated());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>nameOfShip</column-name><column-value><![CDATA[");
		sb.append(getNameOfShip());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>flagStateOfShip</column-name><column-value><![CDATA[");
		sb.append(getFlagStateOfShip());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>nameOfMaster</column-name><column-value><![CDATA[");
		sb.append(getNameOfMaster());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>doctorName</column-name><column-value><![CDATA[");
		sb.append(getDoctorName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>numberOfCrew</column-name><column-value><![CDATA[");
		sb.append(getNumberOfCrew());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>numberOfPassengers</column-name><column-value><![CDATA[");
		sb.append(getNumberOfPassengers());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>lastPortOfCallCode</column-name><column-value><![CDATA[");
		sb.append(getLastPortOfCallCode());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>nextPortOfCallCode</column-name><column-value><![CDATA[");
		sb.append(getNextPortOfCallCode());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>firstPortOfLoadingCode</column-name><column-value><![CDATA[");
		sb.append(getFirstPortOfLoadingCode());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>dateOfdeparture</column-name><column-value><![CDATA[");
		sb.append(getDateOfdeparture());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>plantNameFirst</column-name><column-value><![CDATA[");
		sb.append(getPlantNameFirst());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>plantNameBetween</column-name><column-value><![CDATA[");
		sb.append(getPlantNameBetween());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>plantNameThis</column-name><column-value><![CDATA[");
		sb.append(getPlantNameThis());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>signPlace</column-name><column-value><![CDATA[");
		sb.append(getSignPlace());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>signDate</column-name><column-value><![CDATA[");
		sb.append(getSignDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>masterSigned</column-name><column-value><![CDATA[");
		sb.append(getMasterSigned());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>masterSignedImage</column-name><column-value><![CDATA[");
		sb.append(getMasterSignedImage());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>attachedFile</column-name><column-value><![CDATA[");
		sb.append(getAttachedFile());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>documentYear</column-name><column-value><![CDATA[");
		sb.append(getDocumentYear());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = TempDeclarationForPlantQuarantine.class.getClassLoader();
	private static Class<?>[] _escapedModelProxyInterfaces = new Class[] {
			TempDeclarationForPlantQuarantine.class
		};
	private long _id;
	private String _requestCode;
	private String _originalRequestCode;
	private int _requestState;
	private int _originalRequestState;
	private boolean _setOriginalRequestState;
	private long _documentName;
	private long _originalDocumentName;
	private boolean _setOriginalDocumentName;
	private String _userCreated;
	private String _nameOfShip;
	private String _flagStateOfShip;
	private String _nameOfMaster;
	private String _doctorName;
	private int _numberOfCrew;
	private int _numberOfPassengers;
	private String _lastPortOfCallCode;
	private String _nextPortOfCallCode;
	private String _firstPortOfLoadingCode;
	private Date _dateOfdeparture;
	private String _plantNameFirst;
	private String _plantNameBetween;
	private String _plantNameThis;
	private String _signPlace;
	private Date _signDate;
	private int _masterSigned;
	private int _masterSignedImage;
	private long _attachedFile;
	private int _documentYear;
	private int _originalDocumentYear;
	private boolean _setOriginalDocumentYear;
	private transient ExpandoBridge _expandoBridge;
	private long _columnBitmask;
	private TempDeclarationForPlantQuarantine _escapedModelProxy;
}