/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.gt.dao.noticeandmessage.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import vn.gt.dao.noticeandmessage.model.TempGeneralDeclaration;
import vn.gt.dao.noticeandmessage.model.TempGeneralDeclarationModel;
import vn.gt.dao.noticeandmessage.model.TempGeneralDeclarationSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

/**
 * The base model implementation for the TempGeneralDeclaration service. Represents a row in the &quot;TEMP_GENERAL_DECLARATION&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link vn.gt.dao.noticeandmessage.model.TempGeneralDeclarationModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link TempGeneralDeclarationImpl}.
 * </p>
 *
 * @author win_64
 * @see TempGeneralDeclarationImpl
 * @see vn.gt.dao.noticeandmessage.model.TempGeneralDeclaration
 * @see vn.gt.dao.noticeandmessage.model.TempGeneralDeclarationModel
 * @generated
 */
@JSON(strict = true)
public class TempGeneralDeclarationModelImpl extends BaseModelImpl<TempGeneralDeclaration>
	implements TempGeneralDeclarationModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a temp general declaration model instance should use the {@link vn.gt.dao.noticeandmessage.model.TempGeneralDeclaration} interface instead.
	 */
	public static final String TABLE_NAME = "TEMP_GENERAL_DECLARATION";
	public static final Object[][] TABLE_COLUMNS = {
			{ "ID", Types.BIGINT },
			{ "RequestCode", Types.VARCHAR },
			{ "RequestState", Types.INTEGER },
			{ "DocumentName", Types.BIGINT },
			{ "DocumentYear", Types.INTEGER },
			{ "UserCreated", Types.VARCHAR },
			{ "IsArrival", Types.INTEGER },
			{ "NameOfShip", Types.VARCHAR },
			{ "ShipTypeCode", Types.VARCHAR },
			{ "IMONumber", Types.VARCHAR },
			{ "CallSign", Types.VARCHAR },
			{ "VoyageNumber", Types.VARCHAR },
			{ "PortOfArrivalCode", Types.VARCHAR },
			{ "DateOfArrival", Types.TIMESTAMP },
			{ "PortHarbourCode", Types.VARCHAR },
			{ "PortRegionCode", Types.VARCHAR },
			{ "PortWharfCode", Types.VARCHAR },
			{ "FlagStateOfShip", Types.VARCHAR },
			{ "NameOfMaster", Types.VARCHAR },
			{ "LastPortOfCallCode", Types.VARCHAR },
			{ "CertificateOfRegistryNumber", Types.VARCHAR },
			{ "CertificateOfRegistryDate", Types.TIMESTAMP },
			{ "CertificateOfRegistryPortName", Types.VARCHAR },
			{ "TaxCodeOfShipownersAgents", Types.VARCHAR },
			{ "NameOfShipownersAgents", Types.VARCHAR },
			{ "ShipAgencyAddress", Types.VARCHAR },
			{ "ShipAgencyPhone", Types.VARCHAR },
			{ "ShipAgencyFax", Types.VARCHAR },
			{ "ShipAgencyEmail", Types.VARCHAR },
			{ "GrossTonnage", Types.DOUBLE },
			{ "NetTonnage", Types.DOUBLE },
			{ "PositionOfShipInPort", Types.VARCHAR },
			{ "BriefParticularsOfVoyage", Types.VARCHAR },
			{ "BriefDescriptionOfTheCargo", Types.VARCHAR },
			{ "NumberOfCrew", Types.INTEGER },
			{ "NumberOfPassengers", Types.INTEGER },
			{ "ShipRequirementsInTermsOfWaste", Types.VARCHAR },
			{ "Remarks", Types.VARCHAR },
			{ "NumberCargoDeclaration", Types.VARCHAR },
			{ "NumberShipStoreDeclaration", Types.VARCHAR },
			{ "NumberCrewList", Types.VARCHAR },
			{ "NumberPassengerList", Types.VARCHAR },
			{ "NumberCrewEffects", Types.VARCHAR },
			{ "NumberHealthMaritime", Types.VARCHAR },
			{ "SignPlace", Types.VARCHAR },
			{ "SignDate", Types.TIMESTAMP },
			{ "MasterSigned", Types.INTEGER },
			{ "MasterSignedImage", Types.INTEGER }
		};
	public static final String TABLE_SQL_CREATE = "create table TEMP_GENERAL_DECLARATION (ID LONG not null primary key,RequestCode VARCHAR(75) null,RequestState INTEGER,DocumentName LONG,DocumentYear INTEGER,UserCreated VARCHAR(75) null,IsArrival INTEGER,NameOfShip VARCHAR(75) null,ShipTypeCode VARCHAR(75) null,IMONumber VARCHAR(75) null,CallSign VARCHAR(75) null,VoyageNumber VARCHAR(75) null,PortOfArrivalCode VARCHAR(75) null,DateOfArrival DATE null,PortHarbourCode VARCHAR(75) null,PortRegionCode VARCHAR(75) null,PortWharfCode VARCHAR(75) null,FlagStateOfShip VARCHAR(75) null,NameOfMaster VARCHAR(75) null,LastPortOfCallCode VARCHAR(75) null,CertificateOfRegistryNumber VARCHAR(75) null,CertificateOfRegistryDate DATE null,CertificateOfRegistryPortName VARCHAR(75) null,TaxCodeOfShipownersAgents VARCHAR(75) null,NameOfShipownersAgents VARCHAR(75) null,ShipAgencyAddress VARCHAR(75) null,ShipAgencyPhone VARCHAR(75) null,ShipAgencyFax VARCHAR(75) null,ShipAgencyEmail VARCHAR(75) null,GrossTonnage DOUBLE,NetTonnage DOUBLE,PositionOfShipInPort VARCHAR(75) null,BriefParticularsOfVoyage VARCHAR(75) null,BriefDescriptionOfTheCargo VARCHAR(75) null,NumberOfCrew INTEGER,NumberOfPassengers INTEGER,ShipRequirementsInTermsOfWaste VARCHAR(75) null,Remarks VARCHAR(75) null,NumberCargoDeclaration VARCHAR(75) null,NumberShipStoreDeclaration VARCHAR(75) null,NumberCrewList VARCHAR(75) null,NumberPassengerList VARCHAR(75) null,NumberCrewEffects VARCHAR(75) null,NumberHealthMaritime VARCHAR(75) null,SignPlace VARCHAR(75) null,SignDate DATE null,MasterSigned INTEGER,MasterSignedImage INTEGER)";
	public static final String TABLE_SQL_DROP = "drop table TEMP_GENERAL_DECLARATION";
	public static final String ORDER_BY_JPQL = " ORDER BY tempGeneralDeclaration.id ASC";
	public static final String ORDER_BY_SQL = " ORDER BY TEMP_GENERAL_DECLARATION.ID ASC";
	public static final String DATA_SOURCE = "gtDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.vn.gt.dao.noticeandmessage.model.TempGeneralDeclaration"),
			false);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.vn.gt.dao.noticeandmessage.model.TempGeneralDeclaration"),
			false);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.vn.gt.dao.noticeandmessage.model.TempGeneralDeclaration"),
			true);
	public static long DOCUMENTNAME_COLUMN_BITMASK = 1L;
	public static long DOCUMENTYEAR_COLUMN_BITMASK = 2L;
	public static long REQUESTCODE_COLUMN_BITMASK = 4L;
	public static long REQUESTSTATE_COLUMN_BITMASK = 8L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static TempGeneralDeclaration toModel(
		TempGeneralDeclarationSoap soapModel) {
		TempGeneralDeclaration model = new TempGeneralDeclarationImpl();

		model.setId(soapModel.getId());
		model.setRequestCode(soapModel.getRequestCode());
		model.setRequestState(soapModel.getRequestState());
		model.setDocumentName(soapModel.getDocumentName());
		model.setDocumentYear(soapModel.getDocumentYear());
		model.setUserCreated(soapModel.getUserCreated());
		model.setIsArrival(soapModel.getIsArrival());
		model.setNameOfShip(soapModel.getNameOfShip());
		model.setShipTypeCode(soapModel.getShipTypeCode());
		model.setImoNumber(soapModel.getImoNumber());
		model.setCallSign(soapModel.getCallSign());
		model.setVoyageNumber(soapModel.getVoyageNumber());
		model.setPortOfArrivalCode(soapModel.getPortOfArrivalCode());
		model.setDateOfArrival(soapModel.getDateOfArrival());
		model.setPortHarbourCode(soapModel.getPortHarbourCode());
		model.setPortRegionCode(soapModel.getPortRegionCode());
		model.setPortWharfCode(soapModel.getPortWharfCode());
		model.setFlagStateOfShip(soapModel.getFlagStateOfShip());
		model.setNameOfMaster(soapModel.getNameOfMaster());
		model.setLastPortOfCallCode(soapModel.getLastPortOfCallCode());
		model.setCertificateOfRegistryNumber(soapModel.getCertificateOfRegistryNumber());
		model.setCertificateOfRegistryDate(soapModel.getCertificateOfRegistryDate());
		model.setCertificateOfRegistryPortName(soapModel.getCertificateOfRegistryPortName());
		model.setTaxCodeOfShipownersAgents(soapModel.getTaxCodeOfShipownersAgents());
		model.setNameOfShipownersAgents(soapModel.getNameOfShipownersAgents());
		model.setShipAgencyAddress(soapModel.getShipAgencyAddress());
		model.setShipAgencyPhone(soapModel.getShipAgencyPhone());
		model.setShipAgencyFax(soapModel.getShipAgencyFax());
		model.setShipAgencyEmail(soapModel.getShipAgencyEmail());
		model.setGrossTonnage(soapModel.getGrossTonnage());
		model.setNetTonnage(soapModel.getNetTonnage());
		model.setPositionOfShipInport(soapModel.getPositionOfShipInport());
		model.setBriefParticularsOfVoyage(soapModel.getBriefParticularsOfVoyage());
		model.setBriefDescriptionOfTheCargo(soapModel.getBriefDescriptionOfTheCargo());
		model.setNumberOfCrew(soapModel.getNumberOfCrew());
		model.setNumberOfPassengers(soapModel.getNumberOfPassengers());
		model.setShipRequirementsInTermsOfWaste(soapModel.getShipRequirementsInTermsOfWaste());
		model.setRemarks(soapModel.getRemarks());
		model.setNumberCargoDeclaration(soapModel.getNumberCargoDeclaration());
		model.setNumberShipStoreDeclaration(soapModel.getNumberShipStoreDeclaration());
		model.setNumberCrewList(soapModel.getNumberCrewList());
		model.setNumberPassengerList(soapModel.getNumberPassengerList());
		model.setNumberCrewEffects(soapModel.getNumberCrewEffects());
		model.setNumberHealthMaritime(soapModel.getNumberHealthMaritime());
		model.setSignPlace(soapModel.getSignPlace());
		model.setSignDate(soapModel.getSignDate());
		model.setMasterSigned(soapModel.getMasterSigned());
		model.setMasterSignedImage(soapModel.getMasterSignedImage());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<TempGeneralDeclaration> toModels(
		TempGeneralDeclarationSoap[] soapModels) {
		List<TempGeneralDeclaration> models = new ArrayList<TempGeneralDeclaration>(soapModels.length);

		for (TempGeneralDeclarationSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.vn.gt.dao.noticeandmessage.model.TempGeneralDeclaration"));

	public TempGeneralDeclarationModelImpl() {
	}

	public long getPrimaryKey() {
		return _id;
	}

	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	public Serializable getPrimaryKeyObj() {
		return new Long(_id);
	}

	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	public Class<?> getModelClass() {
		return TempGeneralDeclaration.class;
	}

	public String getModelClassName() {
		return TempGeneralDeclaration.class.getName();
	}

	@JSON
	public long getId() {
		return _id;
	}

	public void setId(long id) {
		_columnBitmask = -1L;

		_id = id;
	}

	@JSON
	public String getRequestCode() {
		if (_requestCode == null) {
			return StringPool.BLANK;
		}
		else {
			return _requestCode;
		}
	}

	public void setRequestCode(String requestCode) {
		_columnBitmask |= REQUESTCODE_COLUMN_BITMASK;

		if (_originalRequestCode == null) {
			_originalRequestCode = _requestCode;
		}

		_requestCode = requestCode;
	}

	public String getOriginalRequestCode() {
		return GetterUtil.getString(_originalRequestCode);
	}

	@JSON
	public int getRequestState() {
		return _requestState;
	}

	public void setRequestState(int requestState) {
		_columnBitmask |= REQUESTSTATE_COLUMN_BITMASK;

		if (!_setOriginalRequestState) {
			_setOriginalRequestState = true;

			_originalRequestState = _requestState;
		}

		_requestState = requestState;
	}

	public int getOriginalRequestState() {
		return _originalRequestState;
	}

	@JSON
	public long getDocumentName() {
		return _documentName;
	}

	public void setDocumentName(long documentName) {
		_columnBitmask |= DOCUMENTNAME_COLUMN_BITMASK;

		if (!_setOriginalDocumentName) {
			_setOriginalDocumentName = true;

			_originalDocumentName = _documentName;
		}

		_documentName = documentName;
	}

	public long getOriginalDocumentName() {
		return _originalDocumentName;
	}

	@JSON
	public int getDocumentYear() {
		return _documentYear;
	}

	public void setDocumentYear(int documentYear) {
		_columnBitmask |= DOCUMENTYEAR_COLUMN_BITMASK;

		if (!_setOriginalDocumentYear) {
			_setOriginalDocumentYear = true;

			_originalDocumentYear = _documentYear;
		}

		_documentYear = documentYear;
	}

	public int getOriginalDocumentYear() {
		return _originalDocumentYear;
	}

	@JSON
	public String getUserCreated() {
		if (_userCreated == null) {
			return StringPool.BLANK;
		}
		else {
			return _userCreated;
		}
	}

	public void setUserCreated(String userCreated) {
		_userCreated = userCreated;
	}

	@JSON
	public int getIsArrival() {
		return _isArrival;
	}

	public void setIsArrival(int isArrival) {
		_isArrival = isArrival;
	}

	@JSON
	public String getNameOfShip() {
		if (_nameOfShip == null) {
			return StringPool.BLANK;
		}
		else {
			return _nameOfShip;
		}
	}

	public void setNameOfShip(String nameOfShip) {
		_nameOfShip = nameOfShip;
	}

	@JSON
	public String getShipTypeCode() {
		if (_shipTypeCode == null) {
			return StringPool.BLANK;
		}
		else {
			return _shipTypeCode;
		}
	}

	public void setShipTypeCode(String shipTypeCode) {
		_shipTypeCode = shipTypeCode;
	}

	@JSON
	public String getImoNumber() {
		if (_imoNumber == null) {
			return StringPool.BLANK;
		}
		else {
			return _imoNumber;
		}
	}

	public void setImoNumber(String imoNumber) {
		_imoNumber = imoNumber;
	}

	@JSON
	public String getCallSign() {
		if (_callSign == null) {
			return StringPool.BLANK;
		}
		else {
			return _callSign;
		}
	}

	public void setCallSign(String callSign) {
		_callSign = callSign;
	}

	@JSON
	public String getVoyageNumber() {
		if (_voyageNumber == null) {
			return StringPool.BLANK;
		}
		else {
			return _voyageNumber;
		}
	}

	public void setVoyageNumber(String voyageNumber) {
		_voyageNumber = voyageNumber;
	}

	@JSON
	public String getPortOfArrivalCode() {
		if (_portOfArrivalCode == null) {
			return StringPool.BLANK;
		}
		else {
			return _portOfArrivalCode;
		}
	}

	public void setPortOfArrivalCode(String portOfArrivalCode) {
		_portOfArrivalCode = portOfArrivalCode;
	}

	@JSON
	public Date getDateOfArrival() {
		return _dateOfArrival;
	}

	public void setDateOfArrival(Date dateOfArrival) {
		_dateOfArrival = dateOfArrival;
	}

	@JSON
	public String getPortHarbourCode() {
		if (_portHarbourCode == null) {
			return StringPool.BLANK;
		}
		else {
			return _portHarbourCode;
		}
	}

	public void setPortHarbourCode(String portHarbourCode) {
		_portHarbourCode = portHarbourCode;
	}

	@JSON
	public String getPortRegionCode() {
		if (_portRegionCode == null) {
			return StringPool.BLANK;
		}
		else {
			return _portRegionCode;
		}
	}

	public void setPortRegionCode(String portRegionCode) {
		_portRegionCode = portRegionCode;
	}

	@JSON
	public String getPortWharfCode() {
		if (_portWharfCode == null) {
			return StringPool.BLANK;
		}
		else {
			return _portWharfCode;
		}
	}

	public void setPortWharfCode(String portWharfCode) {
		_portWharfCode = portWharfCode;
	}

	@JSON
	public String getFlagStateOfShip() {
		if (_flagStateOfShip == null) {
			return StringPool.BLANK;
		}
		else {
			return _flagStateOfShip;
		}
	}

	public void setFlagStateOfShip(String flagStateOfShip) {
		_flagStateOfShip = flagStateOfShip;
	}

	@JSON
	public String getNameOfMaster() {
		if (_nameOfMaster == null) {
			return StringPool.BLANK;
		}
		else {
			return _nameOfMaster;
		}
	}

	public void setNameOfMaster(String nameOfMaster) {
		_nameOfMaster = nameOfMaster;
	}

	@JSON
	public String getLastPortOfCallCode() {
		if (_lastPortOfCallCode == null) {
			return StringPool.BLANK;
		}
		else {
			return _lastPortOfCallCode;
		}
	}

	public void setLastPortOfCallCode(String lastPortOfCallCode) {
		_lastPortOfCallCode = lastPortOfCallCode;
	}

	@JSON
	public String getCertificateOfRegistryNumber() {
		if (_certificateOfRegistryNumber == null) {
			return StringPool.BLANK;
		}
		else {
			return _certificateOfRegistryNumber;
		}
	}

	public void setCertificateOfRegistryNumber(
		String certificateOfRegistryNumber) {
		_certificateOfRegistryNumber = certificateOfRegistryNumber;
	}

	@JSON
	public Date getCertificateOfRegistryDate() {
		return _certificateOfRegistryDate;
	}

	public void setCertificateOfRegistryDate(Date certificateOfRegistryDate) {
		_certificateOfRegistryDate = certificateOfRegistryDate;
	}

	@JSON
	public String getCertificateOfRegistryPortName() {
		if (_certificateOfRegistryPortName == null) {
			return StringPool.BLANK;
		}
		else {
			return _certificateOfRegistryPortName;
		}
	}

	public void setCertificateOfRegistryPortName(
		String certificateOfRegistryPortName) {
		_certificateOfRegistryPortName = certificateOfRegistryPortName;
	}

	@JSON
	public String getTaxCodeOfShipownersAgents() {
		if (_taxCodeOfShipownersAgents == null) {
			return StringPool.BLANK;
		}
		else {
			return _taxCodeOfShipownersAgents;
		}
	}

	public void setTaxCodeOfShipownersAgents(String taxCodeOfShipownersAgents) {
		_taxCodeOfShipownersAgents = taxCodeOfShipownersAgents;
	}

	@JSON
	public String getNameOfShipownersAgents() {
		if (_nameOfShipownersAgents == null) {
			return StringPool.BLANK;
		}
		else {
			return _nameOfShipownersAgents;
		}
	}

	public void setNameOfShipownersAgents(String nameOfShipownersAgents) {
		_nameOfShipownersAgents = nameOfShipownersAgents;
	}

	@JSON
	public String getShipAgencyAddress() {
		if (_shipAgencyAddress == null) {
			return StringPool.BLANK;
		}
		else {
			return _shipAgencyAddress;
		}
	}

	public void setShipAgencyAddress(String shipAgencyAddress) {
		_shipAgencyAddress = shipAgencyAddress;
	}

	@JSON
	public String getShipAgencyPhone() {
		if (_shipAgencyPhone == null) {
			return StringPool.BLANK;
		}
		else {
			return _shipAgencyPhone;
		}
	}

	public void setShipAgencyPhone(String shipAgencyPhone) {
		_shipAgencyPhone = shipAgencyPhone;
	}

	@JSON
	public String getShipAgencyFax() {
		if (_shipAgencyFax == null) {
			return StringPool.BLANK;
		}
		else {
			return _shipAgencyFax;
		}
	}

	public void setShipAgencyFax(String shipAgencyFax) {
		_shipAgencyFax = shipAgencyFax;
	}

	@JSON
	public String getShipAgencyEmail() {
		if (_shipAgencyEmail == null) {
			return StringPool.BLANK;
		}
		else {
			return _shipAgencyEmail;
		}
	}

	public void setShipAgencyEmail(String shipAgencyEmail) {
		_shipAgencyEmail = shipAgencyEmail;
	}

	@JSON
	public double getGrossTonnage() {
		return _grossTonnage;
	}

	public void setGrossTonnage(double grossTonnage) {
		_grossTonnage = grossTonnage;
	}

	@JSON
	public double getNetTonnage() {
		return _netTonnage;
	}

	public void setNetTonnage(double netTonnage) {
		_netTonnage = netTonnage;
	}

	@JSON
	public String getPositionOfShipInport() {
		if (_positionOfShipInport == null) {
			return StringPool.BLANK;
		}
		else {
			return _positionOfShipInport;
		}
	}

	public void setPositionOfShipInport(String positionOfShipInport) {
		_positionOfShipInport = positionOfShipInport;
	}

	@JSON
	public String getBriefParticularsOfVoyage() {
		if (_briefParticularsOfVoyage == null) {
			return StringPool.BLANK;
		}
		else {
			return _briefParticularsOfVoyage;
		}
	}

	public void setBriefParticularsOfVoyage(String briefParticularsOfVoyage) {
		_briefParticularsOfVoyage = briefParticularsOfVoyage;
	}

	@JSON
	public String getBriefDescriptionOfTheCargo() {
		if (_briefDescriptionOfTheCargo == null) {
			return StringPool.BLANK;
		}
		else {
			return _briefDescriptionOfTheCargo;
		}
	}

	public void setBriefDescriptionOfTheCargo(String briefDescriptionOfTheCargo) {
		_briefDescriptionOfTheCargo = briefDescriptionOfTheCargo;
	}

	@JSON
	public int getNumberOfCrew() {
		return _numberOfCrew;
	}

	public void setNumberOfCrew(int numberOfCrew) {
		_numberOfCrew = numberOfCrew;
	}

	@JSON
	public int getNumberOfPassengers() {
		return _numberOfPassengers;
	}

	public void setNumberOfPassengers(int numberOfPassengers) {
		_numberOfPassengers = numberOfPassengers;
	}

	@JSON
	public String getShipRequirementsInTermsOfWaste() {
		if (_shipRequirementsInTermsOfWaste == null) {
			return StringPool.BLANK;
		}
		else {
			return _shipRequirementsInTermsOfWaste;
		}
	}

	public void setShipRequirementsInTermsOfWaste(
		String shipRequirementsInTermsOfWaste) {
		_shipRequirementsInTermsOfWaste = shipRequirementsInTermsOfWaste;
	}

	@JSON
	public String getRemarks() {
		if (_remarks == null) {
			return StringPool.BLANK;
		}
		else {
			return _remarks;
		}
	}

	public void setRemarks(String remarks) {
		_remarks = remarks;
	}

	@JSON
	public String getNumberCargoDeclaration() {
		if (_numberCargoDeclaration == null) {
			return StringPool.BLANK;
		}
		else {
			return _numberCargoDeclaration;
		}
	}

	public void setNumberCargoDeclaration(String numberCargoDeclaration) {
		_numberCargoDeclaration = numberCargoDeclaration;
	}

	@JSON
	public String getNumberShipStoreDeclaration() {
		if (_numberShipStoreDeclaration == null) {
			return StringPool.BLANK;
		}
		else {
			return _numberShipStoreDeclaration;
		}
	}

	public void setNumberShipStoreDeclaration(String numberShipStoreDeclaration) {
		_numberShipStoreDeclaration = numberShipStoreDeclaration;
	}

	@JSON
	public String getNumberCrewList() {
		if (_numberCrewList == null) {
			return StringPool.BLANK;
		}
		else {
			return _numberCrewList;
		}
	}

	public void setNumberCrewList(String numberCrewList) {
		_numberCrewList = numberCrewList;
	}

	@JSON
	public String getNumberPassengerList() {
		if (_numberPassengerList == null) {
			return StringPool.BLANK;
		}
		else {
			return _numberPassengerList;
		}
	}

	public void setNumberPassengerList(String numberPassengerList) {
		_numberPassengerList = numberPassengerList;
	}

	@JSON
	public String getNumberCrewEffects() {
		if (_numberCrewEffects == null) {
			return StringPool.BLANK;
		}
		else {
			return _numberCrewEffects;
		}
	}

	public void setNumberCrewEffects(String numberCrewEffects) {
		_numberCrewEffects = numberCrewEffects;
	}

	@JSON
	public String getNumberHealthMaritime() {
		if (_numberHealthMaritime == null) {
			return StringPool.BLANK;
		}
		else {
			return _numberHealthMaritime;
		}
	}

	public void setNumberHealthMaritime(String numberHealthMaritime) {
		_numberHealthMaritime = numberHealthMaritime;
	}

	@JSON
	public String getSignPlace() {
		if (_signPlace == null) {
			return StringPool.BLANK;
		}
		else {
			return _signPlace;
		}
	}

	public void setSignPlace(String signPlace) {
		_signPlace = signPlace;
	}

	@JSON
	public Date getSignDate() {
		return _signDate;
	}

	public void setSignDate(Date signDate) {
		_signDate = signDate;
	}

	@JSON
	public int getMasterSigned() {
		return _masterSigned;
	}

	public void setMasterSigned(int masterSigned) {
		_masterSigned = masterSigned;
	}

	@JSON
	public int getMasterSignedImage() {
		return _masterSignedImage;
	}

	public void setMasterSignedImage(int masterSignedImage) {
		_masterSignedImage = masterSignedImage;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public TempGeneralDeclaration toEscapedModel() {
		if (_escapedModelProxy == null) {
			_escapedModelProxy = (TempGeneralDeclaration)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelProxyInterfaces,
					new AutoEscapeBeanHandler(this));
		}

		return _escapedModelProxy;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		if (_expandoBridge == null) {
			_expandoBridge = ExpandoBridgeFactoryUtil.getExpandoBridge(0,
					TempGeneralDeclaration.class.getName(), getPrimaryKey());
		}

		return _expandoBridge;
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		getExpandoBridge().setAttributes(serviceContext);
	}

	@Override
	public Object clone() {
		TempGeneralDeclarationImpl tempGeneralDeclarationImpl = new TempGeneralDeclarationImpl();

		tempGeneralDeclarationImpl.setId(getId());
		tempGeneralDeclarationImpl.setRequestCode(getRequestCode());
		tempGeneralDeclarationImpl.setRequestState(getRequestState());
		tempGeneralDeclarationImpl.setDocumentName(getDocumentName());
		tempGeneralDeclarationImpl.setDocumentYear(getDocumentYear());
		tempGeneralDeclarationImpl.setUserCreated(getUserCreated());
		tempGeneralDeclarationImpl.setIsArrival(getIsArrival());
		tempGeneralDeclarationImpl.setNameOfShip(getNameOfShip());
		tempGeneralDeclarationImpl.setShipTypeCode(getShipTypeCode());
		tempGeneralDeclarationImpl.setImoNumber(getImoNumber());
		tempGeneralDeclarationImpl.setCallSign(getCallSign());
		tempGeneralDeclarationImpl.setVoyageNumber(getVoyageNumber());
		tempGeneralDeclarationImpl.setPortOfArrivalCode(getPortOfArrivalCode());
		tempGeneralDeclarationImpl.setDateOfArrival(getDateOfArrival());
		tempGeneralDeclarationImpl.setPortHarbourCode(getPortHarbourCode());
		tempGeneralDeclarationImpl.setPortRegionCode(getPortRegionCode());
		tempGeneralDeclarationImpl.setPortWharfCode(getPortWharfCode());
		tempGeneralDeclarationImpl.setFlagStateOfShip(getFlagStateOfShip());
		tempGeneralDeclarationImpl.setNameOfMaster(getNameOfMaster());
		tempGeneralDeclarationImpl.setLastPortOfCallCode(getLastPortOfCallCode());
		tempGeneralDeclarationImpl.setCertificateOfRegistryNumber(getCertificateOfRegistryNumber());
		tempGeneralDeclarationImpl.setCertificateOfRegistryDate(getCertificateOfRegistryDate());
		tempGeneralDeclarationImpl.setCertificateOfRegistryPortName(getCertificateOfRegistryPortName());
		tempGeneralDeclarationImpl.setTaxCodeOfShipownersAgents(getTaxCodeOfShipownersAgents());
		tempGeneralDeclarationImpl.setNameOfShipownersAgents(getNameOfShipownersAgents());
		tempGeneralDeclarationImpl.setShipAgencyAddress(getShipAgencyAddress());
		tempGeneralDeclarationImpl.setShipAgencyPhone(getShipAgencyPhone());
		tempGeneralDeclarationImpl.setShipAgencyFax(getShipAgencyFax());
		tempGeneralDeclarationImpl.setShipAgencyEmail(getShipAgencyEmail());
		tempGeneralDeclarationImpl.setGrossTonnage(getGrossTonnage());
		tempGeneralDeclarationImpl.setNetTonnage(getNetTonnage());
		tempGeneralDeclarationImpl.setPositionOfShipInport(getPositionOfShipInport());
		tempGeneralDeclarationImpl.setBriefParticularsOfVoyage(getBriefParticularsOfVoyage());
		tempGeneralDeclarationImpl.setBriefDescriptionOfTheCargo(getBriefDescriptionOfTheCargo());
		tempGeneralDeclarationImpl.setNumberOfCrew(getNumberOfCrew());
		tempGeneralDeclarationImpl.setNumberOfPassengers(getNumberOfPassengers());
		tempGeneralDeclarationImpl.setShipRequirementsInTermsOfWaste(getShipRequirementsInTermsOfWaste());
		tempGeneralDeclarationImpl.setRemarks(getRemarks());
		tempGeneralDeclarationImpl.setNumberCargoDeclaration(getNumberCargoDeclaration());
		tempGeneralDeclarationImpl.setNumberShipStoreDeclaration(getNumberShipStoreDeclaration());
		tempGeneralDeclarationImpl.setNumberCrewList(getNumberCrewList());
		tempGeneralDeclarationImpl.setNumberPassengerList(getNumberPassengerList());
		tempGeneralDeclarationImpl.setNumberCrewEffects(getNumberCrewEffects());
		tempGeneralDeclarationImpl.setNumberHealthMaritime(getNumberHealthMaritime());
		tempGeneralDeclarationImpl.setSignPlace(getSignPlace());
		tempGeneralDeclarationImpl.setSignDate(getSignDate());
		tempGeneralDeclarationImpl.setMasterSigned(getMasterSigned());
		tempGeneralDeclarationImpl.setMasterSignedImage(getMasterSignedImage());

		tempGeneralDeclarationImpl.resetOriginalValues();

		return tempGeneralDeclarationImpl;
	}

	public int compareTo(TempGeneralDeclaration tempGeneralDeclaration) {
		int value = 0;

		if (getId() < tempGeneralDeclaration.getId()) {
			value = -1;
		}
		else if (getId() > tempGeneralDeclaration.getId()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		TempGeneralDeclaration tempGeneralDeclaration = null;

		try {
			tempGeneralDeclaration = (TempGeneralDeclaration)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		long primaryKey = tempGeneralDeclaration.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		TempGeneralDeclarationModelImpl tempGeneralDeclarationModelImpl = this;

		tempGeneralDeclarationModelImpl._originalRequestCode = tempGeneralDeclarationModelImpl._requestCode;

		tempGeneralDeclarationModelImpl._originalRequestState = tempGeneralDeclarationModelImpl._requestState;

		tempGeneralDeclarationModelImpl._setOriginalRequestState = false;

		tempGeneralDeclarationModelImpl._originalDocumentName = tempGeneralDeclarationModelImpl._documentName;

		tempGeneralDeclarationModelImpl._setOriginalDocumentName = false;

		tempGeneralDeclarationModelImpl._originalDocumentYear = tempGeneralDeclarationModelImpl._documentYear;

		tempGeneralDeclarationModelImpl._setOriginalDocumentYear = false;

		tempGeneralDeclarationModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<TempGeneralDeclaration> toCacheModel() {
		TempGeneralDeclarationCacheModel tempGeneralDeclarationCacheModel = new TempGeneralDeclarationCacheModel();

		tempGeneralDeclarationCacheModel.id = getId();

		tempGeneralDeclarationCacheModel.requestCode = getRequestCode();

		String requestCode = tempGeneralDeclarationCacheModel.requestCode;

		if ((requestCode != null) && (requestCode.length() == 0)) {
			tempGeneralDeclarationCacheModel.requestCode = null;
		}

		tempGeneralDeclarationCacheModel.requestState = getRequestState();

		tempGeneralDeclarationCacheModel.documentName = getDocumentName();

		tempGeneralDeclarationCacheModel.documentYear = getDocumentYear();

		tempGeneralDeclarationCacheModel.userCreated = getUserCreated();

		String userCreated = tempGeneralDeclarationCacheModel.userCreated;

		if ((userCreated != null) && (userCreated.length() == 0)) {
			tempGeneralDeclarationCacheModel.userCreated = null;
		}

		tempGeneralDeclarationCacheModel.isArrival = getIsArrival();

		tempGeneralDeclarationCacheModel.nameOfShip = getNameOfShip();

		String nameOfShip = tempGeneralDeclarationCacheModel.nameOfShip;

		if ((nameOfShip != null) && (nameOfShip.length() == 0)) {
			tempGeneralDeclarationCacheModel.nameOfShip = null;
		}

		tempGeneralDeclarationCacheModel.shipTypeCode = getShipTypeCode();

		String shipTypeCode = tempGeneralDeclarationCacheModel.shipTypeCode;

		if ((shipTypeCode != null) && (shipTypeCode.length() == 0)) {
			tempGeneralDeclarationCacheModel.shipTypeCode = null;
		}

		tempGeneralDeclarationCacheModel.imoNumber = getImoNumber();

		String imoNumber = tempGeneralDeclarationCacheModel.imoNumber;

		if ((imoNumber != null) && (imoNumber.length() == 0)) {
			tempGeneralDeclarationCacheModel.imoNumber = null;
		}

		tempGeneralDeclarationCacheModel.callSign = getCallSign();

		String callSign = tempGeneralDeclarationCacheModel.callSign;

		if ((callSign != null) && (callSign.length() == 0)) {
			tempGeneralDeclarationCacheModel.callSign = null;
		}

		tempGeneralDeclarationCacheModel.voyageNumber = getVoyageNumber();

		String voyageNumber = tempGeneralDeclarationCacheModel.voyageNumber;

		if ((voyageNumber != null) && (voyageNumber.length() == 0)) {
			tempGeneralDeclarationCacheModel.voyageNumber = null;
		}

		tempGeneralDeclarationCacheModel.portOfArrivalCode = getPortOfArrivalCode();

		String portOfArrivalCode = tempGeneralDeclarationCacheModel.portOfArrivalCode;

		if ((portOfArrivalCode != null) && (portOfArrivalCode.length() == 0)) {
			tempGeneralDeclarationCacheModel.portOfArrivalCode = null;
		}

		Date dateOfArrival = getDateOfArrival();

		if (dateOfArrival != null) {
			tempGeneralDeclarationCacheModel.dateOfArrival = dateOfArrival.getTime();
		}
		else {
			tempGeneralDeclarationCacheModel.dateOfArrival = Long.MIN_VALUE;
		}

		tempGeneralDeclarationCacheModel.portHarbourCode = getPortHarbourCode();

		String portHarbourCode = tempGeneralDeclarationCacheModel.portHarbourCode;

		if ((portHarbourCode != null) && (portHarbourCode.length() == 0)) {
			tempGeneralDeclarationCacheModel.portHarbourCode = null;
		}

		tempGeneralDeclarationCacheModel.portRegionCode = getPortRegionCode();

		String portRegionCode = tempGeneralDeclarationCacheModel.portRegionCode;

		if ((portRegionCode != null) && (portRegionCode.length() == 0)) {
			tempGeneralDeclarationCacheModel.portRegionCode = null;
		}

		tempGeneralDeclarationCacheModel.portWharfCode = getPortWharfCode();

		String portWharfCode = tempGeneralDeclarationCacheModel.portWharfCode;

		if ((portWharfCode != null) && (portWharfCode.length() == 0)) {
			tempGeneralDeclarationCacheModel.portWharfCode = null;
		}

		tempGeneralDeclarationCacheModel.flagStateOfShip = getFlagStateOfShip();

		String flagStateOfShip = tempGeneralDeclarationCacheModel.flagStateOfShip;

		if ((flagStateOfShip != null) && (flagStateOfShip.length() == 0)) {
			tempGeneralDeclarationCacheModel.flagStateOfShip = null;
		}

		tempGeneralDeclarationCacheModel.nameOfMaster = getNameOfMaster();

		String nameOfMaster = tempGeneralDeclarationCacheModel.nameOfMaster;

		if ((nameOfMaster != null) && (nameOfMaster.length() == 0)) {
			tempGeneralDeclarationCacheModel.nameOfMaster = null;
		}

		tempGeneralDeclarationCacheModel.lastPortOfCallCode = getLastPortOfCallCode();

		String lastPortOfCallCode = tempGeneralDeclarationCacheModel.lastPortOfCallCode;

		if ((lastPortOfCallCode != null) && (lastPortOfCallCode.length() == 0)) {
			tempGeneralDeclarationCacheModel.lastPortOfCallCode = null;
		}

		tempGeneralDeclarationCacheModel.certificateOfRegistryNumber = getCertificateOfRegistryNumber();

		String certificateOfRegistryNumber = tempGeneralDeclarationCacheModel.certificateOfRegistryNumber;

		if ((certificateOfRegistryNumber != null) &&
				(certificateOfRegistryNumber.length() == 0)) {
			tempGeneralDeclarationCacheModel.certificateOfRegistryNumber = null;
		}

		Date certificateOfRegistryDate = getCertificateOfRegistryDate();

		if (certificateOfRegistryDate != null) {
			tempGeneralDeclarationCacheModel.certificateOfRegistryDate = certificateOfRegistryDate.getTime();
		}
		else {
			tempGeneralDeclarationCacheModel.certificateOfRegistryDate = Long.MIN_VALUE;
		}

		tempGeneralDeclarationCacheModel.certificateOfRegistryPortName = getCertificateOfRegistryPortName();

		String certificateOfRegistryPortName = tempGeneralDeclarationCacheModel.certificateOfRegistryPortName;

		if ((certificateOfRegistryPortName != null) &&
				(certificateOfRegistryPortName.length() == 0)) {
			tempGeneralDeclarationCacheModel.certificateOfRegistryPortName = null;
		}

		tempGeneralDeclarationCacheModel.taxCodeOfShipownersAgents = getTaxCodeOfShipownersAgents();

		String taxCodeOfShipownersAgents = tempGeneralDeclarationCacheModel.taxCodeOfShipownersAgents;

		if ((taxCodeOfShipownersAgents != null) &&
				(taxCodeOfShipownersAgents.length() == 0)) {
			tempGeneralDeclarationCacheModel.taxCodeOfShipownersAgents = null;
		}

		tempGeneralDeclarationCacheModel.nameOfShipownersAgents = getNameOfShipownersAgents();

		String nameOfShipownersAgents = tempGeneralDeclarationCacheModel.nameOfShipownersAgents;

		if ((nameOfShipownersAgents != null) &&
				(nameOfShipownersAgents.length() == 0)) {
			tempGeneralDeclarationCacheModel.nameOfShipownersAgents = null;
		}

		tempGeneralDeclarationCacheModel.shipAgencyAddress = getShipAgencyAddress();

		String shipAgencyAddress = tempGeneralDeclarationCacheModel.shipAgencyAddress;

		if ((shipAgencyAddress != null) && (shipAgencyAddress.length() == 0)) {
			tempGeneralDeclarationCacheModel.shipAgencyAddress = null;
		}

		tempGeneralDeclarationCacheModel.shipAgencyPhone = getShipAgencyPhone();

		String shipAgencyPhone = tempGeneralDeclarationCacheModel.shipAgencyPhone;

		if ((shipAgencyPhone != null) && (shipAgencyPhone.length() == 0)) {
			tempGeneralDeclarationCacheModel.shipAgencyPhone = null;
		}

		tempGeneralDeclarationCacheModel.shipAgencyFax = getShipAgencyFax();

		String shipAgencyFax = tempGeneralDeclarationCacheModel.shipAgencyFax;

		if ((shipAgencyFax != null) && (shipAgencyFax.length() == 0)) {
			tempGeneralDeclarationCacheModel.shipAgencyFax = null;
		}

		tempGeneralDeclarationCacheModel.shipAgencyEmail = getShipAgencyEmail();

		String shipAgencyEmail = tempGeneralDeclarationCacheModel.shipAgencyEmail;

		if ((shipAgencyEmail != null) && (shipAgencyEmail.length() == 0)) {
			tempGeneralDeclarationCacheModel.shipAgencyEmail = null;
		}

		tempGeneralDeclarationCacheModel.grossTonnage = getGrossTonnage();

		tempGeneralDeclarationCacheModel.netTonnage = getNetTonnage();

		tempGeneralDeclarationCacheModel.positionOfShipInport = getPositionOfShipInport();

		String positionOfShipInport = tempGeneralDeclarationCacheModel.positionOfShipInport;

		if ((positionOfShipInport != null) &&
				(positionOfShipInport.length() == 0)) {
			tempGeneralDeclarationCacheModel.positionOfShipInport = null;
		}

		tempGeneralDeclarationCacheModel.briefParticularsOfVoyage = getBriefParticularsOfVoyage();

		String briefParticularsOfVoyage = tempGeneralDeclarationCacheModel.briefParticularsOfVoyage;

		if ((briefParticularsOfVoyage != null) &&
				(briefParticularsOfVoyage.length() == 0)) {
			tempGeneralDeclarationCacheModel.briefParticularsOfVoyage = null;
		}

		tempGeneralDeclarationCacheModel.briefDescriptionOfTheCargo = getBriefDescriptionOfTheCargo();

		String briefDescriptionOfTheCargo = tempGeneralDeclarationCacheModel.briefDescriptionOfTheCargo;

		if ((briefDescriptionOfTheCargo != null) &&
				(briefDescriptionOfTheCargo.length() == 0)) {
			tempGeneralDeclarationCacheModel.briefDescriptionOfTheCargo = null;
		}

		tempGeneralDeclarationCacheModel.numberOfCrew = getNumberOfCrew();

		tempGeneralDeclarationCacheModel.numberOfPassengers = getNumberOfPassengers();

		tempGeneralDeclarationCacheModel.shipRequirementsInTermsOfWaste = getShipRequirementsInTermsOfWaste();

		String shipRequirementsInTermsOfWaste = tempGeneralDeclarationCacheModel.shipRequirementsInTermsOfWaste;

		if ((shipRequirementsInTermsOfWaste != null) &&
				(shipRequirementsInTermsOfWaste.length() == 0)) {
			tempGeneralDeclarationCacheModel.shipRequirementsInTermsOfWaste = null;
		}

		tempGeneralDeclarationCacheModel.remarks = getRemarks();

		String remarks = tempGeneralDeclarationCacheModel.remarks;

		if ((remarks != null) && (remarks.length() == 0)) {
			tempGeneralDeclarationCacheModel.remarks = null;
		}

		tempGeneralDeclarationCacheModel.numberCargoDeclaration = getNumberCargoDeclaration();

		String numberCargoDeclaration = tempGeneralDeclarationCacheModel.numberCargoDeclaration;

		if ((numberCargoDeclaration != null) &&
				(numberCargoDeclaration.length() == 0)) {
			tempGeneralDeclarationCacheModel.numberCargoDeclaration = null;
		}

		tempGeneralDeclarationCacheModel.numberShipStoreDeclaration = getNumberShipStoreDeclaration();

		String numberShipStoreDeclaration = tempGeneralDeclarationCacheModel.numberShipStoreDeclaration;

		if ((numberShipStoreDeclaration != null) &&
				(numberShipStoreDeclaration.length() == 0)) {
			tempGeneralDeclarationCacheModel.numberShipStoreDeclaration = null;
		}

		tempGeneralDeclarationCacheModel.numberCrewList = getNumberCrewList();

		String numberCrewList = tempGeneralDeclarationCacheModel.numberCrewList;

		if ((numberCrewList != null) && (numberCrewList.length() == 0)) {
			tempGeneralDeclarationCacheModel.numberCrewList = null;
		}

		tempGeneralDeclarationCacheModel.numberPassengerList = getNumberPassengerList();

		String numberPassengerList = tempGeneralDeclarationCacheModel.numberPassengerList;

		if ((numberPassengerList != null) &&
				(numberPassengerList.length() == 0)) {
			tempGeneralDeclarationCacheModel.numberPassengerList = null;
		}

		tempGeneralDeclarationCacheModel.numberCrewEffects = getNumberCrewEffects();

		String numberCrewEffects = tempGeneralDeclarationCacheModel.numberCrewEffects;

		if ((numberCrewEffects != null) && (numberCrewEffects.length() == 0)) {
			tempGeneralDeclarationCacheModel.numberCrewEffects = null;
		}

		tempGeneralDeclarationCacheModel.numberHealthMaritime = getNumberHealthMaritime();

		String numberHealthMaritime = tempGeneralDeclarationCacheModel.numberHealthMaritime;

		if ((numberHealthMaritime != null) &&
				(numberHealthMaritime.length() == 0)) {
			tempGeneralDeclarationCacheModel.numberHealthMaritime = null;
		}

		tempGeneralDeclarationCacheModel.signPlace = getSignPlace();

		String signPlace = tempGeneralDeclarationCacheModel.signPlace;

		if ((signPlace != null) && (signPlace.length() == 0)) {
			tempGeneralDeclarationCacheModel.signPlace = null;
		}

		Date signDate = getSignDate();

		if (signDate != null) {
			tempGeneralDeclarationCacheModel.signDate = signDate.getTime();
		}
		else {
			tempGeneralDeclarationCacheModel.signDate = Long.MIN_VALUE;
		}

		tempGeneralDeclarationCacheModel.masterSigned = getMasterSigned();

		tempGeneralDeclarationCacheModel.masterSignedImage = getMasterSignedImage();

		return tempGeneralDeclarationCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(97);

		sb.append("{id=");
		sb.append(getId());
		sb.append(", requestCode=");
		sb.append(getRequestCode());
		sb.append(", requestState=");
		sb.append(getRequestState());
		sb.append(", documentName=");
		sb.append(getDocumentName());
		sb.append(", documentYear=");
		sb.append(getDocumentYear());
		sb.append(", userCreated=");
		sb.append(getUserCreated());
		sb.append(", isArrival=");
		sb.append(getIsArrival());
		sb.append(", nameOfShip=");
		sb.append(getNameOfShip());
		sb.append(", shipTypeCode=");
		sb.append(getShipTypeCode());
		sb.append(", imoNumber=");
		sb.append(getImoNumber());
		sb.append(", callSign=");
		sb.append(getCallSign());
		sb.append(", voyageNumber=");
		sb.append(getVoyageNumber());
		sb.append(", portOfArrivalCode=");
		sb.append(getPortOfArrivalCode());
		sb.append(", dateOfArrival=");
		sb.append(getDateOfArrival());
		sb.append(", portHarbourCode=");
		sb.append(getPortHarbourCode());
		sb.append(", portRegionCode=");
		sb.append(getPortRegionCode());
		sb.append(", portWharfCode=");
		sb.append(getPortWharfCode());
		sb.append(", flagStateOfShip=");
		sb.append(getFlagStateOfShip());
		sb.append(", nameOfMaster=");
		sb.append(getNameOfMaster());
		sb.append(", lastPortOfCallCode=");
		sb.append(getLastPortOfCallCode());
		sb.append(", certificateOfRegistryNumber=");
		sb.append(getCertificateOfRegistryNumber());
		sb.append(", certificateOfRegistryDate=");
		sb.append(getCertificateOfRegistryDate());
		sb.append(", certificateOfRegistryPortName=");
		sb.append(getCertificateOfRegistryPortName());
		sb.append(", taxCodeOfShipownersAgents=");
		sb.append(getTaxCodeOfShipownersAgents());
		sb.append(", nameOfShipownersAgents=");
		sb.append(getNameOfShipownersAgents());
		sb.append(", shipAgencyAddress=");
		sb.append(getShipAgencyAddress());
		sb.append(", shipAgencyPhone=");
		sb.append(getShipAgencyPhone());
		sb.append(", shipAgencyFax=");
		sb.append(getShipAgencyFax());
		sb.append(", shipAgencyEmail=");
		sb.append(getShipAgencyEmail());
		sb.append(", grossTonnage=");
		sb.append(getGrossTonnage());
		sb.append(", netTonnage=");
		sb.append(getNetTonnage());
		sb.append(", positionOfShipInport=");
		sb.append(getPositionOfShipInport());
		sb.append(", briefParticularsOfVoyage=");
		sb.append(getBriefParticularsOfVoyage());
		sb.append(", briefDescriptionOfTheCargo=");
		sb.append(getBriefDescriptionOfTheCargo());
		sb.append(", numberOfCrew=");
		sb.append(getNumberOfCrew());
		sb.append(", numberOfPassengers=");
		sb.append(getNumberOfPassengers());
		sb.append(", shipRequirementsInTermsOfWaste=");
		sb.append(getShipRequirementsInTermsOfWaste());
		sb.append(", remarks=");
		sb.append(getRemarks());
		sb.append(", numberCargoDeclaration=");
		sb.append(getNumberCargoDeclaration());
		sb.append(", numberShipStoreDeclaration=");
		sb.append(getNumberShipStoreDeclaration());
		sb.append(", numberCrewList=");
		sb.append(getNumberCrewList());
		sb.append(", numberPassengerList=");
		sb.append(getNumberPassengerList());
		sb.append(", numberCrewEffects=");
		sb.append(getNumberCrewEffects());
		sb.append(", numberHealthMaritime=");
		sb.append(getNumberHealthMaritime());
		sb.append(", signPlace=");
		sb.append(getSignPlace());
		sb.append(", signDate=");
		sb.append(getSignDate());
		sb.append(", masterSigned=");
		sb.append(getMasterSigned());
		sb.append(", masterSignedImage=");
		sb.append(getMasterSignedImage());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(148);

		sb.append("<model><model-name>");
		sb.append("vn.gt.dao.noticeandmessage.model.TempGeneralDeclaration");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>id</column-name><column-value><![CDATA[");
		sb.append(getId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>requestCode</column-name><column-value><![CDATA[");
		sb.append(getRequestCode());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>requestState</column-name><column-value><![CDATA[");
		sb.append(getRequestState());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>documentName</column-name><column-value><![CDATA[");
		sb.append(getDocumentName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>documentYear</column-name><column-value><![CDATA[");
		sb.append(getDocumentYear());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userCreated</column-name><column-value><![CDATA[");
		sb.append(getUserCreated());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>isArrival</column-name><column-value><![CDATA[");
		sb.append(getIsArrival());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>nameOfShip</column-name><column-value><![CDATA[");
		sb.append(getNameOfShip());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>shipTypeCode</column-name><column-value><![CDATA[");
		sb.append(getShipTypeCode());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>imoNumber</column-name><column-value><![CDATA[");
		sb.append(getImoNumber());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>callSign</column-name><column-value><![CDATA[");
		sb.append(getCallSign());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>voyageNumber</column-name><column-value><![CDATA[");
		sb.append(getVoyageNumber());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>portOfArrivalCode</column-name><column-value><![CDATA[");
		sb.append(getPortOfArrivalCode());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>dateOfArrival</column-name><column-value><![CDATA[");
		sb.append(getDateOfArrival());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>portHarbourCode</column-name><column-value><![CDATA[");
		sb.append(getPortHarbourCode());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>portRegionCode</column-name><column-value><![CDATA[");
		sb.append(getPortRegionCode());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>portWharfCode</column-name><column-value><![CDATA[");
		sb.append(getPortWharfCode());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>flagStateOfShip</column-name><column-value><![CDATA[");
		sb.append(getFlagStateOfShip());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>nameOfMaster</column-name><column-value><![CDATA[");
		sb.append(getNameOfMaster());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>lastPortOfCallCode</column-name><column-value><![CDATA[");
		sb.append(getLastPortOfCallCode());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>certificateOfRegistryNumber</column-name><column-value><![CDATA[");
		sb.append(getCertificateOfRegistryNumber());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>certificateOfRegistryDate</column-name><column-value><![CDATA[");
		sb.append(getCertificateOfRegistryDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>certificateOfRegistryPortName</column-name><column-value><![CDATA[");
		sb.append(getCertificateOfRegistryPortName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>taxCodeOfShipownersAgents</column-name><column-value><![CDATA[");
		sb.append(getTaxCodeOfShipownersAgents());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>nameOfShipownersAgents</column-name><column-value><![CDATA[");
		sb.append(getNameOfShipownersAgents());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>shipAgencyAddress</column-name><column-value><![CDATA[");
		sb.append(getShipAgencyAddress());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>shipAgencyPhone</column-name><column-value><![CDATA[");
		sb.append(getShipAgencyPhone());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>shipAgencyFax</column-name><column-value><![CDATA[");
		sb.append(getShipAgencyFax());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>shipAgencyEmail</column-name><column-value><![CDATA[");
		sb.append(getShipAgencyEmail());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>grossTonnage</column-name><column-value><![CDATA[");
		sb.append(getGrossTonnage());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>netTonnage</column-name><column-value><![CDATA[");
		sb.append(getNetTonnage());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>positionOfShipInport</column-name><column-value><![CDATA[");
		sb.append(getPositionOfShipInport());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>briefParticularsOfVoyage</column-name><column-value><![CDATA[");
		sb.append(getBriefParticularsOfVoyage());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>briefDescriptionOfTheCargo</column-name><column-value><![CDATA[");
		sb.append(getBriefDescriptionOfTheCargo());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>numberOfCrew</column-name><column-value><![CDATA[");
		sb.append(getNumberOfCrew());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>numberOfPassengers</column-name><column-value><![CDATA[");
		sb.append(getNumberOfPassengers());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>shipRequirementsInTermsOfWaste</column-name><column-value><![CDATA[");
		sb.append(getShipRequirementsInTermsOfWaste());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>remarks</column-name><column-value><![CDATA[");
		sb.append(getRemarks());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>numberCargoDeclaration</column-name><column-value><![CDATA[");
		sb.append(getNumberCargoDeclaration());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>numberShipStoreDeclaration</column-name><column-value><![CDATA[");
		sb.append(getNumberShipStoreDeclaration());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>numberCrewList</column-name><column-value><![CDATA[");
		sb.append(getNumberCrewList());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>numberPassengerList</column-name><column-value><![CDATA[");
		sb.append(getNumberPassengerList());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>numberCrewEffects</column-name><column-value><![CDATA[");
		sb.append(getNumberCrewEffects());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>numberHealthMaritime</column-name><column-value><![CDATA[");
		sb.append(getNumberHealthMaritime());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>signPlace</column-name><column-value><![CDATA[");
		sb.append(getSignPlace());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>signDate</column-name><column-value><![CDATA[");
		sb.append(getSignDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>masterSigned</column-name><column-value><![CDATA[");
		sb.append(getMasterSigned());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>masterSignedImage</column-name><column-value><![CDATA[");
		sb.append(getMasterSignedImage());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = TempGeneralDeclaration.class.getClassLoader();
	private static Class<?>[] _escapedModelProxyInterfaces = new Class[] {
			TempGeneralDeclaration.class
		};
	private long _id;
	private String _requestCode;
	private String _originalRequestCode;
	private int _requestState;
	private int _originalRequestState;
	private boolean _setOriginalRequestState;
	private long _documentName;
	private long _originalDocumentName;
	private boolean _setOriginalDocumentName;
	private int _documentYear;
	private int _originalDocumentYear;
	private boolean _setOriginalDocumentYear;
	private String _userCreated;
	private int _isArrival;
	private String _nameOfShip;
	private String _shipTypeCode;
	private String _imoNumber;
	private String _callSign;
	private String _voyageNumber;
	private String _portOfArrivalCode;
	private Date _dateOfArrival;
	private String _portHarbourCode;
	private String _portRegionCode;
	private String _portWharfCode;
	private String _flagStateOfShip;
	private String _nameOfMaster;
	private String _lastPortOfCallCode;
	private String _certificateOfRegistryNumber;
	private Date _certificateOfRegistryDate;
	private String _certificateOfRegistryPortName;
	private String _taxCodeOfShipownersAgents;
	private String _nameOfShipownersAgents;
	private String _shipAgencyAddress;
	private String _shipAgencyPhone;
	private String _shipAgencyFax;
	private String _shipAgencyEmail;
	private double _grossTonnage;
	private double _netTonnage;
	private String _positionOfShipInport;
	private String _briefParticularsOfVoyage;
	private String _briefDescriptionOfTheCargo;
	private int _numberOfCrew;
	private int _numberOfPassengers;
	private String _shipRequirementsInTermsOfWaste;
	private String _remarks;
	private String _numberCargoDeclaration;
	private String _numberShipStoreDeclaration;
	private String _numberCrewList;
	private String _numberPassengerList;
	private String _numberCrewEffects;
	private String _numberHealthMaritime;
	private String _signPlace;
	private Date _signDate;
	private int _masterSigned;
	private int _masterSignedImage;
	private transient ExpandoBridge _expandoBridge;
	private long _columnBitmask;
	private TempGeneralDeclaration _escapedModelProxy;
}