/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.gt.dao.danhmuc.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import vn.gt.dao.danhmuc.model.DmHistoryPort;
import vn.gt.dao.danhmuc.service.DmHistoryPortLocalServiceUtil;

/**
 * The extended model base implementation for the DmHistoryPort service. Represents a row in the &quot;DM_HISTORY_PORT&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link DmHistoryPortImpl}.
 * </p>
 *
 * @author win_64
 * @see DmHistoryPortImpl
 * @see vn.gt.dao.danhmuc.model.DmHistoryPort
 * @generated
 */
public abstract class DmHistoryPortBaseImpl extends DmHistoryPortModelImpl
	implements DmHistoryPort {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a dm history port model instance should use the {@link DmHistoryPort} interface instead.
	 */
	public void persist() throws SystemException {
		if (this.isNew()) {
			DmHistoryPortLocalServiceUtil.addDmHistoryPort(this);
		}
		else {
			DmHistoryPortLocalServiceUtil.updateDmHistoryPort(this);
		}
	}
}