/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.gt.dao.danhmuc.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;

import vn.gt.dao.danhmuc.model.DmHistoryPortHarbour;
import vn.gt.dao.danhmuc.model.DmHistoryPortHarbourModel;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;

/**
 * The base model implementation for the DmHistoryPortHarbour service. Represents a row in the &quot;DM_HISTORY_PORT_HARBOUR&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link vn.gt.dao.danhmuc.model.DmHistoryPortHarbourModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link DmHistoryPortHarbourImpl}.
 * </p>
 *
 * @author win_64
 * @see DmHistoryPortHarbourImpl
 * @see vn.gt.dao.danhmuc.model.DmHistoryPortHarbour
 * @see vn.gt.dao.danhmuc.model.DmHistoryPortHarbourModel
 * @generated
 */
public class DmHistoryPortHarbourModelImpl extends BaseModelImpl<DmHistoryPortHarbour>
	implements DmHistoryPortHarbourModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a dm history port harbour model instance should use the {@link vn.gt.dao.danhmuc.model.DmHistoryPortHarbour} interface instead.
	 */
	public static final String TABLE_NAME = "DM_HISTORY_PORT_HARBOUR";
	public static final Object[][] TABLE_COLUMNS = {
			{ "id", Types.INTEGER },
			{ "PortHarbourCode", Types.VARCHAR },
			{ "PortHarbourName", Types.VARCHAR },
			{ "PortHarbourNameVN", Types.VARCHAR },
			{ "PortHarbourType", Types.INTEGER },
			{ "PortCode", Types.VARCHAR },
			{ "PortRegionCode", Types.VARCHAR },
			{ "Note", Types.VARCHAR },
			{ "IsDelete", Types.INTEGER },
			{ "MarkedAsDelete", Types.INTEGER },
			{ "ModifiedDate", Types.TIMESTAMP },
			{ "RequestedDate", Types.TIMESTAMP },
			{ "SyncVersion", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table DM_HISTORY_PORT_HARBOUR (id INTEGER not null primary key,PortHarbourCode VARCHAR(75) null,PortHarbourName VARCHAR(75) null,PortHarbourNameVN VARCHAR(75) null,PortHarbourType INTEGER,PortCode VARCHAR(75) null,PortRegionCode VARCHAR(75) null,Note VARCHAR(75) null,IsDelete INTEGER,MarkedAsDelete INTEGER,ModifiedDate DATE null,RequestedDate DATE null,SyncVersion VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table DM_HISTORY_PORT_HARBOUR";
	public static final String ORDER_BY_JPQL = " ORDER BY dmHistoryPortHarbour.id ASC";
	public static final String ORDER_BY_SQL = " ORDER BY DM_HISTORY_PORT_HARBOUR.id ASC";
	public static final String DATA_SOURCE = "gtDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.vn.gt.dao.danhmuc.model.DmHistoryPortHarbour"),
			false);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.vn.gt.dao.danhmuc.model.DmHistoryPortHarbour"),
			false);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.vn.gt.dao.danhmuc.model.DmHistoryPortHarbour"),
			true);
	public static long PORTHARBOURCODE_COLUMN_BITMASK = 1L;
	public static long PORTREGIONCODE_COLUMN_BITMASK = 2L;
	public static long SYNCVERSION_COLUMN_BITMASK = 4L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.vn.gt.dao.danhmuc.model.DmHistoryPortHarbour"));

	public DmHistoryPortHarbourModelImpl() {
	}

	public int getPrimaryKey() {
		return _id;
	}

	public void setPrimaryKey(int primaryKey) {
		setId(primaryKey);
	}

	public Serializable getPrimaryKeyObj() {
		return new Integer(_id);
	}

	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Integer)primaryKeyObj).intValue());
	}

	public Class<?> getModelClass() {
		return DmHistoryPortHarbour.class;
	}

	public String getModelClassName() {
		return DmHistoryPortHarbour.class.getName();
	}

	public int getId() {
		return _id;
	}

	public void setId(int id) {
		_columnBitmask = -1L;

		_id = id;
	}

	public String getPortHarbourCode() {
		if (_portHarbourCode == null) {
			return StringPool.BLANK;
		}
		else {
			return _portHarbourCode;
		}
	}

	public void setPortHarbourCode(String portHarbourCode) {
		_columnBitmask |= PORTHARBOURCODE_COLUMN_BITMASK;

		if (_originalPortHarbourCode == null) {
			_originalPortHarbourCode = _portHarbourCode;
		}

		_portHarbourCode = portHarbourCode;
	}

	public String getOriginalPortHarbourCode() {
		return GetterUtil.getString(_originalPortHarbourCode);
	}

	public String getPortHarbourName() {
		if (_portHarbourName == null) {
			return StringPool.BLANK;
		}
		else {
			return _portHarbourName;
		}
	}

	public void setPortHarbourName(String portHarbourName) {
		_portHarbourName = portHarbourName;
	}

	public String getPortHarbourNameVN() {
		if (_portHarbourNameVN == null) {
			return StringPool.BLANK;
		}
		else {
			return _portHarbourNameVN;
		}
	}

	public void setPortHarbourNameVN(String portHarbourNameVN) {
		_portHarbourNameVN = portHarbourNameVN;
	}

	public int getPortHarbourType() {
		return _portHarbourType;
	}

	public void setPortHarbourType(int portHarbourType) {
		_portHarbourType = portHarbourType;
	}

	public String getPortCode() {
		if (_portCode == null) {
			return StringPool.BLANK;
		}
		else {
			return _portCode;
		}
	}

	public void setPortCode(String portCode) {
		_portCode = portCode;
	}

	public String getPortRegionCode() {
		if (_portRegionCode == null) {
			return StringPool.BLANK;
		}
		else {
			return _portRegionCode;
		}
	}

	public void setPortRegionCode(String portRegionCode) {
		_columnBitmask |= PORTREGIONCODE_COLUMN_BITMASK;

		if (_originalPortRegionCode == null) {
			_originalPortRegionCode = _portRegionCode;
		}

		_portRegionCode = portRegionCode;
	}

	public String getOriginalPortRegionCode() {
		return GetterUtil.getString(_originalPortRegionCode);
	}

	public String getNote() {
		if (_note == null) {
			return StringPool.BLANK;
		}
		else {
			return _note;
		}
	}

	public void setNote(String note) {
		_note = note;
	}

	public int getIsDelete() {
		return _isDelete;
	}

	public void setIsDelete(int isDelete) {
		_isDelete = isDelete;
	}

	public int getMarkedAsDelete() {
		return _markedAsDelete;
	}

	public void setMarkedAsDelete(int markedAsDelete) {
		_markedAsDelete = markedAsDelete;
	}

	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {
		_modifiedDate = modifiedDate;
	}

	public Date getRequestedDate() {
		return _requestedDate;
	}

	public void setRequestedDate(Date requestedDate) {
		_requestedDate = requestedDate;
	}

	public String getSyncVersion() {
		if (_syncVersion == null) {
			return StringPool.BLANK;
		}
		else {
			return _syncVersion;
		}
	}

	public void setSyncVersion(String syncVersion) {
		_columnBitmask |= SYNCVERSION_COLUMN_BITMASK;

		if (_originalSyncVersion == null) {
			_originalSyncVersion = _syncVersion;
		}

		_syncVersion = syncVersion;
	}

	public String getOriginalSyncVersion() {
		return GetterUtil.getString(_originalSyncVersion);
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public DmHistoryPortHarbour toEscapedModel() {
		if (_escapedModelProxy == null) {
			_escapedModelProxy = (DmHistoryPortHarbour)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelProxyInterfaces,
					new AutoEscapeBeanHandler(this));
		}

		return _escapedModelProxy;
	}

	@Override
	public Object clone() {
		DmHistoryPortHarbourImpl dmHistoryPortHarbourImpl = new DmHistoryPortHarbourImpl();

		dmHistoryPortHarbourImpl.setId(getId());
		dmHistoryPortHarbourImpl.setPortHarbourCode(getPortHarbourCode());
		dmHistoryPortHarbourImpl.setPortHarbourName(getPortHarbourName());
		dmHistoryPortHarbourImpl.setPortHarbourNameVN(getPortHarbourNameVN());
		dmHistoryPortHarbourImpl.setPortHarbourType(getPortHarbourType());
		dmHistoryPortHarbourImpl.setPortCode(getPortCode());
		dmHistoryPortHarbourImpl.setPortRegionCode(getPortRegionCode());
		dmHistoryPortHarbourImpl.setNote(getNote());
		dmHistoryPortHarbourImpl.setIsDelete(getIsDelete());
		dmHistoryPortHarbourImpl.setMarkedAsDelete(getMarkedAsDelete());
		dmHistoryPortHarbourImpl.setModifiedDate(getModifiedDate());
		dmHistoryPortHarbourImpl.setRequestedDate(getRequestedDate());
		dmHistoryPortHarbourImpl.setSyncVersion(getSyncVersion());

		dmHistoryPortHarbourImpl.resetOriginalValues();

		return dmHistoryPortHarbourImpl;
	}

	public int compareTo(DmHistoryPortHarbour dmHistoryPortHarbour) {
		int value = 0;

		if (getId() < dmHistoryPortHarbour.getId()) {
			value = -1;
		}
		else if (getId() > dmHistoryPortHarbour.getId()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		DmHistoryPortHarbour dmHistoryPortHarbour = null;

		try {
			dmHistoryPortHarbour = (DmHistoryPortHarbour)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		int primaryKey = dmHistoryPortHarbour.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		DmHistoryPortHarbourModelImpl dmHistoryPortHarbourModelImpl = this;

		dmHistoryPortHarbourModelImpl._originalPortHarbourCode = dmHistoryPortHarbourModelImpl._portHarbourCode;

		dmHistoryPortHarbourModelImpl._originalPortRegionCode = dmHistoryPortHarbourModelImpl._portRegionCode;

		dmHistoryPortHarbourModelImpl._originalSyncVersion = dmHistoryPortHarbourModelImpl._syncVersion;

		dmHistoryPortHarbourModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<DmHistoryPortHarbour> toCacheModel() {
		DmHistoryPortHarbourCacheModel dmHistoryPortHarbourCacheModel = new DmHistoryPortHarbourCacheModel();

		dmHistoryPortHarbourCacheModel.id = getId();

		dmHistoryPortHarbourCacheModel.portHarbourCode = getPortHarbourCode();

		String portHarbourCode = dmHistoryPortHarbourCacheModel.portHarbourCode;

		if ((portHarbourCode != null) && (portHarbourCode.length() == 0)) {
			dmHistoryPortHarbourCacheModel.portHarbourCode = null;
		}

		dmHistoryPortHarbourCacheModel.portHarbourName = getPortHarbourName();

		String portHarbourName = dmHistoryPortHarbourCacheModel.portHarbourName;

		if ((portHarbourName != null) && (portHarbourName.length() == 0)) {
			dmHistoryPortHarbourCacheModel.portHarbourName = null;
		}

		dmHistoryPortHarbourCacheModel.portHarbourNameVN = getPortHarbourNameVN();

		String portHarbourNameVN = dmHistoryPortHarbourCacheModel.portHarbourNameVN;

		if ((portHarbourNameVN != null) && (portHarbourNameVN.length() == 0)) {
			dmHistoryPortHarbourCacheModel.portHarbourNameVN = null;
		}

		dmHistoryPortHarbourCacheModel.portHarbourType = getPortHarbourType();

		dmHistoryPortHarbourCacheModel.portCode = getPortCode();

		String portCode = dmHistoryPortHarbourCacheModel.portCode;

		if ((portCode != null) && (portCode.length() == 0)) {
			dmHistoryPortHarbourCacheModel.portCode = null;
		}

		dmHistoryPortHarbourCacheModel.portRegionCode = getPortRegionCode();

		String portRegionCode = dmHistoryPortHarbourCacheModel.portRegionCode;

		if ((portRegionCode != null) && (portRegionCode.length() == 0)) {
			dmHistoryPortHarbourCacheModel.portRegionCode = null;
		}

		dmHistoryPortHarbourCacheModel.note = getNote();

		String note = dmHistoryPortHarbourCacheModel.note;

		if ((note != null) && (note.length() == 0)) {
			dmHistoryPortHarbourCacheModel.note = null;
		}

		dmHistoryPortHarbourCacheModel.isDelete = getIsDelete();

		dmHistoryPortHarbourCacheModel.markedAsDelete = getMarkedAsDelete();

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			dmHistoryPortHarbourCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			dmHistoryPortHarbourCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		Date requestedDate = getRequestedDate();

		if (requestedDate != null) {
			dmHistoryPortHarbourCacheModel.requestedDate = requestedDate.getTime();
		}
		else {
			dmHistoryPortHarbourCacheModel.requestedDate = Long.MIN_VALUE;
		}

		dmHistoryPortHarbourCacheModel.syncVersion = getSyncVersion();

		String syncVersion = dmHistoryPortHarbourCacheModel.syncVersion;

		if ((syncVersion != null) && (syncVersion.length() == 0)) {
			dmHistoryPortHarbourCacheModel.syncVersion = null;
		}

		return dmHistoryPortHarbourCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(27);

		sb.append("{id=");
		sb.append(getId());
		sb.append(", portHarbourCode=");
		sb.append(getPortHarbourCode());
		sb.append(", portHarbourName=");
		sb.append(getPortHarbourName());
		sb.append(", portHarbourNameVN=");
		sb.append(getPortHarbourNameVN());
		sb.append(", portHarbourType=");
		sb.append(getPortHarbourType());
		sb.append(", portCode=");
		sb.append(getPortCode());
		sb.append(", portRegionCode=");
		sb.append(getPortRegionCode());
		sb.append(", note=");
		sb.append(getNote());
		sb.append(", isDelete=");
		sb.append(getIsDelete());
		sb.append(", markedAsDelete=");
		sb.append(getMarkedAsDelete());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", requestedDate=");
		sb.append(getRequestedDate());
		sb.append(", syncVersion=");
		sb.append(getSyncVersion());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(43);

		sb.append("<model><model-name>");
		sb.append("vn.gt.dao.danhmuc.model.DmHistoryPortHarbour");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>id</column-name><column-value><![CDATA[");
		sb.append(getId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>portHarbourCode</column-name><column-value><![CDATA[");
		sb.append(getPortHarbourCode());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>portHarbourName</column-name><column-value><![CDATA[");
		sb.append(getPortHarbourName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>portHarbourNameVN</column-name><column-value><![CDATA[");
		sb.append(getPortHarbourNameVN());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>portHarbourType</column-name><column-value><![CDATA[");
		sb.append(getPortHarbourType());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>portCode</column-name><column-value><![CDATA[");
		sb.append(getPortCode());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>portRegionCode</column-name><column-value><![CDATA[");
		sb.append(getPortRegionCode());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>note</column-name><column-value><![CDATA[");
		sb.append(getNote());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>isDelete</column-name><column-value><![CDATA[");
		sb.append(getIsDelete());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>markedAsDelete</column-name><column-value><![CDATA[");
		sb.append(getMarkedAsDelete());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>requestedDate</column-name><column-value><![CDATA[");
		sb.append(getRequestedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>syncVersion</column-name><column-value><![CDATA[");
		sb.append(getSyncVersion());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = DmHistoryPortHarbour.class.getClassLoader();
	private static Class<?>[] _escapedModelProxyInterfaces = new Class[] {
			DmHistoryPortHarbour.class
		};
	private int _id;
	private String _portHarbourCode;
	private String _originalPortHarbourCode;
	private String _portHarbourName;
	private String _portHarbourNameVN;
	private int _portHarbourType;
	private String _portCode;
	private String _portRegionCode;
	private String _originalPortRegionCode;
	private String _note;
	private int _isDelete;
	private int _markedAsDelete;
	private Date _modifiedDate;
	private Date _requestedDate;
	private String _syncVersion;
	private String _originalSyncVersion;
	private long _columnBitmask;
	private DmHistoryPortHarbour _escapedModelProxy;
}